### ISSUE TITLE
[regression - 8.0.7-9.1.0] Fix native fullscreen on macOS

### ISSUE THREAD

**Issue by firefinchdev** [nativefier/nativefier#1006]
**Problem statement**
macOS supports two types of fullscreen: Zoom and Native Full Screen. Zoom will maximize the window similar to Windows/Ubuntu. Native Full Screen maximizes the window to its own separate workspace. This is used by default by all macOS apps (all 3rd party incl.)
It would be nice to have Native full screen on pressing maximize(green) button.

- [X ] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md , no existing option fits my needs.
- [ X] I searched existing open & closed issues. Yes, my issue is new.

**Suggested solution**
Electron definitely supports native full screen as electron apps are able to full screen natively. Thus it must be possible to include it as an option in nativefier.

**Comment by axelav** [comment]
This worked in version `8.0.7` but I just upgraded to `9.1.0` and it is broken.

**Comment by navinkumarg** [comment]
I am facing the same issue. Please look into it :)

**Comment by rvanmazijk** [comment]
Issue persists in `10.1.0` (on macOS Catalina `10.15.6` (`19G2021`)).

But, interestingly, when using `nativefier --full-screen '<url>'` to force the app to open in native full-screen: that works!

And, I can exit full-screen and re-enter it with no issues using the native window controls:

<img width="306" alt="Screenshot 2020-09-08 at 11 53 47" src="https://user-images.githubusercontent.com/30973454/92461807-f804b500-f1c9-11ea-8482-357d15a9126e.png">

**Comment by AlJohri** [comment]
I'm also running into this issue of missing native full screen on macOS. In addition, when creating an app for YouTube, the video doesn't full screen to the entire monitor- it only fills the app window.

**Comment by ZepDonald** [comment]
I'm having the same problem on Catalina with the latest version of Nativefier (via Homebrew).

After fiddling around a bit and reading some documentation of Nativefier and Electron I tried adding the following parameter:

``
--browserwindow-options '{ "fullscreenable": "true", "simpleFullscreen": "false" }'
``

That fixes my problem and windows behave as they should regarding fullscreen support. Maybe this helps in finding a general solution. If not, it is (at least for me) a possible workaround.

**Comment by hnlkaitan** [comment]
Don't think this works on Big Sur... I ran `brew update` just to be sure , as well as copy-pasting your parameter (but those already the defaults, no? Or would this imply there's a bug with it). It still only zooms (not the native macOS fullscreen) for me.

Macbook Pro (2019), macOS Big Sur 11.2.1

**Comment by TheCleric** [comment]
@firefinchdev @axelav @navinkumarg @rvanmazijk @AlJohri @ZepDonald can anyone confirm if this is still an issue with the latest version? When clicking maximize for me on the latest version on Catalina, it seems to be maximizing to Native full screen (on its own workspace).

**Comment by ZepDonald** [comment]
For now native fullscreen is working like expected. Thanks for fixing this bug.
