### ISSUE TITLE
How to quit application on button click, or windows close window event

### ISSUE THREAD

**Issue by ikiK-CRO** [nativefier/nativefier#1013]
First of all I would like to mention I never build ELECTRON application before, I did read some documentation but some things are confusing on how they work. 

Been using nativefier for some time on MAC but now I have build my remote web application  for windows. And I have noticed that after I close window there are 4 background process left. They are using around 60MB RAM. 

I researched how to  quit app on windows and this is suggested solution:
[electronjs.org/docs](https://www.electronjs.org/docs/api/app)

**To make it default:**
```
const { app } = require('electron')
app.on('window-all-closed', () => {
  app.quit()
})
```
**1. Question one:** 
_[fast-quit] options is macOS only in nativefier_
Above code needs to be added to main.js. I found main.js in app  for windows after nativefier build and added code above et end of it but nothing happens, processes are still there. 

**2. Question two:** 
But I would like to make a button inside my app that will quit it (windows and OSX), and suggestion from SO is to just use:
`  app.quit()`
When I add this line in (in-web-app) JS that is called on press of button I get: `app is not defined`. Can someone explain how to make it work?

I am generally interested in how to use some of native electron options and call it inside my app, where and how should I add/edit those things. I tried putting some things into `injected.js `they didn't work. I have read a lot of topics here, electron and SO in last couple of months and I still dot understand this.
I see I can add `browserwindow-options` from electron native options with nativefier but events from upper questions are not mentioned in those. 

There are also a lot of electron plugins that would be helpful, is it possible to use them while building with nativefier?

Sorry for long post, i have been using nativefer for months now and I would really like to expand my knowledge on this and I can not find relevant info. I would really appreciate any guidance.

Also thanks to all maintaining this, its amazingly helpful!

**Comment by ronjouch** [comment]
Grep for `exit` and `quit` in our codebase to see what we do. For example,

https://github.com/nativefier/nativefier/blob/b3c202fd331aa43216c4d71c86092cc377970bae/app/src/components/trayIcon.ts#L41-L42

and

https://github.com/nativefier/nativefier/blob/b3c202fd331aa43216c4d71c86092cc377970bae/app/src/main.ts#L171-L182

Good luck with your projects!
