### ISSUE TITLE
Support wrapping with Tauri instead of Electron

### ISSUE THREAD

**Issue by gregpalaci** [nativefier/nativefier#1018]
Would be awesome to investigate https://tauri.studio/en/ instead of electron as the wrapper. Could output applications with a much smaller filesize

**Comment by Gulivertx** [comment]
is there anyone already trying to embed a web-site with Tauri ?

**Comment by Milo123459** [comment]
Any news? I think using tauri would be a good addition as not only is it more secure, it's more lightweight, making it a better product. Also, when the new tauri autoupdater comes out, we could use a fast and secure autoupdater to update the nativeifed apps. Ie, on launch, check for updates.

**Comment by TheCleric** [comment]
I can't speak for anyone else, but this strikes me as something best left as a separate project. Looking at Tauri it has the following downsides that would make it complicated to integrate with Nativefier:

- Requires a separate set of setup steps for each platform that someone wants to run it from (which Nativefier would then have to ask downstream users to perform if they want to use Tauri). Compared to the simplicity of `npm install [-g] nativefier` that seems a little onerous to me.
- According to [their docs](https://tauri.studio/en/docs/usage/ci-cd/cross-platform), they currently do not support cross platform app creation, which would be a step down in terms of supported features.

**Comment by Milo123459** [comment]
Well yes, but I have a soloution! A server that generates the projects on demand. Or, you can just create feature request issues in the tauri repo

**Comment by hamza72x** [comment]
Here we go: https://github.com/hamza72x/nativefier_tauri
Just did mvp in this morning, for the exact same reason. The bundle size is less than 2MB!


https://user-images.githubusercontent.com/48919542/204241689-66a411fc-b71a-49b0-9315-405b7eb53721.mp4

**Comment by egrieco** [comment]
That’s awesome! Looking forward to giving this a try.

**Comment by tw93** [comment]
Maybe you can try pake. Simply make any web page a desktop application using Rust. 
https://github.com/tw93/Pake/issues/165

**Comment by gregpalaci** [comment]
@OpenOS-Project-Creator-Founder 
Howdy I'm a contributor on [nodegui](https://docs.nodegui.org/) vue and react projects
I don't reckon it would be the right tool or an easy task to use it for this.

**Comment by OpenOS-Project-Creator-Founder** [comment]
> @OpenOS-Project-Creator-Founder 
> Howdy I'm a contributor on [nodegui](https://docs.nodegui.org/) vue and react projects
> I don't reckon it would be the right tool or an easy task to use it for this.



Would this help?

https://github.com/canonic/canonic

**Comment by gregpalaci** [comment]
@OpenOS-Project-Creator-Founder 
I totally understand your adventures in the webview desktop app sphere you can read some of my findings:
https://dev.to/jswhisperer/proton-native-gg8
https://dev.to/jswhisperer/webview-apps-on-your-os-2h6k
https://dev.to/jswhisperer/scratch-the-surface-of-nodegui-2lfo
https://dev.to/jswhisperer/nodegui-react-component-by-component-b98
I'm not affiliated with nativefier, but I can say Tauri might work in my opinion the many other libraries I've explored are interesting but not 1-1 drop in replacement for electron.
Cheers

**Comment by egrieco** [comment]
There are some other pure-rust options as well:

* [nativefier_tauri](https://lib.rs/crates/nativefier_tauri): Turn any web page into a desktop app (but, lightweight <1MB)
* [localapp](https://lib.rs/crates/localapp): Rust CLI to convert webpage into desktop app with tauri under 3 MB
* [web2app](https://lib.rs/crates/web2app): Turn any web page into a desktop app (but, lightweight <1MB)

**Comment by OpenOS-Project-Creator-Founder** [comment]
> There are some other pure-rust options as well:
> 
> * [nativefier_tauri](https://lib.rs/crates/nativefier_tauri): Turn any web page into a desktop app (but, lightweight <1MB)
> * [localapp](https://lib.rs/crates/localapp): Rust CLI to convert webpage into desktop app with tauri under 3 MB
> * [web2app](https://lib.rs/crates/web2app): Turn any web page into a desktop app (but, lightweight <1MB)



Wrap all 3 resources you shared into these...

https://github.com/rust-qt
