### ISSUE TITLE
Support for SCSS (SASS)

### ISSUE THREAD

**Issue by heyimyunyl** [nativefier/nativefier#1028]
I have tried injecting CSS file for a website, some changes I made was working while some didn't. Turns out, those not working classes are using SCSS (SASS). I wonder if we can get a feature where the app overwrites CSS over SCSS?

**Comment by ronjouch** [comment]
I don't think that's something we want done by Nativefier. Write SASS/SCSS if you want, and compile it and pass it as regular CSS to Nativefier.
