### ISSUE TITLE
Support non-latin characters (chinese, korean, ...) in --name option

### ISSUE THREAD

**Issue by Simplici** [nativefier/nativefier#1056]
support chinese characters in --name option.
currently, if i set a chinese name for --name option, for the builded app, the name is 'APP' instead of the name specified by --name.

below is my command:
nativefier "https://weread.qq.com/" -n "微信读书"

**Comment by ytbg0512** [comment]
Actually this issue seems to apply for all non-latin characters, like Korean.

**Comment by TheCleric** [comment]
This will be fixed in the next version of Nativefier.
