### ISSUE TITLE
Support packaging custom bookmarks in menubar

### ISSUE THREAD

**Issue by catinbetween** [nativefier/nativefier#1065]
**Problem statement**

I love nativefier and the options it gives, but beside the possibility to inject js code and styles or to add custom keyboard shortcuts with a json file, i really missed an option to add custom bookmarks to the menu bar. For example, i have lots of online classes these days that are either on webex or zoom or whereever, and i don't really want to install the chrome-addons on my linux.  If i just opened these tabs in my browser that would work, but they would get lost over time and i end up having clutter of  20-30 tabs that are the same.  So i wanted  a program that "has them all".

**Suggested solution**

I've already made my own fork from master where i added some stuff to the menu builder - which reads a json.config in the root folder and then adds them to a new menu entry. (see latest commits in [my forked version](https://github.com/catinbetween/nativefier) and also the readme)

Basically the current state is that you add a label with the according url that, when you click on that entry, will take you to the url (online meeting in my case). You can also add submenus and separators. And there is one entry that opens a popup where you can enter a custom URL ( also meeting url in my case).  It's basically an "inject menu" feature.

It worked wonderfully for me, so.. Is this a feature that would be appreciated or useful to someone else? If yes, i'd be happy to contribute since i've already done it. I'd also put some more work into it so it can be used with a command option (something like ``nativefier --inject-menu config.js [..]``. That, some code cleanup and then a pull request. 

**Context**

 - Nativefier: 10.1.0
 - Node.js: v10.19.0
 - Npm: 6.14.4
 - OS:  Ubuntu 20.04

**Homework**

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md , no existing option fits my needs.
- [x] I searched existing issues, open & closed. Yes, my feature request is new.
- [x] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Comment by ronjouch** [comment]
@catinbetween hi, maintainer here. Thanks for offering! I don't remember of similar feature requests, presumably because people use the search/favorites feature of apps they bundle, but I can understand it's nice to have bookmarks to reach stuff you use frequently even faster (I use bookmarks a lot myself in my main browser).

So, leaving open to see if passersby upvote it, and yeah I'll take an eventual PR. If you go for it, please start with a concise RFC here, to settle what the flag looks like and minimize PR back & forth. Thanks!
