### ISSUE TITLE
No Notifications on Ubuntu with Google Messages?

### ISSUE THREAD

**Issue by BrodyStone21** [nativefier/nativefier#1078]
So just learned about Nativefier today, installed it, and went through the process of turning the link www.messages.google.com/web into an application and it's working fine. However, I don't receive any notifications at all, I am currently on the latest stable release of Ubuntu (installed yesterday). I tried reinstalling the web wrapper a few times but with no luck. I did do some digging around and saw that people have had issues with Google Teams and Google Voice, along with issues for notifications in general with Ubuntu, I did find a link to a temporary fix that was using javascript or something like that but I couldn't get it to work either.

Does anyone have any ideas? My system fully up to date along with everything I'm using.

Edit: I did want to mention whether I keep the process running but close the window, or if I minimize the window, still no notifications. Let me know if you guys need any more information.

**Comment by ronjouch** [comment]
Probably fixed with `--user-agent firefox`, see https://github.com/nativefier/nativefier/blob/master/CATALOG.md#google-apps . If that doesn't help, chime in and I'll re-open the issue.
