### ISSUE TITLE
MacOS libffmpeg.dylib error and Electron crash

### ISSUE THREAD

**Issue by pidtuner** [nativefier/nativefier#1087]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [ ] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

Using latest **Docker** version.

**Bug description**

Crashes when running on MacOs 10.12 Sierra. Using latest Docker version on the [pidtuner PWA](https://pidtuner.com).

First got a `Library not loaded: @rpath/libffmpeg.dylib` error which I fixed by copying the library to the system as detailed in [this Electron issue](https://github.com/electron/electron/issues/4765). Is there any way to avoid having to do this?

Then an Electron crash. **I attach both reports in the Debug Info section**.

```
Process:               PIDTuner [733]
Path:                  /Users/USER/Desktop/*/PIDTuner.app/Contents/MacOS/PIDTuner
Identifier:            com.electron.pidtuner
Version:               1.0.0 (1.0.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           PIDTuner [733]
User ID:               501

Date/Time:             2020-12-15 17:31:03.824 +0100
OS Version:            Mac OS X 10.12 (16A323)
Report Version:        12
Anonymous UUID:        D7AFE68B-E9EC-31F1-DD4F-6781DBA0E758

Sleep/Wake UUID:       DECCEDBE-EB3C-47C4-B9E4-96925B3A94ED

Time Awake Since Boot: 2100 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Trace/BPT trap: 5
Termination Reason:    Namespace SIGNAL, Code 0x5
Terminating Process:   exc handler [0]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   Electron Framework            	0x000000010950f465 ElectronInitializeICUandStartNode + 1867413
1   Electron Framework            	0x000000010adf6b71 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 2634865
2   Electron Framework            	0x000000010d37aad4 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 41972692
3   Electron Framework            	0x000000010a077684 ElectronInitializeICUandStartNode + 13828276
4   Electron Framework            	0x0000000109347594 ElectronMain + 84
5   com.electron.pidtuner         	0x0000000109312110 0x109311000 + 4368
6   libdyld.dylib                 	0x00007fffa78c4255 start + 1
```

**Steps to reproduce**

Built on Linux for the [pidtuner PWA](https://pidtuner.com) using the following command:

```bash
docker run --rm -v /home/user/Documents/nativefier:/target/:Z jiahaog/nativefier -p osx --name 'PIDTuner' https://pidtuner.com/ /target/
```

**Expected behavior**

Not to crash.

**Actual behavior**

Crashed

**Debug info**

[err1.txt](https://github.com/jiahaog/nativefier/files/5697269/err1.txt)

[err2.txt](https://github.com/jiahaog/nativefier/files/5697270/err2.txt)

**Context**

 - Docker build for MacOS for [https://pidtuner.com](https://pidtuner.com).

**Comment by ronjouch** [comment]
@pidtuner does it keep crashing with a different/newer [version of Electron](https://github.com/electron/electron/releases) (which you pass to Nativefier with flag `-e`) ?

**Comment by ronjouch** [comment]
Closing as issue wasn't reproducible and didn't get feedback. feel free to chime in and re-open the discussion anytime 🙂!
