### ISSUE TITLE
The futex facility returned an unexpected error code. [1]    47792 abort (core dumped)

### ISSUE THREAD

**Issue by Zerafiall** [nativefier/nativefier#1088]
No idea what I'm doing wrong. If the error was more descriptive I probably could've gotten it working by now. But...

``The futex facility returned an unexpected error code.``

``[1]    47792 abort (core dumped)  ./TogglTrack``

- Running Arch Linux 5.9.14-arch1-1 
- nativefier --version:  42.0.2
- npm --version: 6.14.9

I tried googling both lines to no information. Best I can tell is fatux is some kernal level multi threading.... thing. And core dump is just a crash. 

Dug though the --help and API Docs page. Nothing about error and crashes. 

Dug through the issues pages and couldn't find anything.

**Comment by ronjouch** [comment]
@Zerafiall no idea either. Please provide the information requested by the [bug report issue template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by ronjouch** [comment]
Hi @Zerafiall.

1. Please try with another [version of Electron](https://github.com/electron/electron/releases), which you can pass using flag `-e`
2. If it still crashes, please come back with the information requested by the [bug report issue template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), and I'll re-open
