### ISSUE TITLE
Cannot login - Prime Video

### ISSUE THREAD

**Issue by AshH2O** [nativefier/nativefier#1092]
I know that this has been talked about in issue #706 and after referring to it, I packaged www.primevideo.com with this:
`nativefier https://www.primevideo.com --name PrimeVideo --widevine --bounce --width 800px --height 500px --title-bar-style hidden --single-instance --internal-urls “www\.amazon\.com/ap/signin”`
When I press the continue login button, it opens the url specified in the `--internal-urls` flag. Please help.
1. Entered info
![Screenshot 2020-12-30 at 10 27 59](https://user-images.githubusercontent.com/70855558/103331033-084ae380-4a8a-11eb-82a8-be29ba83d99d.png)
2. It is opened in my browser
![Screenshot 2020-12-30 at 10 28 38](https://user-images.githubusercontent.com/70855558/103331055-1993f000-4a8a-11eb-97e1-dafc7f0d7fc0.png)

**Comment by Paderman** [comment]
Hello :smiley:
I was testing and I tried it with `--internal-urls ".*?"` instead yours and it opens within from _nativefier_
Here in Germany, I can only use amazon.de for login & content :frowning_face:

**Comment by ronjouch** [comment]
> I was testing and I tried it with `--internal-urls ".*?"` instead yours and it opens within from _nativefier_

👍
