### ISSUE TITLE
Support for Mac OS menu bar popover

### ISSUE THREAD

**Issue by isometriq** [nativefier/nativefier#1093]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md , no existing option fits my needs.
- [x] I searched existing issues, open & closed. Yes, my feature request is new.
- [x] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Problem statement**

Nativefier is fantastic and is a great way to sandbox usage with specific web apps. Some of the packaged web app are ones that are useful to peek at from time to time, just for a status check. 

**Suggested solution**

Support Mac OS menu bar popover feature? Example:
https://github.com/sozercan/electron-menubar

This would allow to take a quick look a the web app status.

I don't know the implications or complexity.

**Alternative solutions**

- I don't know if electron config arguments can help, but I'm feeling that it's not.
- Maybe a window management app could handle this behavior. Any ideas?
- I thought that maybe the `--tray` flag was for this purpose, but an error occurs when generate app is launched. The app works, but the flag does not seem to have any effect, other than the error message. I can elaborate about that if it is relevant.

**Context**

 - Nativefier: 42.0.2
 - Node.js: 14.13.1
 - Npm: 6.14.8
 - OS: Mac OS Catalina 10.15.7 (19H114)
 - Additional context: been using the latest docker: jiahaog/nativefier

**Comment by isometriq** [comment]
Maybe a duplicate of or related to
https://github.com/jiahaog/nativefier/issues/318

**Comment by isometriq** [comment]
Here they call it "status bar apps"
https://www.bzgapps.com/unite

**Comment by ronjouch** [comment]
> Maybe a duplicate of or related to #318

Yes, closing this issue, and reopening #318, which has more discussion in it.
