### ISSUE TITLE
Is it possible to have a transparent window?

### ISSUE THREAD

**Issue by Aiyush-G** [nativefier/nativefier#1106]
Hi, 

I was wondering whether it is possible to have a transparent window using natifier 
I am on macOS Catalina.

I look forward to your response
AG

**Comment by ronjouch** [comment]
@Aiyush-G yes, see https://github.com/nativefier/nativefier/blob/master/docs/api.md#browserwindow-options , which links to https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions , which offers an `opacity` option.
