### ISSUE TITLE
"Please update your browser" message on Android Messages app

### ISSUE THREAD

**Issue by tom-tb9394** [nativefier/nativefier#1107]
Hi there, I've recently downloaded the Android Messages app for my MacBook Pro on macOS Big Sur 11.1, however, I have received the message, "You are using an out of date version of your web browser, please update to the latest version before using Messages for web." I updated my chrome browser yesterday and it now says that it is on the latest version (supposedly filling the requirements by the android messages app) however, I am still getting the update chrome browser message when I open the Android messages app. Any suggestions on how I can fix this to get the android messages app working?

**Comment by Cyberoid** [comment]
I'm getting the same message using macOS Catalina 10.5.7 on my Macbook Pro.  It prevents me from accessing Android Messages on my Mac.  Of course, the application works fine on my Android phone.

**Comment by Itai-Nelken** [comment]
I'm getting the same message but with a whatsapp web nativefier webapp

**Comment by ronjouch** [comment]
Does the issue persist after re-building your apps with a [newer version of Electron](https://github.com/electron/electron/releases), which you pass to Nativefier with flag `-e` ?

**Comment by TheCleric** [comment]
@tom-tb9394 or @Cyberoid  Is the app you downloaded, from here?

https://github.com/chrisknepper/android-messages-desktop

**Comment by TheCleric** [comment]
Closing as I have not heard a response back. We can reopen if anyone is still experiencing this.
