### ISSUE TITLE
2 Bugs

### ISSUE THREAD

**Issue by xvzhenduo** [nativefier/nativefier#1108]
Hi'
1.When I hide window frame ,I can't close the window because the "close" button is also hidden.
2.When I use "--clear-cache" and "--tray" wen I click the "close" button and then I click the tray then I found the cache was beeen clear.
3.I can't login my Google account in nativefier,it says the broswer is not safe.

**Comment by xvzhenduo** [comment]
> Hi'
> 1.When I hide window frame ,I can't close the window because the "close" button is also hidden.
> 2.When I use "--clear-cache" and "--tray" wen I click the "close" button and then I click the tray then I found the cache was beeen clear.
> 3.I can't login my Google account in nativefier,it says the broswer is not safe.

**Comment by ronjouch** [comment]
Hi.

1. Uh, what else do you expect? You hid the window frame, didn't you? Close it using keyboard shortcuts.
2. Expected
3. See https://github.com/nativefier/nativefier/issues/1112
