### ISSUE TITLE
--single-instance not working properly

### ISSUE THREAD

**Issue by mlscherer** [nativefier/nativefier#1109]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

When I build an app using the --single-instance flag, it starts another instance when I click in a link with target="_blank" inside the application directing to the same URL as the application.

**Steps to reproduce**

When i start an application using a domain like "example.com", using the --single-instance flag, every time I click in a link like: `<a href="https://example.com/test">Test</a>` it will start another instance of the application.

```
nativefier https://example.com/ --platform windows --min-width 800 --min-height 600 --maximize --hide-window-frame --disable-dev-tools --single-instance --tray --file-download-options "{\"saveAs\": false, \"directory\": \"C:\/Downloads\/123\"}" --background-color #EEEEEE
```

**Expected behavior**

I expected the application to open the link in a browser, the same way other URLs do. I believe that if someone needs this behavior, it shouldn't use the "--single-instance" flag...

**Actual behavior**

When I click the link it starts another instance for the application.

**Context**

 - Nativefier: 42.2.1
 - Node.js: 14.15.4
 - Npm: 6.14.10
 - OS: Using both Windows and MacOS

**Comment by cybermoloch** [comment]
This is intended. --single-instance prevents launching the application multiple times. Having multiple windows/browser views open is still the same instance/process.

I am not sure how to get around that with the current APIs if it is on the same domain. I would think a new option --single-window might be what you are looking for but that doesn't exist yet.

**Comment by m-bp** [comment]
Very interested in this as it is one of the main reasons why I'd use Nativefier

**Comment by TheCleric** [comment]
@mlscherer it seems to me what you are expecting here is less 'single instance' (of a running application) and more 'single window'. Would you agree?

**Comment by TheCleric** [comment]
Closing this for now. Will reopen if we can get a clarification on the desired behavior.
