### ISSUE TITLE
--name and --app-copyright flags do not allow space between the texts

### ISSUE THREAD

**Issue by mlscherer** [nativefier/nativefier#1110]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**
When building an app with the name "My App Name", it will only consider the first word, and the app will be named "My". Same thing happens with the copyright flag.

**Steps to reproduce**

I'm using this command to build the app:
```nativefier example.com --name My App Name --app-copyright My App Name --platform windows --min-width 800 --min-height 600```

**Expected behavior**

The app to be named "My App Name"

**Actual behavior**

The app is named "My"

**Context**

Nativefier: 42.2.1
Node.js: 14.15.4
Npm: 6.14.10
OS: Using both Windows and MacOS

**Comment by sarweshparajuli** [comment]
Insert double quotes, as in:

`nativefier example.com --name "My App Name" --app-copyright "My App Name" --platform "windows" --min-width "800" --min-height "600"`

**Comment by mlscherer** [comment]
Thanks @sarweshparajuli ! It really worked.

As a suggestion for improvement, I think it would be interesting to make this more clear in the documentation....
