### ISSUE TITLE
Cannot seem to use subdomains

### ISSUE THREAD

**Issue by tristanjones247** [nativefier/nativefier#1113]
Cannot seem to be able to use a sub-domain when creating an application. is there a prefix required before the subdomain, to allow for subdomains?

 - Nativefier: 42.2.1
 - Node.js: v14.15.4
 - Npm: 6.14.10
 - OS: (for example: Mac OSX)

**Comment by ronjouch** [comment]
Hi @tristanjones247 . I don't understand the question, please precise it. https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE/bug_report.md might be helpful.
