### ISSUE TITLE
Globally installing Nativefier breaks Linux systems by changing sudo permissions

### ISSUE THREAD

**Issue by Itai-Nelken** [nativefier/nativefier#1117]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

I recently updated nativefier on my Raspberry Pi running [TwisterOS](https://twisteros.com/) (based on RaspberryPi OS), then I did something else that required a reboot. after the reboot I got errors from sudo and this error from dbus: `org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.blueman.Mechanism: permission denied`. I changed the permission of the broken sudo file by logging in to the root account, but still got that error and wifi wasn't working.
I didn't suspect nativefier at all, I thought I had done something wrong, so I reflashed my ssd and after installing nativefier and rebooting, I got the same errors! I still didn't suspect nativefier.
this time I reflashed the ssd with regular plain RaspberryPiOS, and it worked perfectly fine untill I installed nativefier, then suddenly sudo stopped working, I changed its permissions again and so far its still working ok (I didn't reboot yet).

Right now I'm 100% sure nativefier is causing this.
could this happen because I'm installing nativefier with sudo (`sudo npm install -g nativefier`) because otherwise it fails?

**Steps to reproduce**
1) Flash a RPiOS image to a sd card/SSD/USB stick.
2) boot the pi.
3) install node.js (I installed 15.x).
4) run `sudo npm install -g nativefier`.
5) try to run sudo, it will fail.

**Expected behavior**

I expected sudo to work fine after installing nativefier.

**Actual behavior**

sudo broke and caused some other things like wifi to break.

**Context**

 - Node.js: 15.9.0
 - Npm: 7.5.3
 - OS: RaspberryPiOS and TwisterOS - RPiOS is based on Debian and TwisterOS is based on RPiOS.
- Machine: RaspberryPi 4b 4gb model.

**Comment by ronjouch** [comment]
@Itai-Nelken uuuuuuh that's a weird one. I don't see how the `npm install -g` could have barfed your install so hard. Can you still reproduce this bug, and are you 101% sure it's reliably attributable to Nativefier?

**Comment by ronjouch** [comment]
Also, which permissions does your broken `sudo` have?

**Comment by bachmannn** [comment]
Might need codereview sounds more like NSA backdoor or malware

**Comment by Itai-Nelken** [comment]
> @Itai-Nelken uuuuuuh that's a weird one. I don't see how the `npm install -g` could have barfed your install so hard. Can you still reproduce this bug, and are you 101% sure it's reliably attributable to Nativefier?

I'll try to reproduce this again next week, but it happened 3 times in a row after installing nativefier. so I'm pretty sure is caused by it.

**Comment by Itai-Nelken** [comment]
@ronjouch I think I found the issue: installing node.js from apt (using the nodesource repo) breaks the permissions, I installed node.js using `nvm` and I didn't even need `sudo` to install nativefier.

**Comment by Itai-Nelken** [comment]
This doesn't have anything to do with nativefier.
I have been using it with node.js installed uwing `nvm` for a few weeks and didn't get any issues so far.
