### ISSUE TITLE
Bundling Flash / Pointing a flashPluginDir with relative path or folder inside application

### ISSUE THREAD

**Issue by bleidd** [nativefier/nativefier#1123]
I've tried to build on OSX with 
-e 11.3.0 --flash-path "/Users/usr/flash/PepperFlashPlayer.plugin" -- direct an 'absolute' path to plugin and it worked. 
- [x] I searched existing issues, open & closed. Yes, my feature request is new, some of them are:
(https://github.com/nativefier/nativefier/issues/385) - pointing directly to desired Pepperflash - worked
(https://github.com/nativefier/nativefier/issues/45) - there was some workaround to make local index.html
- I'm using the latest version available at https://github.com/nativefier/nativefier/releases (42.3.0)

I know that Flash is a round way back, but there are some good flash-based games, those didn't manage to transfer to newer platforms, and I'm coming from one of them in a struggle to keep it alive.

I need a way to make an electron-based client for end users with bundled in Flash support.

So, it would be great to find a way to point a path to PepperFlash Plugin inside an app.

I've already tried building app, and then changing 'flashPluginDir' to:
```
'"flashPluginDir":"PepperFlashPlayer.plugin"
"flashPluginDir":"../PepperFlashPlayer.plugin"
"flashPluginDir":"./PepperFlashPlayer.plugin"
```
with no luck.
On each try PepperFlashPlayer.plugin was put to the same dir as main.js and/or nativefier.json
like:
`/Users/usr/Electron11-darwin-x64/test_Electron11.app/Contents/Resources/app/lib/PepperFlashPlayer.plugin `
or 
`/Users/usr/Electron11-darwin-x64/test_Electron11.app/Contents/Resources/app/PepperFlashPlayer.plugin 
`

Also I've read older docs from Electron [itself](https://web.archive.org/web/20190817014551/https://www.electronjs.org/docs/tutorial/using-pepper-flash-plugin)
```
// Specify flash path, supposing it is placed in the same directory with main.js.
let pluginName
switch (process.platform) {
  case 'win32':
    pluginName = 'pepflashplayer.dll'
    break
  case 'darwin':
    pluginName = 'PepperFlashPlayer.plugin'
    break
  case 'linux':
    pluginName = 'libpepflashplayer.so'
    break
}
```
I'm suggesting to make a relative path near nativefier.json to be available as ../

Or, if this case isn't very common, please tell me what should I exactly change in main.json to make it work

**Comment by oleteacher** [comment]
Interested in this. Have a lot of flash apps for the classroom and the kids loved them. Any progress made that you can share?

**Comment by ronjouch** [comment]
> Interested in this. Have a lot of flash apps for the classroom and the kids loved them. Any progress made that you can share?

@oleteacher not the progress you want to hear, sorry 😕. You and the kids who love Flash apps/games have my sincere sympathy, but there's nothing we can do to stop this treadmill, so here it goes:

Flash is triply dead upstream at Adobe, in Chrome, and now in Electron. I just released Nativefier 43.0.0, which moves to [Electron 12, which officially removes all support for Flash](https://www.electronjs.org/blog/electron-12-0#breaking-changes).

Your best bet now is on [Ruffle, "a Flash Player emulator built in the Rust programming language"](https://ruffle.rs/). It's feasible to build webpages loading Ruffle to play embedded `.swf`s, and that's [what Archive.org does](http://blog.archive.org/2020/11/19/flash-animations-live-forever-at-the-internet-archive/).

With that, closing this issue. You might still be able to use Nativefier's Flash support, but it's only downhill from here, it will be removed when maintaining compatibility with old Electrons becomes impossible, and new features around Flash like the one requested here become clearly out of scope.

**Comment by oleteacher** [comment]
Thank you @ronjouch 

"there's nothing Nativefier can do to stop this treadmill"

Kind of figured that was the case.

Thanks for taking time to reply.

**Comment by bleidd** [comment]
> Your best bet now is on Ruffle
[Ruffle states that:](https://github.com/ruffle-rs/ruffle/issues/1368)
> AS3 content will not currently display properly in Ruffle 

> and now in Electron
[Harman](https://services.harman.com/partners/adobe), which is currently in charge of supporting Adobe Flash providing  _“Packaged Browser" solution_. This "solution" is nothing more than Electron with built-in Flash Plugin.

@oleteacher here's some workaround for you and others: 
1. Build your app with `nativefier -e 11.3.0 --flash-path null`
2. Check nativefier.json, there should be `flashPluginDir:null`, and not `flashPluginDir:"null"`
2. Now find this lines in /app/lib/main.js
```
let mainWindow;
if (typeof appArgs.flashPluginDir === 'string') {
    electron_1.app.commandLine.appendSwitch('ppapi-flash-path', appArgs.flashPluginDir);
}
```
 comment out some of it
```
//else if (appArgs.flashPluginDir) {
 //   const flashPath = inferFlash_1.inferFlashPath();
   // electron_1.app.commandLine.appendSwitch('ppapi-flash-path', flashPath); }
```
And add after them
```
else if (appArgs.flashPluginDir == null) {
				const path = require('path')
				electron_1.app.commandLine.appendSwitch('ppapi-flash-path', path.join(__dirname,'PepperFlashPlayer.plugin'))
}
```
where 'PepperFlashPlayer.plugin' - name of plugin for Mac OS
this should be 'libpepflashplayer.so' for Linux
and 'pepflashplayer.dll' for Windows

Those plugin files should be put near main.js in /app/lib/

**Comment by oleteacher** [comment]
@bleidd Great information, thank you much for sharing!

I will have to build and see what I get. Looks fairly easy so will give it a try in next day or two.

**Comment by bleidd** [comment]
https://gist.github.com/KuromeSan/56d8b724c0696b54f9f81994ae3591d1

**Comment by oleteacher** [comment]
@bleidd By chance, know the version of flash plugin (DLL) you used?

Having some issues and wanted to make sure I am using correct version.

Thank you!
