### ISSUE TITLE
Are nativefier apps commonly flagged as malware?

### ISSUE THREAD

**Issue by janniks** [nativefier/nativefier#1127]
I made a nativefier app about two years ago and today Bitdefender flagged the `.app` as `Trojan.MAC.Agent.JR`. Does this commonly occur? I rebuilt the app with the latest nativefier version and Bitdefender did not flag it any more.

I just wanted to ask if you are aware of anything similar (I tried searching but couldn't find anything).

_[Here is the faulty `.app` file](https://we.tl/t-yG3DPt5c4z) — I also scanned it using VirusTotal (_**[see results](https://www.virustotal.com/gui/file/628c8beb38ec4b9af9b069078894b512ec5bfdcf8a82a2561d79b222c5bd641d/detection)**_)_

**Comment by ronjouch** [comment]
@janniks hmmm, not that I know. Then, false positives are always possible, but did you consider the possibility that your old version was indeed actually infected?

**Comment by janniks** [comment]
I'm hoping it's false positives.

I tried to compare the executables in `./Contents/Macos` which seems to be the problem. I'm not great at reverse-engineering, but their [`strings`](https://linux.die.net/man/1/strings) looked very similar (only minor diff). So, I don't think it's a real infection. I'm also somewhat relieved that only 11/60 VirusTotal engines believe it's a virus (but also hard to tell what that actually means).

**Comment by ronjouch** [comment]
@janniks okay, and thanks for the report. One more thing: you write that you *"tried searching but couldn't find anything"*. If you searched for Nativefier in these searches (e.g. googling "nativefier executable virus"), did you try instead googling for Electron? (e.g. googling "electron executable virus")

**Comment by janniks** [comment]
Yep, I tried this and found some older cases. They are mostly confined to windows. I was hoping to find cases with the exact threat tags as the virus engines show, but no success there. 

Seems similar enough I guess. Thinking this a false positive — Thanks for the quick responses 😊

**Comment by TheCleric** [comment]
> I made a nativefier app about two years ago and today Bitdefender flagged the `.app` as `Trojan.MAC.Agent.JR`. Does this commonly occur? I rebuilt the app with the latest nativefier version and Bitdefender did not flag it any more.
> 
> I just wanted to ask if you are aware of anything similar (I tried searching but couldn't find anything).
> 
> _[Here is the faulty `.app` file](https://we.tl/t-yG3DPt5c4z) — I also scanned it using VirusTotal (_**[see results](https://www.virustotal.com/gui/file/628c8beb38ec4b9af9b069078894b512ec5bfdcf8a82a2561d79b222c5bd641d/detection)**_)_

I recreated your app with the latest version of Nativefier and it is not flagged. I would recommend doing the same. From what I see, what can happen is if someone creates a malicious app with a similar version of electron, it can look just similar enough to some virus scanners that they flag it. Best way to avoid this is to update the app with the latest version of Nativefier if this occurs.

**Comment by ronjouch** [comment]
Thanks for the extra check, @TheCleric. I don't see anything alarming, so, closing. Of course, feel free to re-open if new alerts happen.

**Comment by janniks** [comment]
@TheCleric Yes, that's what I did 🤞

@ronjouch Thanks, sounds good 👍
