### ISSUE TITLE
Nativefier should show a "Permissions Popup" for Audio / Video / Screen Sharing when necessary, like browsers do

### ISSUE THREAD

**Issue by maxnitze** [nativefier/nativefier#1129]
**Homework**

- [/] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md
- [/] I searched existing issues, open & closed. Yes, my question is new.
- [/] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Your question**

I'm using `nativefier` for Webex Teams, as there is no native Linux client yet.

It works for regular chat, but when I call someone I cannot select the correct audio device, so nobody can hear me. The problem is, that I don't get any _audio device selection window_ like I get in Chromium, for example. I have a similar issue with screen sharing: When I try to start sharing I get the message _We can't display your shared content. Make sure that you've allowed permission to share content, and then try again._

Is there an option to activate this somehow?

**Steps to reproduce**

```
nativefier --name "Webex Teams" https://teams.webex.com --internal-urls ".*\.webex\.com" --tray .temp/webex-teams
```

**Context**

 - Nativefier: 42.3.0
 - Node.js: v10.23.0
 - Npm: 6.14.8
 - OS: ArchLinux
 - Additional context: Sway (Wayland)

**Comment by TheCleric** [comment]
I'll have to investigate this in VirtualBox, but on my Mac I get the prompts for these out of the box (well except for screen sharing, that's a different animal).

For screen sharing we'll have to write our own screen selector:
https://github.com/electron/electron/issues/4432

**Comment by maxnitze** [comment]
Hey @TheCleric ,

thanks for investigating!

In case I can do/try/test anything, I'll gladly do so!

**Comment by TheCleric** [comment]
@maxnitze I was able to "replicate" this in my VirtualBox Ubuntu, but it's hard to tell if it was a true replication, or just the fact that my audio/video passthrough is a little flaky. Can you do me a favor and do the following?

1. Open the app
2. Open the dev tools (Ctrl + Shift + I)
3. Try to start or join a video call
4. Copy any errors from the console in the dev tools and paste them here

**Comment by maxnitze** [comment]
I got two errors int he console:

```
GET https://locus-k.wbx2.com/locus/api/v1/loci/meetingInfo&alternateRedirect=true 400 (Bad Request)

wx-js-sdk Meeting-info:index#requestFetchInfo -->  r: Required argument type is invalid
GET https://locus-k.wbx2.com/locus/api/v1/loci/meetingInfo&alternateRedirect=true
WEBEX_TRACKING_ID: <REDACTED>
 fetch meetingInfo
```

Not sure if this really helps you though. Are there additional parts of the message you need?

**Comment by TheCleric** [comment]
Stupid question: when you join a meeting from the browser (such as Chrome or Firefox), does the audio work correctly then?

**Comment by maxnitze** [comment]
Yes and no. The problem is, that by default the wrong device for my microphone is selected. Also in my regular browser. So my speakers are working (I can hear the others), my camera is working (they can see me), but nobody can hear me, as I would need to change the device. Which I cannot do, as I don't have the option to do so.

So maybe this does not actually have something to do with the permissions themselves, but rather with the wrong device being active and that I cannot change it.

**Comment by TheCleric** [comment]
Have you tried selecting the microphone you'd like to use as your default microphone in your linux system settings? Looking at WebEx's web app, it doesn't appear to have ability to use anything other than default (unlike their desktop apps).

**Comment by maxnitze** [comment]
Tried that, yes. But audio and devices is a big piece of sh* on Linux, imho.

Also the device changes based on my setup: Sometimes I'm connected to my docking station, sometimes I use the output on the notebook itself. And sometimes I use bluetooth headphones.

And yes in the Windows and Mac native apps and in the Webex meetings app (also on the Webapp) it is possibe to change the device from the app itself. But I get from your answer, that displaying the _choose your device_ browser popup/settings/thingy is not possible in electron, right?

**Comment by maxnitze** [comment]
Please forget my comment. I just realized, that Chrome/Chromium does not seem to have that option at all.

You can globally change the default microphone in the browser. But there is no "change it for this meeting".

It seems I mixed up Chromium and Firefox here to some extend. Firefox has this (there is a popup asking for the devices to use for sound and video when starting a call/meeting).

Ok. I will try to fix my microphone setup in my OS. Maybe that will fix it.

And for the topic of Screen Sharing: Is there an open issue for that already, that I can subscribe to?

**Comment by TheCleric** [comment]
> And yes in the Windows and Mac native apps and in the Webex meetings app (also on the Webapp) it is possibe to change the device from the app itself. But I get from your answer, that displaying the _choose your device_ browser popup/settings/thingy is not possible in electron, right?

I don't THINK so, but I could be wrong. In the end as well it would involve WebEx respecting that choice (which I don't think they technically have to, as they can read from the same audio device list that we could).

> And for the topic of Screen Sharing: Is there an open issue for that already, that I can subscribe to?

I believe we have #927 and #971 that are similarly related. I'm going to try to dig into this one soon.

**Comment by maxnitze** [comment]
I subscribed to both of them and will mark this as closed then.

Thank you very much!
