### ISSUE TITLE
Nativefier should support packaging local HTML files

### ISSUE THREAD

**Issue by lewisforster12** [nativefier/nativefier#1137]
**Homework**

- [yes ] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md
- [yes] I searched existing issues, open & closed. Yes, my bug is new.
- [yes ] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

this bug will not allow you to do anymore apps with them having a url

**Steps to reproduce**

1.open the node.js command prompt
2.cd to the dir you want to do it in
3.import any html file you want using the normal command 

```
nativefier --name (name here) html file location here
```

**Expected behavior**

make the app with it working

**Actual behavior**

electron refuses to build 

**Debug info**
Error during build. Run with --verbose (did it with verbose too) for details. Error: rcedit.exe failed with exit code 1. Fatal error: Unable to commit changes
    at ChildProcess.<anonymous> (C:\Users\Lewis\AppData\Roaming\npm\node_modules\nativefier\node_modules\rcedit\lib\rcedit.js:71:16)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

**Context**

 - Nativefier:43.0.0
 - Node.js: 14.16.0
 - Npm:6.14.11 
 - OS: Windows 10 pro 2004

**Comment by TheCleric** [comment]
Nativefier at the moment isn't designed to use static html files. Using Electron (what Nativefier is based on) may be a better fit for this use case.

@ronjouch do you agree, or do you think we should support something like the ability to `--inject` html files?

**Comment by ronjouch** [comment]
> @ronjouch do you agree, or do you think we should support something like the ability to `--inject` html files?

@TheCleric yes, I agree that I'm okay with simply not supporting this, and I already closed a few issues asking about it. On surface level it appears like "just something else `--inject`able, but then it opens a can of worms, like of injecting other types of resources (images, other html files linkable from the application, a whole folder, etc). Then what about the path of these? Etc.

Also, is it common? If it's niche, niche users can simply serve the local heap of html they want to package (with a little Python server, or Apache or Nginx) on a local port, and Nativefy http://localhost:PORT.

→ Until one or a few motivated users prove their point by writing detailed use cases and an API, I'd stay away from it.

**Comment by ronjouch** [comment]
With that, closing. @lewisforster12, if you have the time for this, do bring your case: tell us why you think it's valuable for many other users, tell us for which app you'd use it, tell us why the local server workaround I'm offering doesn't suit you. We'll listen and can re-open the issue if there's interest.
