### ISSUE TITLE
How to package for multi-platform and how do I package it so that other people can download it on my website?

### ISSUE THREAD

**Issue by talmax1124** [nativefier/nativefier#1139]

**Comment by mattruzzi** [comment]
You can use the --arch and --platform flags for each architecture/platform you want to support. 

https://github.com/nativefier/nativefier/blob/master/docs/api.md#platform

#### [platform]

```
-p, --platform <value>
```

- Default: current operating system.
    - To test your default platform you can run
      ```
      node -p "process.platform"
      ```
      (See https://nodejs.org/api/os.html#os_os_platform)
- Can be overwritten by specifying either `linux`, `windows`, `osx` or `mas` for a Mac App Store specific build.

The alternative values `win32` (for Windows) or `darwin`, `mac` (for macOS) can also be used.

#### [arch]

```
-a, --arch <value>
```

The processor architecture to target when building.

- Default: the architecture of the installed version of node (usually the architecture of the build-time machine).
    - To test your default architecture you can run
      ```
      node -p "process.arch"
      ```
      (See https://nodejs.org/api/os.html#os_os_arch)
    - Please note: On M1 Macs, unless an arm64 version of brew is used to install nodejs, the version installed will be an `x64` version run through Rosetta, and will result in an `x64` app being generated. If this is not desired, either specify `-a arm64` to build for M1, or re-install node with an arm64 version of brew. See https://github.com/nativefier/nativefier/issues/1089
- Can be overridden by specifying one of: `ia32`, `x64`, `armv7l`, `arm64`.

**Comment by ronjouch** [comment]
Thx for the pointer to docs, @mattruzzi .
