### ISSUE TITLE
WebNowPlaying Support

### ISSUE THREAD

**Issue by PhantomNimbi** [nativefier/nativefier#1142]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md , no existing option fits my needs.
- [x] I searched existing issues, open & closed. Yes, my feature request is new.
- [ ] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Problem statement**

I would suggest adding support for WebNowPlaying for use with websites like youtube and soundcloud and so on. This would allow people to control their music from apps like rainmeter while keeping the apps in the background. This will make listening to music while doing other things much less intrusive and will be a major imporvement to nativefier.

```
nativefier --name "YouTube Music" "https://music.youtube.com/" --flash --tray --single-instance --enable-es3-apis --internal-urls ".*?"
```

**Suggested solution**

Adding a flag such as the following would likely be the best solution to implement this.

```
--enable-webnowplaying
```

**Alternative solutions**

The below option might also be a more flexible option if possible since it would allow for other things to be added in the future as well and might even be possible to open up a open source community plugins project for people to provide plugins for nativefier.

```
--plugin-options "{\"WebNowPlaying\": true}"
```

This method of course would probably best be suited for use with a plugins sub folder, however.

**Context**

 - Nativefier: 42.2.2
 - Node.js: v15.6.0
 - Npm: 7.4.0
 - OS: Windows 10 21H1 (OS Build  19043.867)

**Comment by TheCleric** [comment]
I'll defer to @ronjouch on this, but my opinion is I don't see this happening anytime soon. If you'd like to submit a PR to get this in, we'd be willing to consider it.

However, at this point we probably have more command line options that we'd like, so there would have to be a compelling reason to do add another one.

**Comment by ronjouch** [comment]
Yes to what @TheCleric wrote. I don't see this implemented in core Nativefier, there's little hope for supporting extensions (see https://github.com/nativefier/nativefier/issues/207), and I wouldn't want to bundle Nativefier-specific "basic versions of popular extensions": ad blocking is one of these, see https://github.com/nativefier/nativefier/issues/177 .

Also, @PhantomNimbi, you write

> This would allow people to control their music from apps like rainmeter while keeping the apps in the background

I know it's a far cry from the feature set you expect, but note that you can already play/pause music from backgrounded Nativefier apps, using your native media keys.

With that, closing.
