### ISSUE TITLE
Minor issue with workaround re: updating service workers (for Roam Research)

### ISSUE THREAD

**Issue by vergenzt** [nativefier/nativefier#1143]
Feel free to close this since it's not really a thorough bug report. I encountered an issue and was able to find a workaround so not willing to put too much effort into this. I wanted to report it for SEO though in case others and/or my future self encounter the same. :)

I'm using `nativefier` on [Roam Research](https://roamresearch.com). Recently Roam prompted in-app that there was an update available, but the button to update to the newest version didn't appear to work. It still didn't do anything after a hard refresh (Cmd+Shift+R in devtools).

What did eventually fix it was going to Devtools > Application tab > Service Workers, checking "☑ Update on reload", and refreshing. The app was then able to update. 🤷‍♂️ 

```
$ nativefier --version
42.3.0

$ cat ~/Applications/Roam\ Research-darwin-x64/version
11.3.0⏎

$ cat ~/Applications/Roam\ Research-darwin-x64/Roam\ Research.app/Contents/Resources/app/nativefier.json | jq .
{
  "alwaysOnTop": false,
  "backgroundColor": null,
  "basicAuthPassword": null,
  "basicAuthUsername": null,
  "bounce": false,
  "clearCache": false,
  "counter": false,
  "darwinDarkModeSupport": false,
  "disableGpu": false,
  "diskCacheSize": null,
  "enableEs3Apis": false,
  "fastQuit": false,
  "flashPluginDir": null,
  "fullScreen": false,
  "globalShortcuts": null,
  "height": 800,
  "ignoreCertificate": false,
  "ignoreGpuBlacklist": false,
  "insecure": false,
  "internalUrls": null,
  "blockExternalUrls": false,
  "maximize": false,
  "name": "Roam Research",
  "nativefierVersion": "42.3.0",
  "proxyRules": null,
  "showMenuBar": false,
  "singleInstance": false,
  "targetUrl": "https://roamresearch.com/#/app/<my-graph-url>",
  "titleBarStyle": null,
  "tray": false,
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",
  "width": 1280,
  "win32metadata": {
    "ProductName": "Roam Research",
    "InternalName": "Roam Research",
    "FileDescription": "Roam Research"
  },
  "disableOldBuildWarning": false,
  "zoom": 1,
  "buildDate": 1614783814496
}

**Comment by TheCleric** [comment]
@vergenzt did you get a chance to try what I suggested above?

**Comment by TheCleric** [comment]
Closing as I have not heard a response back. We can reopen if anyone is still experiencing this.

**Comment by TheCleric** [comment]
Also worth noting is we had to do something a little more in depth for Spotify service workers:https://github.com/nativefier/nativefier/issues/1185#issuecomment-839054611

**Comment by vergenzt** [comment]
Hey @TheCleric! I was able to get unblocked before I filed this via ⤵️, so I didn't need to try your workaround. 🙂

> https://github.com/nativefier/nativefier/issues/1143#issue-840982405:
>
> What did eventually fix it was going to Devtools > Application tab > Service Workers, checking "☑ Update on reload", and refreshing. The app was then able to update. 🤷‍♂️
