### ISSUE TITLE
Add Edit -> "Copy as Plain Text" action

### ISSUE THREAD

**Issue by p01t0t0** [nativefier/nativefier#1144]
- [yes]  I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md
- [yes] I searched existing issues, open & closed. Yes, my question is new.
- [yes] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

Can i change the copy option on the app to copy as plain text??

I am running a kiwix server on my local network and use nativefier to build the app to access the resources.
The app is working wonderfully but the only issue is when users copy any article from the app containing a link and paste on word, they get the link to access the resources directly which is not convenient.

Is there any way to change copy to copy as plain text? So links wont be copied!

Sorry if this is a dumb question.

**Comment by TheCleric** [comment]
This is possible if you forked and modified Nativefier's base code, but likely not something we'd support out of the box.

If you do wish to do so, you'd have to modify the `menu.ts` file in the `app/src/components` directory to have a function for the `Edit > Copy` menu item instead of a role, and in that function, you could get the highlighted text, strip the formatting, and then place it in the clipboard.

**Comment by p01t0t0** [comment]
> This is possible if you forked and modified Nativefier's base code, but likely not something we'd support out of the box.
> 
> If you do wish to do so, you'd have to modify the `menu.ts` file in the `app/src/components` directory to have a function for the `Edit > Copy` menu item instead of a role, and in that function, you could get the highlighted text, strip the formatting, and then place it in the clipboard.

**Comment by abhi12299** [comment]
> This is possible if you forked and modified Nativefier's base code, but likely not something we'd support out of the box.
> 
> If you do wish to do so, you'd have to modify the `menu.ts` file in the `app/src/components` directory to have a function for the `Edit > Copy` menu item instead of a role, and in that function, you could get the highlighted text, strip the formatting, and then place it in the clipboard.

Is this supposed to be added? I can work on this if need be.

**Comment by ronjouch** [comment]
> I can work on this if need be.

@abhi12299 sure! Patch welcome.
