### ISSUE TITLE
Blank page on redirect

### ISSUE THREAD

**Issue by sidelux** [nativefier/nativefier#1145]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md
- [x] I searched existing issues, open & closed. Yes, my question is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Your question**

Hi, i have a nativiefied website that every N seconds redirect to another page, in a loop (it's similar to a Digital Signage).
But if i lost connection during this redirect, i get a blank page and the application keep that condition until i restart it.

There is a way to detect connection lost / auto restart / avoid blank page?

Thanks a lot.

**Context**

 - Nativefier: 43.0.0
 - Node.js: 14.10.1
 - Npm: 6.14.9
 - OS: MacOS 11.2.3, generated for windows.

**Comment by TheCleric** [comment]
You could potentially inject a JS file that does this. I would suggest that for something like every (10*N*number of pages) seconds, it redirects the app to the starting page.

This way, every 10 rotations, it will force a "restart".

**Comment by sidelux** [comment]
I solved it by making the main page with a frame and reload the frame url from js, so it reloads indipendently from errors.
Is not the best way but it works.
