### ISSUE TITLE
Until signing the Nativefier app with CastLabs sign-pkg, Udemy videos fail to load even with flag --widevine, with error "Widevine license acquisition failed >> Verified media path has been tampered"

### ISSUE THREAD

**Issue by TheChanRProject** [nativefier/nativefier#1147]
### Problem 

Hello, I recently used nativefier to have a local Desktop app for watching Udemy courses. For some courses that I try to watch from the app, I am getting a **Video Error**. For other courses, I am able to watch the video playback without any problems. I was thinking it might be an issue from Udemy, but I went to Udemy on the browser to see if I can watch videos for the courses that have issues. It turns out the playback works perfectly on the browser. 

Any ideas on how this can be fixed? 

#### Nativefier Version 

![Screen Shot 2021-04-01 at 4 27 25 PM](https://user-images.githubusercontent.com/27648890/113363999-44027d00-9307-11eb-9b20-d842ce5ae5f7.png)

#### Web Browser Version

![Screen Shot 2021-04-01 at 4 27 55 PM](https://user-images.githubusercontent.com/27648890/113363987-3d740580-9307-11eb-90d6-85202b743dcf.png)

**Comment by deciacco** [comment]
Wanted to chime in as well... Same issue. Videos work fine in Firefox, etc. 
Nativefier 43.0.2 on Windows 10. Electron 12.0.4.

**Comment by dragonhelios** [comment]
had the same issue adding the --widevine tag to the build seems to have resolved it:

nativefier https://www.udemy.com/ --widevine

**Comment by ronjouch** [comment]
Thanks @dragonhelios

**Comment by deciacco** [comment]
I tried the --widevine flag and I'm still having issues with some video in my course... 
![image](https://user-images.githubusercontent.com/36453844/116129291-3a7ff100-a6ca-11eb-8991-9359f56a26e2.png)

**Comment by ronjouch** [comment]
So, with flag `--widevine`,

- @dragonhelios for you, Udemy videos fully work
- @deciacco for you, Udemy videos don't work, the video is black

It'd be great if the two of you could compare the details of your two use cases (exact URL, version of Nativefier, OS, etc), to isolate what remains breaking for @deciacco .

**Comment by deciacco** [comment]
yeah... so this is how I generate the app:
`nativefier https://www.udemy.com/ --name Udemy --internal-urls ".*?udemy.*?" --file-download-options "{\"saveAs\": true}" --disk-cache-size 0 --icon udemy.ico --widevine`

and I'm on the following and happy to provide other...

Windows - 10.0.19042 20H2 Build 19042
AMD Radeon(TM) Vega 3 Graphics
Nativefier 43.0.2

**Comment by tbouska** [comment]
I can't play videos too and I generate the app like this:
`nativefier --name "Udemy" --internal-urls ".*?" --icon udemy.icns  --widevine "https://www.udemy.com/" ~/Applications/webapps`

macOS 11.2.3
Intel UHD Graphics 630 1536 MB
Nativefier 43.0.2

**Comment by TheCleric** [comment]
This may be related to #1153 . The console generated essentially the same error there. Try this to see if this fixes it, from my comment on that ticket, but sub Udemy for HBO Max:

> The problem boils down to Widevine, which allows the app to access DRM content (such as HBO Max videos). Some sites (such as HBO Max) are sticklers for WHO can access this content. In the case of HBO Max it's not good enough to be using Widevine, you must have a digitally signed app using Widevine.
> 
> Fortunately the team at Castlabs were a great help and make this pretty easy.
> 
> They've documented the process here: https://github.com/castlabs/electron-releases/wiki/EVS
> 
> As well here's what I did to make this work:
> 
> 1. Make your app as you did before (in my case I only needed --widevine in addition to the standard parameters. --flash was not necessary.
> 2. Install the evs signing python package (in the steps from the document above)
> 3. Sign my generated app (in the steps from the document above). One thing that slipped me up briefly is when passing your app location to the signing tool, pass it the folder that contains the app. So for me I had generated my app on Mac to ~/Downloads which created a folder called ~/Downloads/HBO Max-darwin-x64. That folder is the one I had to pass to the signing tool.
> 4. After signing, launching, and signing in (fortunately I have an HBO Max login, lol), I was able to watch a show.
> 
> Sorry for the extra steps, but let me know if these work for you. If so, we'll document this a little better for future users.

**Comment by TheCleric** [comment]
In testing locally, the signing that I indicated above may not be needed, though I'm not sure. Worse comes to worse, it may be worth a try.

For me locally, I don't have an issue when running an app built like this with the current available version of Nativefier:

`nativefier --name "Udemy" --widevine "https://www.udemy.com/" ~/Downloads`

Similar to @tbouska I am on
macOS 10.15.7
Intel UHD Graphics 630 1536 MB
Nativefier 43.0.2

So only difference there is Catalina vs. Big Sur OS version (can't go Big Sur yet as I use apps that don't have support yet). Not sure if that makes a difference or not.

One thing I have noticed on MacOS when having issues like this, is even if you recreate the app, MacOS caches certain parts of the app outside of the app folder, so on subsequent runs it's not "clean". Hence why even if you recreate the app after logging in, it usually does not make you log in again.

So to start from scratch I would do the following command:

`rm -rf ~/Library/Application\ Support/udemy-nativefier-* ~/Library/Preferences/com.electron.udemy.plist`

After that, can you try the command I used to generate the app from above (with `~/Downloads` not being required of course) and see if you have better results?

**Comment by deciacco** [comment]
Happy to report that using `--widevine` and signing the generated app as @TheCleric mentioned worked!! Now the videos on Udemy that were not playing are working!! Woo hoo!!  Thank you, thank you!!!!

I did as Castlabs instructed. Luckily I already had Python installed on my Windows machine.

I installed the python module:
`pip install --upgrade castlabs-evs`

Signed up:
`python3 -m castlabs_evs.account signup`

Signed the generated app
```
python -m castlabs_evs.vmp sign-pkg Udemy-win32-x64
Signing: Udemy-win32-x64\Udemy.exe
 - Verifying existing VMP signature
 - Signature invalid: Failed to verify signature
 - Requesting VMP signature
```

**Comment by ronjouch** [comment]
Thanks folks! I closed this with a bit of doc in API.md, see https://github.com/nativefier/nativefier/commit/83b284e72768a867e175ab7161e6bc1706e8c5e2 .

Of course, doc is a first step, this can be improved/automated.
