### ISSUE TITLE
What does this mean and how do I go about Resolution

### ISSUE THREAD

**Issue by jackdashack** [nativefier/nativefier#1148]
I can't seem to paste the image or drag without this link showing.  Only this link. Well it did appear after posting. I get this message when starting Messages for Desktop saying the present Nativefier is old and potentially dangerous. How do I resolve this.

![messages app err](https://user-images.githubusercontent.com/45501353/113415972-4f4cbb80-938e-11eb-9b5d-ca31ef875ddf.png)

**Comment by ronjouch** [comment]
@jackdashack you should upgrade Nativefier and rebuild your nativefied app with the same flags. More discussion at https://github.com/nativefier/nativefier/issues/1131 . With that, closing.
