### ISSUE TITLE
Hide elements by ID or class name

### ISSUE THREAD

**Issue by sitemapxml** [nativefier/nativefier#1149]
Some time ago I bought some commercial nodejs script that convert website to desktop app, an it have simple json configuration file where you have two settings called "hideElementsId" and "hideElementsClass" which allow you to inject js code in all of the website pages loaded inside app, and hide certain elements like website header and footer.

The problem with that script is that I could not publish a project that is made by that script as opensource, because of proprietary license.

I was searching in your documentation and is seems that you don't have mention that. I have also take a look at issues and I found nothing similar.

So, my question would be:
- Is there a way to hide element by id or class name during nativefier build process?

or, if not:
- Do we have some simple way to establish this?

Thank you.

**Comment by ronjouch** [comment]
@sitemapxml yup, see https://github.com/nativefier/nativefier/blob/master/docs/api.md#inject and add the things you want to add with a little

```css
.foo #bar { display: none !important }
```

**Comment by sitemapxml** [comment]
Wow, I have never get such a fast reply!

Thank you 😄 
Cheers!
