### ISSUE TITLE
Title bar color on macOS Big Sur

### ISSUE THREAD

**Issue by ronilaukkarinen** [nativefier/nativefier#1150]
**Homework**

- [X] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md
- [X] I searched existing issues, open & closed. Yes, my question is new.
- [X] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Your question**

I'm trying to set up dark, same-color title bar on macOS Big Sur.

Command:

```
nativefier --name 'Todoist' 'https://todoist.com/app/today' --darwin-dark-mode-support --background-color '#22252e' --internal-urls '.*' --browserwindow-options '{ "webPreferences": { "spellcheck": false } }' --inject /Users/rolle/Projects/todoist-dracula-theme/style.css --icon /Users/rolle/Projects/todoist-dracula-theme/icon.icns
```

Screenshot:
![Screen-Shot-2021-04-08-17-21-33 55](https://user-images.githubusercontent.com/1534150/114043526-0a91ba80-988f-11eb-8f3e-2d154a4827d5.png)

How to get title bar to tinted dark? I have a dark mode set on system-level and proper parameters added to command but it still white.

**Context**

 - Nativefier: 43.0.0
 - Node.js: v10.24.1
 - Npm: 6.14.12
 - OS: macOS Big Sur, 11.2.3

**Comment by mindingulove** [comment]
add --title-bar-style "hiddenInset"  and --inject "/path/script.css"

script.css example: 
/* site.css */

/* header is draggable... */
header {
  -webkit-app-region: drag;
}

/* but any buttons inside the header shouldn't be draggable */
header button {
  -webkit-app-region: no-drag;
}

/* perhaps move some items out of way for the traffic light */
header div:first-child {
  margin-left: 100px;
  margin-top: 25px;
}

https://github.com/nativefier/nativefier/blob/master/docs/api.md#inject

**Comment by ronjouch** [comment]
Thanks @mindingulove
