### ISSUE TITLE
Instagram "Official dark theme" not working. https://www.instagram.com/?theme=dark

### ISSUE THREAD

**Issue by alexandrerochasalles** [nativefier/nativefier#1159]
**Homework**

- [ ] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md
- [ ] I searched existing issues, open & closed. Yes, my question is new.
- [ ] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Your question**

Recently (at least that I know), instagram have launched the dark theme version for website https://www.instagram.com/?theme=dark, which I'm using on web, and tried to convert using Nativefier, but I couldn't run with this 'targetUrl'.

zsh: no matches found: www.instagram.com/?theme=dark

Isn't it possible with this modifyed url to change appearance to dark?

**Steps to reproduce**

If you already have a Nativefier command you're struggling with, paste ***full*** nativefier command and its logs, with the ***`--verbose` flag***, on a ***public*** site:

```
nativefier --verbose --some-option https://mysite.com
<paste your verbose build logs, if relevant to your question>
```

**Debug info**

If applicable,

- Console logs of your attempted `nativefier` build command, with `--verbose` flag
- Error messages
- Screenshots
- Anything else relevant!

**Context**

 - Nativefier: (for example: 9.1.0)
 - Node.js: (for example: 14.6.0)
 - Npm: (for example: 6.14.7)
 - OS: (for example: Windows 10 build 1809)
 - Additional context: (for example: "I'm behind a proxy, with configuration X and protocol Y")

**Comment by ronjouch** [comment]
@alexandrerochasalles hi! Time to learn about your shell and [shell globbing](https://www.google.ca/search?q=shell%20globbing)!

```
nativefier 'www.instagram.com/?theme=dark'
```

, not

```
nativefier www.instagram.com/?theme=dark
```

! 🙂

**Comment by alexandrerochasalles** [comment]
> @alexandrerochasalles hi! Time to learn about your shell and [shell globbing](https://www.google.com/search?q=shell%20globbing)!
> 
> ```
> nativefier 'www.instagram.com/?theme=dark'
> ```
> 
> , not
> 
> ```
> nativefier www.instagram.com/?theme=dark
> ```
> 
> ! 🙂

So sorry about that, and thank you a lot.

As you could see, completely noob trying to do things here!! lol
By the way, to don't open another question, I'm trying to make a Spotify app, and tried even with the internal -urls (that worked fine) but still not able to work. 
In both cases, with or without the --Internal URL after login the app always says that the "browser is not supported", to use another browser or download the app.

I'm doing something wrong??

nativefier --name "Spotify" 'http://open.spotify.com' --internal-urls "(.*?)(accounts\.spotify\.com)(.*?)"

**Comment by ronjouch** [comment]
@alexandrerochasalles no worry. I pushed 9286fc80868e33034402a3b2eccce947747f40bb to not push users to shell globbing pitfalls.

`--internal-urls` isn't what you're looking for. To work around a webapp doing browser sniffing, you probably want to [tweak the user agent](https://github.com/nativefier/nativefier/blob/master/docs/api.md#user-agent) (and maybe you need more hacks, do a bit of searching around!). If you don't find a solution, please open a new issue with a new name that's clearly about your Spotify `"browser is not supported"` error.
