### ISSUE TITLE
Compare to webcatalog, another WebApp → Desktop App MetaA pp

### ISSUE THREAD

**Issue by linonetwo** [nativefier/nativefier#1165]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md
- [x] I searched existing issues, open & closed. Yes, my question is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Your question**

I'm using [WebCatalog](https://webcatalog.app/)  currently, and use its code to build https://github.com/tiddly-gittly/TiddlyGit-Desktop , and I see nativefier today, so being curious.

Can you briefly describe the difference between two, so users can compare?

**Comment by TheCleric** [comment]
Looking over your app (and WebCatalog), from a high level, here's the distinctions I'd make:

For WebCatalog in general:
&nbsp; | WebCatalog | Nativefier
-|-|-
License | Paid (with a limited free tier and an open source backend) | Completely free and open source
Base Technology | Electron | Electron
Interface | OS Native UI | Command line
Catalog | Catalog of pre-built apps | No current catalog (but we're working on it #1130 #1166)

For your use case in specific, from a quick glance, I think Nativefier and WebCatalog would be fairly equivalent as you're building on WebCatalog (with an added internal web server from what I see) to display a web page from the local server. Even going to raw Electron would likely do what you want (in which you'd get a little more control, but a little more difficulty).

If there is a particular need that you are looking for, we can certainly let you know if we support that (or plan on supporting that). The good news is that porting from one to the other would be fairly simple as the root of Electron is the same.

One caveat to that though is that Nativefier is really meant as a command line tool for generating apps, not as a framework for building apps on your own. So while you are free to do so (in the spirit of open source), it's not necessarily a designed for or supported use case.

Hope this helps.

**Comment by linonetwo** [comment]
Thank you Adam, that is clear. I will recommend Nativefier along with WebCatalog if I'm going to introduce them on social media.

**Comment by mattruzzi** [comment]
I am working on my own GUI for nativefier although it currently lacks most of the options found in the nativefier cli. 
https://github.com/mattruzzi/nativefier-gui
