### ISSUE TITLE
[Road to nativefier-catalog] First have a "Build Commands Library" md file compiling "known minimal good configurations" per site

### ISSUE THREAD

**Issue by deciacco** [nativefier/nativefier#1166]
I was wondering if we could enable the Wiki in Github or maybe just use a "Feature Request type Issue" here where we can post the commands we use as a reference for everyone. For example below is what I do for Outlook Web and for Udemy:

#### Command String
```
nativefier https://outlook.office.com/mail 
--name OutlookWA 
--internal-urls ".*?(outlook.live.com|outlook.office365.com|outlook.office.com|login.microsoftonline.com).*?" 
--file-download-options "{\"saveAs\": true}" 
--disable-dev-tools 
--disk-cache-size 0 
--browserwindow-options "{ \"webPreferences\": { \"webviewTag\": true, \"nodeIntegration\": true, \"nodeIntegrationInSubFrames\": true, \"nativeWindowOpen\": true } }"
```
#### Notes:
In order to have the "pop out" window functionality when creating an email, the `--browserwindow-options` is needed.

#### Command String
```
nativefier https://www.udemy.com/ 
--name Udemy 
--internal-urls ".*?udemy.*?" 
--file-download-options "{\"saveAs\": true}" 
--disable-dev-tools 
--disk-cache-size 0 
--icon udemy.ico 
--widevine
```
#### Notes:
Most videos will work, but to be sure everything works you are better off using the `--widevine` version and sign the app afterwards. See this post: https://github.com/nativefier/nativefier/issues/1147#issuecomment-828750362

**Comment by ronjouch** [comment]
@deciacco good suggestion! Thoughts:

1. See https://github.com/nativefier/nativefier/issues/1130 ...
2. ... but until this happens, if it does, I hadn't thought of first compiling / documenting a simple list of commands. I like it 🙂.
3. Rather than the GitHub wiki, let's use a proper in-tree file (`EXAMPLES.md` ? `CATALOG.md` ? `EXAMPLES-CATALOG.md` ? `EXAMPLES-LIBRARY.md` ?). They're functionally the same (it's all markdown, rendered the same), except a file is A. more visible, B. accessible by anyone with a clone of the repo.
4. Library commands should be the strict necessary to make an app work. so, for example,
    1. Yes to have `--widevine` in Udemy. Yes to `--internal-urls` and `--browserwindow-options` for Outlook Web. Yes to a `name` and `icon` for both...
    2. ... but let's not have all the other flags that are a matter of personal preference (e.g. `--disable-dev-tools` or `--disk-cache-size`) . By the way, what makes you use `--disk-cache-size 0` ?

@deciacco PR welcome for this (the file, and a mention of the file at the end of the [Usage section of README.md](https://github.com/nativefier/nativefier#usage)

**Comment by deciacco** [comment]
Yeah.. in short I agree with everything you mentioned and thank you for taking the time to respond... I've been meaning to ask for this for some time, but just never got around to it. It took me a long time to figure out the Outlook issue and the Udemy thing I'm sure could get a lot of folks...

I disable the disk cache to hopefully save writes to my ssd... maybe I shouldn't?

I'm not sure if I need to do anything at this point...??

**Comment by ronjouch** [comment]
@deciacco 

> It took me a long time to figure out the Outlook issue and the Udemy thing I'm sure could get a lot of folks...

Agreed a thousand times. You don't see it if you're not subscribed to the repo issues, but we have a LOT of duplicate _"site XYZ doesn't work, how do I make it work?"_ questions. A visible library/catalog of examples will help a lot alleviate this.

> I disable the disk cache to hopefully save writes to my ssd... maybe I shouldn't?

I dunno how consequential/negligible the impact is for a SSD, but yeah makes sense. I personally disable all caching and system logging for a dashboard at work running on a Raspberry, which use an SD card as storage, and have an extremely low write lifespan.

> I'm not sure if I need to do anything at this point...??

If you have the time for this, you can create the file and add a PR for it. PR should have the file, and a mention of the file at the end of the [Usage section of README.md](https://github.com/nativefier/nativefier#usage).

**Comment by mattruzzi** [comment]
I was thinking for every site that is in nativefier-catalog we also could put it in a markdown file so that the json schema for nativefier-catalog can remain clean and not have the explanations for the flags in it but we can still have explanations for all of the flags in the markdown file.
