### ISSUE TITLE
Help enabling another spellcheck language in addition to US EN.

### ISSUE THREAD

**Issue by deciacco** [nativefier/nativefier#1182]
I was reading the API and saw the past post on enabling spellchecking, etc. Honestly, I'm not exactly sure how to do this, but I'd like to add Italian spellchecking to my app. I use Fastmail in Nativefier and US EN works well, but I'd like to be able to add Italian as I write emails in this language as well. I'm guessing I need to inject the code as the API shows, but that seems to switch the spellchecker preferred language whereas I'd like to add to it. 

I'm using the latest version of Nativefier and am on Windows.

Thanks.

**Comment by TheCleric** [comment]
The example JS could be modified simply to add a new spellcheck language. When the function `setSpellCheckerLanguages` gets called it takes an array of languages. In the example it's just `[['fr']]` but in your case you'd want it to send something like `[['en', 'it']]`.

Only caveat to this is that this will not work for Mac, as on Mac `setSpellCheckerLanguages` doesn't work (Mac's spellchecker just uses the OS enabled locales).

Let us know if that works for you.
