### ISSUE TITLE
Spotify web not supported

### ISSUE THREAD

**Issue by Knallli** [nativefier/nativefier#1185]
**Homework**

- [ x ] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md
- [ x ] I searched existing issues, open & closed. Yes, my question is new.
- [ x ] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Your question**

I'm unable to get into the Spotify Web player on open.spotify.com, telling me my browser is not supported, I used another user agent already and I tried it with the --widevine flag, but without success. 

**Steps to reproduce**
nativefier "https://play.spotify.com" --internal-urls ".*" --name "Spotify native" --widevine -u "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"

**Context**

 - Nativefier: (latest)
 - Node.js: (v16.1.0)
 - Npm: (brew)
 - OS: (MacOS 11.3.1)

**Comment by TheCleric** [comment]
So there are a few competing issues at play here:

1. Spotify seems to use a serviceWorker to limit electron apps (like WhatsApp in #1122)
2. Spotify seems to need a signed version of WideVine (like 

So to solve each, you'll need to do a few things when building the app.

To fix issue 1, we need to inject a script to nuke serviceWorker data. So save this snippet as a js file and `--inject` it:
```javascript
if ('serviceWorker' in navigator) {
    caches.keys().then(function (cacheNames) {
        cacheNames.forEach(function (cacheName) {
            caches.delete(cacheName);
        });
    });
}
```

To fix issue 2, you'll need to have Castlabs sign your app, instructions can be found here: https://github.com/castlabs/electron-releases/wiki/EVS

After doing these two things locally I was able to get the app working using your command as a base.

**Comment by Knallli** [comment]
Hmm even after clearing the caches it doesn't seem to work with the script you sent me

I can access the page when I unregister the ServiceWorker with an injected script`navigator.serviceWorker.getRegistrations().then( function(registrations) { for(let registration of registrations) { registration.unregister(); } }); ` 

I just have to reload the page on every restart and it's always installing another iteration of the serviceworker afterwards, but still does the job

**Comment by TheCleric** [comment]
Can you try a slightly different name such as `Spotify Test` with everything else, and see how that behaves?
