### ISSUE TITLE
Personalization

### ISSUE THREAD

**Issue by yap241986** [nativefier/nativefier#1186]
I can customize the bar
<img width="743" alt="Schermata 2021-05-11 alle 23 00 23" src="https://user-images.githubusercontent.com/65458792/117884573-149f4280-b2ad-11eb-9bb4-89ca25a4cf43.png">

**Comment by yap241986** [comment]
?

**Comment by ronjouch** [comment]
@yap241986 hi, please precise your question.

**Comment by ronjouch** [comment]
@yap241986 closing this for now. Will re-open if you precise what you meant; our [feature request](https://github.com/nativefier/nativefier/blob/master/.github/ISSUE_TEMPLATE/feature_request.md) or [bug report](https://github.com/nativefier/nativefier/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) templates are here to help.

**Comment by yap241986** [comment]
For example can I modify the voice Save AS In the File Menu?

**Comment by ronjouch** [comment]
> For example can I modify the voice Save AS In the File Menu?

@yap241986 hi. Sorry I still don't understand, what do you mean by "voice Save AS"? You want to modify the *label" "Save As"? If yes, what for?

**Comment by TheCleric** [comment]
@ronjouch I could be VERY wrong, but I think you are correct in that they are asking to modify the label. I also wonder if what they're really getting at would be do we support localization of things like menu items to something other than English.
