### ISSUE TITLE
JavaScript error when popups / link clicks fail

### ISSUE THREAD

**Issue by zachriggle** [nativefier/nativefier#1193]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md
- [x] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

When a Nativefier'ed app (generally GMail) attempts to open certain links with a pop-up window, an exception is thrown (and continues to be re-thrown instantly) occurs until the application is Force-Quit (on macOS).

The specific case here is clicking a link that should navigate to Reddit, from a Reddit reply to a post.  GMail pops up an error message about a pop-up blocker being used.  I can forward this email to the Nativefier team if this is useful, for reproduction purposes.

<img width="266" alt="Screen Shot 2021-05-15 at 4 50 12 PM" src="https://user-images.githubusercontent.com/111640/118379074-a9e85280-b59d-11eb-9733-73f7997e1513.png">

Once that message is closed, a repeating error is thrown. The contents of the exception is here:

```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Object has been destroyed
at Function.<anonymous> (/Applications/GMail.app/Contents/Resources/app/lib/webpack:/nativefier-placeholder/src/components/mainWindow.ts:77:23)
```

<img width="260" alt="Screen Shot 2021-05-15 at 4 32 30 PM" src="https://user-images.githubusercontent.com/111640/118378920-87096e80-b59c-11eb-93fd-49265f573ed2.png">

**Steps to reproduce**

Give your ***full*** nativefier command and its logs, with the ***`--verbose` flag***, on a ***public*** site:

<details><summary>Nativefier Command</summary>

```
nativefier --single-instance --no-overwrite --bounce --verbose --darwin-dark-mode-support --user-agent 'Mozilla/5.0 (Windows NT 10.0; rv:74.0) Gecko/20100101 Firefox/74.0' --internal-urls '(.*?(contacts|calendar|accounts)\.google\.com.*?|.*?facebook\.com.*?)' --name GMail --icon icon.png https://mail.google.com/mail/u/0/
```
</details>

<details><summary>Nativefier Logs</summary>

```
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.

Performing async options post-processing.
Got icon from options. Using it, no inferring needed
Got name GMail from options. No inferring needed
Sanitized filename for GMail : GMail
options {
  packager: {
    appCopyright: undefined,
    appVersion: undefined,
    arch: 'x64',
    asar: false,
    buildVersion: undefined,
    darwinDarkModeSupport: true,
    dir: '/opt/brew/Cellar/nativefier/43.1.3/libexec/lib/node_modules/nativefier/app',
    electronVersion: '12.0.6',
    icon: 'icon.png',
    name: 'GMail',
    out: '/private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.o6Mt5MSG',
    overwrite: false,
    platform: 'darwin',
    portable: false,
    targetUrl: 'https://mail.google.com/mail/u/0/',
    tmpdir: false,
    upgrade: false,
    upgradeFrom: undefined,
    win32metadata: {
      ProductName: 'GMail',
      InternalName: 'GMail',
      FileDescription: 'GMail'
    }
  },
  nativefier: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    backgroundColor: null,
    basicAuthPassword: null,
    basicAuthUsername: null,
    blockExternalUrls: false,
    bookmarksMenu: null,
    bounce: true,
    browserwindowOptions: undefined,
    clearCache: false,
    counter: false,
    crashReporter: undefined,
    disableContextMenu: undefined,
    disableDevTools: undefined,
    disableGpu: false,
    diskCacheSize: null,
    disableOldBuildWarning: false,
    enableEs3Apis: false,
    fastQuit: false,
    fileDownloadOptions: undefined,
    flashPluginDir: null,
    fullScreen: false,
    globalShortcuts: null,
    hideWindowFrame: undefined,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    inject: [],
    insecure: false,
    internalUrls: '(.*?(contacts|calendar|accounts)\\.google\\.com.*?|.*?facebook\\.com.*?)',
    lang: undefined,
    maximize: false,
    nativefierVersion: '43.1.3',
    processEnvs: undefined,
    proxyRules: null,
    showMenuBar: false,
    singleInstance: true,
    titleBarStyle: null,
    tray: false,
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; rv:74.0) Gecko/20100101 Firefox/74.0',
    userAgentOverriden: true,
    verbose: true,
    versionString: undefined,
    width: 1280,
    height: 800,
    minWidth: undefined,
    minHeight: undefined,
    maxWidth: undefined,
    maxHeight: undefined,
    widevine: false,
    x: undefined,
    y: undefined,
    zoom: 1
  }
}

Preparing Electron app...
Copying electron app from /opt/brew/Cellar/nativefier/43.1.3/libexec/lib/node_modules/nativefier/app to /var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/nativefier-16-45-9-app--65354-nrFt1UTjEZwZ
Writing app config to /var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/nativefier-16-45-9-app--65354-nrFt1UTjEZwZ/nativefier.json
No files to inject, skipping copy.
Updating /var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/nativefier-16-45-9-app--65354-nrFt1UTjEZwZ/package.json 'name' field to gmail-nativefier-13fa29

Converting icons...
Converting icon icon.png to /var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/nativefier-16-45-9-iconconv--65354-L4XXRDR5VlR2/icon.icns. Calling shell command: "/opt/brew/Cellar/nativefier/43.1.3/libexec/lib/node_modules/nativefier/icon-scripts/convertToIcns" "icon.png" "/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/nativefier-16-45-9-iconconv--65354-L4XXRDR5VlR2/icon.icns"
Copying icons if necessary
No icon specified in options; aborting

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...

Finalizing build...
App built to /private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.o6Mt5MSG/GMail-darwin-x64, move to wherever it makes sense for you and run the app bundle.
```
</details>

**Expected behavior**

Not sure what should happen when a pop-up is attempted, but a repeated exception is not it.

**Actual behavior**

An error message / exception is shown repeatedly.

**Context**

```
$ sw_vers
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F5055c

$ nativefier --version
43.1.3

$ node --version
v16.1.0
```

**Comment by TheCleric** [comment]
We'll take a look. In the meantime, did this recently break for you, or did you just discover it?

**Comment by zachriggle** [comment]
I don't recall encountering this until a few weeks ago.

**Comment by TheCleric** [comment]
> I don't recall encountering this until a few weeks ago.

Thanks! Hopefully that will help us narrow down the culprit. 😃

**Comment by TheCleric** [comment]
Okay, I think I've got this "figured out". Issue seems to be with GMail/Google itself.

For certain useragents (such as the one we're using in Nativefier unfortunately, GMail tries to handle these links in a funky way (trying to do funky stuff with asking the "browser" to open a new about:blank window, and then injecting the link you actually clicked on after the fact, but in our case it decides it didn't like how we handled it, so the inject doesn't occur).

Current "fix" for this is to use a different user agent. Firefox useragents (including this he one you used and up to the latest) seem to have the issue, but latest Edge and latest Chrome both made this behave as expected for me.

Sorry for the headache. Google is notoriously antagonistic to their apps being used inside of Electron.

Let me know if this works for you.

**Comment by PhantomNimbi** [comment]
I'm having the JavaScript error as well. I'm on Windows 10. Latest version of nativefier. It has only been happening since the latest update. It happens whenever I close an app I made with nativefier.

**Comment by zachriggle** [comment]
@TheCleric can you provide a *specific* User Agent that I should use, which still makes Gmail / Google Drive work, but doesn't exhibit this error?

**Comment by TheCleric** [comment]
> @TheCleric can you provide a _specific_ User Agent that I should use, which still makes Gmail / Google Drive work, but doesn't exhibit this error?

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 Edg/90.0.818.56`

**Comment by TheCleric** [comment]
> I'm having the JavaScript error as well. I'm on Windows 10 Pro build 21H1 with the latest version of nativefier. It has only been happening since the latest update. It happens whenever I close an app I made with nativefier.
> 
> For me it specifically happens when I close out a a window of which was opened in a new window.
> I've tried the user agent thing but it doesn't seem to fix it for me. It seems to be a general issue with anything opened in a new window for me.

So to confirm, your Nativefier version is 43.1.3? Because we recently fixed a very similar bug to this (#939).

**Comment by TheCleric** [comment]
@ronjouch I also found this Electron bug related to this ticket:

https://github.com/electron/electron/issues/28927

Looks like it was fixed in 12.0.7, so at least that part of this issue (can't quit the window with a dialog open).

**Comment by TheCleric** [comment]
Haven't heard back on this issue with the suggested workaround. If this is still an issue, please let us know.

Closing for now.

**Comment by zachriggle** [comment]
The UA workaround did solve this issue.  Thanks for your time!
