### ISSUE TITLE
Spotify Browser not supported 

### ISSUE THREAD

**Issue by Thelevithan** [nativefier/nativefier#1195]
I made Spotify app and when I am opening it it says browser not supported I also did same with discord but it works perfectly fine idk what's the problem with Spotify

**Comment by ronjouch** [comment]
@Thelevithan hi. Spotify needs a bit of help to work. See https://github.com/nativefier/nativefier/blob/master/CATALOG.md#spotify

**Comment by Thelevithan** [comment]
It isn't working I did all the steps mentioned in above link but the app is only showing white background nothing else

<img width="1440" alt="Screenshot 2021-05-19 at 4 00 05 PM" src="https://user-images.githubusercontent.com/66463310/118798493-55094c80-b8bb-11eb-8b38-2027cdb3d0c8.png">

<img width="571" alt="Screenshot 2021-05-19 at 3 58 30 PM" src="https://user-images.githubusercontent.com/66463310/118798368-3014d980-b8bb-11eb-9de2-a840a5188534.png">

**Comment by ronjouch** [comment]
@Thelevithan this recipe was just added to CATALOG.md , so I'd tend to think it is working but you missed something. Double-check what you did and dee https://github.com/nativefier/nativefier/issues/1185 .

**Comment by TheCleric** [comment]
@Thelevithan did you sign the app with castlabs as instructed?

**Comment by Thelevithan** [comment]
Yeah I got it done by following the steps thanks btw

**Comment by alexandrerochasalles** [comment]
@Thelevithan 

What have you done to make it work?

**Comment by TheCleric** [comment]
> @Thelevithan 
> 
> 
> 
> What have you done to make it work?

He followed the steps laid out here https://github.com/nativefier/nativefier/blob/master/CATALOG.md#spotify

**Comment by eleanorlouisesmith** [comment]
This also doesn't work for me, just shows a white screen. I've followed the steps listed above and signed the app successfully.

**Comment by akash329d** [comment]
This appears to be an issue specific to M1 devices, as I'm having the same problem with my M1 Mac. I jumped in dev tools and when I run "navigator.serviceWorker.getRegistrations()", it returns an empty array for some reason. I'm having trouble debugging further as I'm not experienced at all here.

**Comment by akash329d** [comment]
Did some further investigating and got it working. It seems to be the "--user-agent" flag. When I ran it using firefox or edge as the argument, it didn't replace it, and it was sending requests with the user agent as "firefox" or "edge" verbatim. When I removed that argument it began working again (again this is on an M1 macbook).

**Comment by eleanorlouisesmith** [comment]
Thanks for finding that Akash, removing the user-agent flag has got Spotify working for me now in nativefier.

**Comment by TheCleric** [comment]
> Did some further investigating and got it working. It seems to be the "--user-agent" flag. When I ran it using firefox or edge as the argument, it didn't replace it, and it was sending requests with the user agent as "firefox" or "edge" verbatim. When I removed that argument it began working again (again this is on an M1 macbook).
> 
> #1211 - Created a new issue for this.

Sorry for the headache @akash329d . That's the latest code, but hasn't made it out to the npm package yet. Hopefully @ronjouch will cut a new release soon!

**Comment by ronjouch** [comment]
Truuuuuuuuuuue. Will remind to release fast when we merge stuff that updates the docs! Cutting a release later today, sorry for the hiccup everybody!

**Comment by ronjouch** [comment]
Say hi to useragent shortcodes in freshly-released 44.0.0, released now on npm!

One thing, though: @akash329d @eleanorlouisesmith you say

> removing the user-agent flag has got Spotify working for me now in nativefier.

... did you replace it with a manual complete user-agent you copy-pasted, or did you fully remove it? If you fully removed it and Spotify still works, it means it's unnecessary for Spotify and we'll remove it from CATALOG.md

**Comment by akash329d** [comment]
> Say hi to useragent shortcodes in freshly-released 44.0.0, released now on npm!
> 
> One thing, though: @akash329d @eleanorlouisesmith you say
> 
> > removing the user-agent flag has got Spotify working for me now in nativefier.
> 
> ... did you replace it with a manual complete user-agent you copy-pasted, or did you fully remove it? If you fully removed it and Spotify still works, it means it's unnecessary for Spotify and we'll remove it from CATALOG.md

I totally removed it and it’s still working, so looks like it’s unnecessary. Thanks for such a quick turnaround on the release!

**Comment by eleanorlouisesmith** [comment]
@ronjouch Fully removed as well and now working perfectly! Thanks for the fix + release :)

**Comment by ronjouch** [comment]
👍, thx folks. Updated CATALOG.md in 16cacb0
