### ISSUE TITLE
Is there a way to have a Menu item that resets the app to the main screen?

### ISSUE THREAD

**Issue by maneeshsethi** [nativefier/nativefier#1196]
**Homework**

- [x ] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md
- [ x] I searched existing issues, open & closed. Yes, my question is new.
- [ x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Your question**

When I navigate with title-bar-style=hiddenInset, and navigate to a link from the Bookmarks menu, the whole screen is hidden with no way to get back to the main menu. (Cmd-Left takes you back, but you can't reset via the menu, or keyboard shortcut).

Is there a way to have a Menu item that resets the app to the main screen? Ideally, Cmd-1 would take you back to the main screen, and Cmd-Shift-R would reset the app to base state.

**Steps to reproduce**

Run 

`nativefier --title-bar-style 'hiddenInset' --bookmarks-menu 'bookmarks.json'  https://example.com  
`

with a bookmarks.json file 

```
{
    "menuLabel": "Links",
    "bookmarks": [
    	{
            "title": "Pavlok",
            "url": "https://pavlok.com/",
            "type": "link",
            "shortcut": "CmdOrCtrl+2"
        },
}
```

As you can see, no way to go back.

![Pasted_Image_5_20_21__4_27_AM](https://user-images.githubusercontent.com/620799/118955164-1065cb80-b924-11eb-957f-b369a7ff395a.png)

**Debug info**

**Context**

 - Nativefier: (for example: 43.1.2)
 - Node.js: (for example: 16.1.0)
 - Npm: (for example: 7.11.2)
 - OS: (for example: Mac M1 Arch64)

**Comment by TheCleric** [comment]
We could potentially add a "Home" bookmark by default when using a bookmarks menu. In the interim, the easiest solution would be adding a Home entry yourself that corresponds to whatever keyboard shortcut and location you'd like.

**Comment by TheCleric** [comment]
Closing as answer to the question was provided. If anything further is desired, please consider opening a feature request.
