### ISSUE TITLE
Toggle full screen not working

### ISSUE THREAD

**Issue by rkansal47** [nativefier/nativefier#1199]
Hi, this is a great tool, thank you! I'd like to report a bug when using this for overleaf.com on Big Sur 11.2.3: the 'toggle full screen' does not appear to do anything.

**Comment by TheCleric** [comment]
I'm not on Big Sur yet (incompatible software 😦 ), but this seems to work fine in Catalina.

You are referring to this button right?

![Screen Shot 2021-05-24 at 10 30 48 AM](https://user-images.githubusercontent.com/547567/119363070-6667a580-bc7b-11eb-9929-fc9c5c3cfd8a.png)

If so can you open Dev Tools (View > Toggle Developer Tools) and provide any output that shows up in the Console view when clicking the button?

**Comment by rkansal47** [comment]
I was referring to the native option to make the app full screen instead of in a window on the desktop - however, after restarting my laptop that option is working fine now. Sorry I really should have tried the 'turning it off and back on again' method before posting this.

**Comment by TheCleric** [comment]
> I was referring to the native option to make the app full screen instead of in a window on the desktop - however, after restarting my laptop that option is working fine now. Sorry I really should have tried the 'turning it off and back on again' method before posting this.

Glad it worked itself out!
