### ISSUE TITLE
Open new Tab keeps doubling tabs

### ISSUE THREAD

**Issue by bambootb** [nativefier/nativefier#1214]
Yes, my bug is new.
 I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

Run app with Nativefier on Mac and CMD + Click on a link to open new tab then the tabs keep open double, every time.

Please check the screen record for better understanding.
https://monosnap.com/file/drGzOfh9kxYtuhiswnotiQBq2YfvCA

**Context**

 - Nativefier v44.0.0
 - OS: (Mac)

**Comment by ronjouch** [comment]
Closing as dup of https://github.com/nativefier/nativefier/issues/1209
