### ISSUE TITLE
icons are a little bigger than native app's

### ISSUE THREAD

**Issue by maondun** [nativefier/nativefier#1215]
**Homework**

- [ ] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [ ] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [ ] I searched existing issues, open & closed. Yes, my bug is new.
- [ ] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

When I create a web app, the icon of web app is bigger than native app's. Both on dock and startup.

**Steps to reproduce**

Give your ***full*** nativefier command and its logs, with the ***`--verbose` flag***, on a ***public*** site:

```
nativefier --verbose --some-option https://mysite.com
<paste your verbose build logs too>
```

**Expected behavior**

The icons are same size of native app's, so that it looks pretty well.

**Actual behavior**

icons are a little bigger than native app's

**Debug info**

- Console logs of your `nativefier` build command, with `--verbose` flag
- If the bug happens at app run time, the in-app DevTools console logs (open it with F12)
- Error messages
- Screenshots
- Anything else relevant!

**Context**

 - Nativefier: 44.0.0
 - Node.js:  v16.2.0
 - Npm:  7.13.0
 - OS: macOS 11.4
 
<img width="462" alt="image" src="https://user-images.githubusercontent.com/77653842/120894028-dd704700-c648-11eb-95bd-197cdbbbb1c6.png">

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/77653842/120894046-fd076f80-c648-11eb-8925-6a1ee0ea4d20.png">

**Comment by ronjouch** [comment]
Closing as dup of https://github.com/nativefier/nativefier/issues/329 . Feel free to follow the discussion and bring extra info not already there.
