### ISSUE TITLE
font size

### ISSUE THREAD

**Issue by Meditationer** [nativefier/nativefier#1217]
Webpage：
![image](https://user-images.githubusercontent.com/50068247/120948157-22dd6300-c774-11eb-891c-20bc0e01fd7e.png)
After app
![image](https://user-images.githubusercontent.com/50068247/120948074-f3c6f180-c773-11eb-95c7-82ad490c642b.png)
How to change the font size, the original page font size is 5

**Comment by ronjouch** [comment]
Did you try https://github.com/nativefier/nativefier/blob/master/API.md#zoom ?


Also, please provide the info requested by our [bug report issue template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Quoting its first three lines:

```
Help us help you, please take the time to fill this information 🙂.
An incomprehensible bug report is a useless bug report.
Incomprehensible / incomplete bug reports will be closed.
```

With that, closing, but will re-open if `--zoom` doesn't work for you and if you find the time to bring details.

**Comment by Meditationer** [comment]
nativefier --name "material" "https://www.zhihu.com/" --zoom <2&gt;
命令语法不正确。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nativefier/nativefier"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月7日(星期一) 上午9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nativefier/nativefier] font size (#1217)





 
Did you try https://github.com/nativefier/nativefier/blob/master/API.md#zoom ?
 
Also, please provide the info requested by our bug report issue template. Quoting its first three lines:
 Help us help you, please take the time to fill this information 🙂. An incomprehensible bug report is a useless bug report. Incomprehensible / incomplete bug reports will be closed.  
With that, closing, but will re-open if --zoom doesn't work for you and if you find the time to bring details.

**Comment by Meditationer** [comment]
What is the correct syntax use of room <value>.
this nativefier --name "material" "https://www.zhihu.com/" --zoom <2> is error;

**Comment by Meditationer** [comment]
Homework

&nbsp;I looked at&nbsp;nativefier --help&nbsp;and&nbsp;https://github.com/nativefier/nativefier/blob/master/API.md

&nbsp;I checked the&nbsp;Troubleshooting section of the README.

&nbsp;I searched existing issues, open &amp; closed. Yes, my bug is new.

&nbsp;I'm using the latest version available at&nbsp;https://github.com/nativefier/nativefier/releases

Bug description

How to change the&nbsp;Desktop applications&nbsp;font size, the original page font size is 5.Compared with the original page, the font size after packaging is significantly smaller

Web page display effect：

![image](https://user-images.githubusercontent.com/50068247/120954702-52936780-c782-11eb-861f-e8b3d836a033.png)。

Desktop application display effect：

![image](https://user-images.githubusercontent.com/50068247/120954795-8cfd0480-c782-11eb-9602-93d01b57f9b6.png)

Steps to reproduce

first&nbsp;Run command：

nativefier --name "material" "https://www.zhihu.com/"

After revision



nativefier --name "spp" "https://www.zhihu.com/" --zoom '3'
command&nbsp;invalid，The style has not changed。

Expected behavior

Modify and enlarge the packaged page font

Actual behavior

The font does not match the original page size





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nativefier/nativefier"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月7日(星期一) 上午9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nativefier/nativefier] font size (#1217)





 
Did you try https://github.com/nativefier/nativefier/blob/master/API.md#zoom ?
 
Also, please provide the info requested by our bug report issue template. Quoting its first three lines:
 Help us help you, please take the time to fill this information 🙂. An incomprehensible bug report is a useless bug report. Incomprehensible / incomplete bug reports will be closed.  
With that, closing, but will re-open if --zoom doesn't work for you and if you find the time to bring details.

**Comment by ronjouch** [comment]
> Also, What is the correct syntax use of room . this nativefier --name "material" "https://www.zhihu.com/" --zoom <2> is error;

@Meditationer I see. In the documentation, `<value>` is meant to be "insert value here". So, you should try `nativefier --zoom 2 "https://www.zhihu.com/"` , not `nativefier --zoom <2> "https://www.zhihu.com/"`

Results:

**`nativefier "https://www.zhihu.com/"`**

![screenshot_default_2021-06-07-09:18:03](https://user-images.githubusercontent.com/522085/121023670-81551200-c771-11eb-95b6-d8bb254ed538.png)


**`nativefier --zoom 2 "https://www.zhihu.com/"`**

![screenshot_zoom2_2021-06-07-09:18:32](https://user-images.githubusercontent.com/522085/121023687-84500280-c771-11eb-88ce-1ea7181980f6.png)
