### ISSUE TITLE
--tray start-in-tray, --width, --height not working in Windows

### ISSUE THREAD

**Issue by kariyna** [nativefier/nativefier#1225]
i'm a nativefier noob so i'm not sure if that is the intended effect... i can't get start-in-tray to work at all, nor the width or height. the "start-in-tray" modifier especially messes with the entire operation and ends up making a subfolder for the app called start-in-tray.

**Comment by mattruzzi** [comment]
You might be that you are using 
`nativefier https://example.com/  start-in-tray` instead of 
`nativefier https://example.com/ --tray` <<< the correct command
 
`--tray` enables the tray option
putting `start-in-tray` after the website url will create a folder named start-in-tray

**Comment by kariyna** [comment]
> 
> 
> Can you provide the exact command you are using?

nativefier "https://192.168.137.204:8741/" --n X --i X --width X --height X --tray start-in-tray

if i try just --tray, it doesn't even have the option to go in tray at all, but if i write start-in-tray it goes to tray when clicking the close button but it doesn't start in tray at all

**Comment by TheCleric** [comment]
@kariyna what OS are you using? Windows? Which version?

**Comment by TheCleric** [comment]
I have confirmed @kariyna initial bug on my Mac. I will have a fix son.

**Comment by kariyna** [comment]
@TheCleric sorry for the late reply. i'm using windows 10. i thought it might have something to do with the particular URL i was trying to access but since then i've tried creating multiple apps with different URLs but its always the same result, it never starts in tray.

**Comment by TheCleric** [comment]
I will have a fix for the tray issue shortly, but the width and height may be a little more complicated.

Width and height DO work, but have a big caveat to them that may be unexpected. Each app maintains a cache of the window state (position, width, etc.) between executions. This state is maintained even across builds (as long as the app name stays the same). So what happens is if you generate the app without a width/height or change its width/height, that size gets saved. And when you build next time with a new width/height, then the cache will be found and reused. For many users this is the desired behavior (in the sense that they don't want to have to fiddle with window sizes after every update (for a distributed app).

So here's a few options for you in this instance:
- If you want to delete the current saved state that is present, it should be in `%APPDATA%\<app_name>-nativefier-<random_6_digit_code>\window-state.json`
- If you want to LOCK the width at a certain value (i.e., no resizing allowed), set the `--width`, `--maxWidth`, and `--minWidth` to the same value as the locked width, and `--height`, `--maxHeight`, and `--minHeight` to the same value as the locked height.
- If you don't want the app to keep this window state between builds, you can use the `--portable` flag to keep all settings in the app folder, but be aware that there are some things to be aware of when using this flag: https://github.com/nativefier/nativefier/blob/master/API.md#portable
