### ISSUE TITLE
All external url's open in a new tab in same window

### ISSUE THREAD

**Issue by luvis** [nativefier/nativefier#1228]
This is my full command to create the app for google chat.

nativefier 'https://chat.google.com/' --internal-urls '.*?chat.google.com.*?' -i chat.icns -n Chat --width 600px --height 950px --tray --counter --user-agent 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0'

All my links open in a new tab in the same application window. How can I set it to open in my default browser instead? I can right-cllick a link and open in default browser, that works, but not just clicking on the link..

**Comment by grundprinzip** [comment]
I have the same issue, tried different combinations of `--internal-urls` but could not get it working.

**Comment by TheCleric** [comment]
Looks like this was a bug introduced in version 44.0.0. I'll take a look at what the cause may be. For now if you want to mitigate the issue, 43.1.3 works if you want to use that: `npm install -g nativefier@43.1.3`

**Comment by luvis** [comment]
> Looks like this was a bug introduced in version 44.0.0. I'll take a look at what the cause may be. For now if you want to mitigate the issue, 43.1.3 works if you want to use that: `npm install -g nativefier@43.1.3`

Thanks for the quick response! Yes 43.1.3 seems to work fine for me as well. I see you have added a fix too, awesome =)

**Comment by TheCleric** [comment]
We'll still make sure this gets fixed. Going to reopen so that we can track when it's in version 44+

**Comment by vic-pic** [comment]
Hi TheCleric,
I have this issue with 45.0.4 version of nativefier on macos Big Sur, all links opens in a new tab. This behavior doesn't happen on Linux.

**Comment by pavlvs327** [comment]
Same here; 45.0.4 installed from homebrew on Big Sur.
