### ISSUE TITLE
Old build detect macOS

### ISSUE THREAD

**Issue by ikiK-CRO** [nativefier/nativefier#1233]
I have gotten Old build detect macOS massage on my test App, I have also read topic: https://github.com/kelyvin/Google-Messages-For-Desktop/issues/34 and links appended there. 

I have bit of a problem in my usage case with this:

- I serve my application under https and basic-auth, for MULTIPLE subdomains for each client separately. 
- Code served vary from client to client. And code itself is my own. I take care of security from access to all code in my App.
- I do not have update servers due to variety of login basic-auth credentials and number of pre-defind sub-domains. 
- As of build itself I have only very little CSS and JS injected on build. 99% is served on my servers, and 99% changes to my "apps" are on server side.

With all this stated the case of "browsing the internet with old build" I believe does not apply to my usage case. 

It has now given me a task to follow date of each build for each client separately to make this unconformable massage does not pop up too them. 

I do follow all new releases of Nativefier but I do not chose to update all my clients apps every 90 days, from time to time I bump them all at once and offer new builds via download link to each client. 

I see --disable-old-build-warning-yesiknowitisinsecure flag that is manetiond is 404, not found?

If that is the case I really would like option to disable this. Or make those days longer myself at least. 
(if I understand what I read on links provided at start, this is not possible to do myself?)

Thank you for reply in advance.

**Comment by ronjouch** [comment]
@ikiK-CRO what do you mean by

> I see `--disable-old-build-warning-yesiknowitisinsecure` flag that is manetiond is 404, not found?

The flag is [documented in API.md](https://github.com/nativefier/nativefier/blob/master/API.md#disable-old-build-warning-yesiknowitisinsecure). Did you mean it is broken?

**Comment by ikiK-CRO** [comment]
> @ikiK-CRO what do you mean by
> 
> > I see `--disable-old-build-warning-yesiknowitisinsecure` flag that is manetiond is 404, not found?
> 
> The flag is [documented in API.md](https://github.com/nativefier/nativefier/blob/master/API.md#disable-old-build-warning-yesiknowitisinsecure). Did you mean it is broken?

Oh my God, I feel dum now. I have follow links from other topic. https://github.com/nativefier/nativefier/blob/master/docs/api.md#disable-old-build-warning-yesiknowitisinsecure That is not found. 

And believe it or not, I have went threw API docs before posting this, and I have missed it. I haven't searched the flag by name, and have missed it while browsing. 

I'm sorry for inconvenience. 

Thanks one more time for great work on this!

**Comment by ronjouch** [comment]
@ikiK-CRO no worries 🙂. Yeah I renamed API.md to have it at the root of the project, for obviousness / find-ability. This must have caused a few 404s and broken bookmarks, but I'm okay with this and remain happy we did it.

As for the flag, the documentation still stands: not recommended, but with documented consequences, it's here if you need it with its very explicit name.

With this, closing. Feel free to chime in if the flag is broken and we'll re-open the issue.

**Comment by ikiK-CRO** [comment]
I understand the consequences, and like I said I do bump them myself from time to time, I just don't need this x days constraint. 

Thanks! I will create new build right away to test this. So you wont hear from me on this topic for next 90 days, and hopefully never ;)
