### ISSUE TITLE
How to properly update Nativefier (MacOS)

### ISSUE THREAD

**Issue by solepixel** [nativefier/nativefier#1240]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I searched existing issues, open & closed. Yes, my question is new.
- [ ] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Your question**

What is the proper way to update Nativefier? So far I've tried:
- `npm update -g nativefier`
- `npm install -g nativefier`
- `npm remove -g nativefier` then `npm install -g nativefier`

It appears after `install`, I'm seeing the latest package installed, however when I run `nativefier -v`, it shows an older version. I don't think any of the attempts I've tried actually overwrite `/usr/local/bin/nativefier` and I'm not sure how to fix that. Do I just delete `/usr/local/bin/nativefier` and then run `install`?

**Steps to reproduce**

1. Run `nativefier -v` and note the version is outdated (currently showing 43.0.0)
2. Run any of the commands mentioned above
3. Run `nativefier -v`, expecting latest version to display (44.0.4) but still shows older version (43.0.0)

**Debug info**

Screenshot: https://3cd.co/7KuoAER1
![Screen Shot 2021-06-23 at 6 23 17 AM](https://user-images.githubusercontent.com/882391/123088611-91b0f200-d3eb-11eb-877b-5c54eb69ba44.png)

**Context**

 - Nativefier: 43.0.0
 - Node.js: 14.16.1
 - Npm: 6.14.12
 - OS: MacOS Big Sur v11.4 (20F71)
 - Shell: All commands ran in Terminal App

**Comment by TheCleric** [comment]
If you uninstall Nativefier does the `nativefier` command continue to work? If so I would try doing `sudo rm -rf /usr/local/bin/nativefier` and then redo the `npm install -g nativefier`. Let me know how this works.

**Comment by solepixel** [comment]
Yay! Thank you @TheCleric! Looks like that did the trick. I'm not sure why I had nativefier in my `/usr/local/bin` folder to being with? When I removed and re-installed it, it now shows up in `/Users/{USERNAME}/.nvm/versions/node/v14.16.1/bin/nativefier` and works fine, even after restarting Terminal. Anyway, thanks for the help!!

**Comment by TheCleric** [comment]
My guess would be it was installed prior to nvm being installed and `/usr/local/bin` comes before nvm's bin directory.
