### ISSUE TITLE
Support granting/denying web permissions (e.g. clipboard, microphone, camera, notifications), and maybe switch to more secure nothing-enabled-by-default

### ISSUE THREAD

**Issue by AgentSmith0** [nativefier/nativefier#1246]
Is it possible to automatically grant permissions like clipboard access or notifications?

**Comment by ronjouch** [comment]
@AgentSmith0 I assume you are talking about macOS permissions. To my knowledge, no, that'd defeat the purpose. Closing, but feel free to come back with more info and we can re-open if there's something worth adding.

**Comment by AgentSmith0** [comment]
I didn't mean macOS permissions specifically, I mean permissions in general. For example if your website requires microphone access, the browser is asking the user for permission. But I didn't see any popup in my nativefier app, so I wanted to ask if there is a way to force allowing some or all permissions.
Here is an example for such a permission popup:
https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Build_a_phone_with_peerjs/Connect_peers/Get_microphone_permission/1oieizmfmllnygbsdu4f1iq.png
Here are some links:
https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API
https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/build_a_phone_with_peerjs/connect_peers/get_microphone_permission
https://developer.mozilla.org/de/docs/Web/API/notification/permission
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read

**Comment by ronjouch** [comment]
@AgentSmith0 right, got confused about the question.

Did you try it? Nativefier grants these permissions already. Try it for yourself:

- ✔ https://async-clipboard-api.glitch.me/ → both Copy/Paste buttons work
- ✔ https://www.html5rocks.com/en/tutorials/getusermedia/intro/ → "Capture video" and "Stop" work
- ✘ https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API → "Notify me!" button doesn't work, this may be https://github.com/nativefier/nativefier/issues/1078

, so I guess your question becomes "Can/should permissions like clipboard / microphone / video/notifications be denied (maybe by default), and allowed/denied via a flag". Seems legit, renaming the issue.

**Comment by AgentSmith0** [comment]
Are the permissions also automatically granted when the website is not using a https protocol?

**Comment by TheCleric** [comment]
> Are the permissions also automatically granted when the website is not using a https protocol?

I'd be unsure without a test site to try on. You could also add the `--insecure` flag during app creation to see if that helps.

**Comment by AgentSmith0** [comment]
Local server without https do not have all permissions automatically granted. I tried it with a server in my network, it's address is something like http://192.168.0.10
I already tried adding the `--insecure` flag, but this doesn't solves my issue. Is there a way to fix this?

**Comment by AgentSmith0** [comment]
I was able to use https on my server and everything is working fine with nativefier. I will close this issue for now.
Thank you all for your great help!
