### ISSUE TITLE
Support macOS' trafficLightPosition API to set window close/maximize/minimize buttons position

### ISSUE THREAD

**Issue by tankxu** [nativefier/nativefier#1249]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md , no existing option fits my needs.
- [x] I searched existing issues, open & closed. Yes, my feature request is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Problem statement**

Hi, i used the nativefier built two macOS app with frameless window, but the default traffic lights button position with `--title-bar-style hidden/hiddenInset` is not ideal, i want to move them a bit right and down.

**Suggested solution**

Electron offer a **trafficLightPosition** api to set the traffic lights position, if nativefier support this api, the built app will looks more native.
About trafficLightPostion api: https://github.com/electron/electron/pull/21781

**Context**

 - Nativefier: 44.04
 - OS: macOS 11.4

**Comment by TheCleric** [comment]
This should already be something that can be done with the `--browserwindow-options` command line like so:

`nativefier https://site.com --browserwindow-options '{"trafficLightPosition": {"x": 100, "y": 100}}'`

**Comment by tankxu** [comment]
Thanks @TheCleric and @ronjouch, have a nice day.

**Comment by Aeneon** [comment]
> This should already be something that can be done with the `--browserwindow-options` command line`

… but it doesn't work with latest Electron ( 13.4 ) specified. It also doesn't work with other Electron Versions like 9.0.0 and 12.0.0, which I've tested. What I'm doing wrong ? This is my Command Line :

nativefier https://site.com --title-bar-style hidden --browserwindow-options '{"trafficLightPosition": {"x": 100, "y": 100}}'
