### ISSUE TITLE
Can't build for Windows 32-bit

### ISSUE THREAD

**Issue by AgentSmith0** [nativefier/nativefier#1254]
Is set the `--platform` flag to win32, like it is written here: https://github.com/nativefier/nativefier/blob/master/API.md#platform
But I get the following error message:
```
Invalid values:
  Argument: p, Given: "win32", Choices: "darwin", "linux", "mac", "mas", "osx", "windows"
```

Note: I have wine installed and I already tried a windows platform build, but it doesn't run on a 32-bit Windows computer.

Is there a way to make a build for Windows (32-bit)?

**Comment by mattruzzi** [comment]
The platform and arch are separate flags, use `--platform windows --arch ia32`.

**Comment by ronjouch** [comment]
Thanks @mattruzzi . I pushed an improvement to API.md hopefully letting users not fall into this gotcha.

**Comment by AgentSmith0** [comment]
Thank you all very much, this solved my issue.
