### ISSUE TITLE
Set app menu bar from webapp menu bar

### ISSUE THREAD

**Issue by tbrodbeck** [nativefier/nativefier#1257]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md , no existing option fits my needs.
- [x] I searched existing issues, open & closed. Yes, my feature request is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Problem statement**

![Screen Shot 2021-07-13 at 15 33 50](https://user-images.githubusercontent.com/24418160/125462101-05eb4304-2bda-46b5-ba2c-e5304d45086d.png)
As you can see in the image there are applications like https://github.com/cdr/code-server that actually have a menu bar that could be put in the macOS app menu.

**Suggested solution**

It would be great if this menu bar of the web app could be put/accessed into the macOS app menu bar. 

**Alternative solutions**

I have tried to set the `-m`/`--show-menu-bar` flag of nativefier but it did not help.

**Context**

 - Nativefier: 44.0.7
 - Node.js: 16.4.2
 - Npm: 7.18.1
 - OS: macOS 11.4

**Comment by mattruzzi** [comment]
The menu bar in webapps is just DOM elements and is done differently for every app, so we would have to write different code to extract the items for every supported app. Then we would have to somehow communicate this to the electron code that sets the menu bar, and it would have to communicate this back and emulate a click on the DOM element that the webapp menubar is made of or somehow trigger the action. This would be really cool but seems like the kind of thing that would be a pain to maintain unless there was some kind of standard.

**Comment by ronjouch** [comment]
I must agree with @mattruzzi here. I usually leave feature requests open regardless of the probability to implement, but this is so far-fetched that it makes no sense to implement and maintain. If you want progress on this, as hinted by Matt, you can try to help standardize such a thing, and work with browser makers.

With that, closing as wontfix.
