### ISSUE TITLE
[Project internals] Switch issues from GitHub "issue templates" to new/beta "issue forms"

### ISSUE THREAD

**Issue by ronjouch** [nativefier/nativefier#1258]
We use GitHub "issue templates" to push / force users to write good issues containing all the necessary information. See [our `.github/ISSUE_TEMPLATE` folder](https://github.com/nativefier/nativefier/tree/master/.github/ISSUE_TEMPLATE).

GitHub recently released a new feature called "issue forms", which are basically ***structured*** issue templates, enabling a clearer separation between issue template filler and the actual issue, for better (?) user experience. See:

- [GitHub Docs / Issue & PR templates / Creating issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)
- [GitHub Docs / Issue & PR templates / Syntax for GitHub's form schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)

It looks neat and I think I'll give it a try these days. This is a little issue

1. To remind me to try it
2. To encourage passersbys who already used it to give feedback about it: how did it go for you? (As a user or project maintainer?) Does it work as advertised? Any annoying limitations? Does it look like a great idea but turns out to be inflexible from a user perspective in the end? Etc; all feedback welcome 🙂.

**Comment by TheCleric** [comment]
Saw that today and was very interested given the tendency of some reporters to flat out ignore our requested format.

**Comment by ronjouch** [comment]
> Saw that today and was very interested given the tendency of some reporters to flat out ignore our requested format.

@TheCleric yup, and it's not by failure to try a lot of variants on insisting that incomplete bug reports makes everybody lose time (see blah at the top of our templates) :shrug: . So, when we try the new thing, for sure it won't eliminate all these "flat out ignoring our requested format" cases, but who knows, maybehopefully it can help reduce them a bit.

The dramatic way to actually solve this is to setup a bot to auto-close issues not matching our requested pattern (vuejs/vue used to do this, not sure it stil does). I don't think we have such a high volume of issues to justify it though; I deal with it with canned answers asking for clarification.

**Comment by TheCleric** [comment]
> The dramatic way to actually solve this is to setup a bot to auto-close issues not matching our requested pattern (vuejs/vue used to do this, not sure it stil does). I don't think we have such a high volume of issues to justify it though; I deal with it with canned answers asking for clarification.

Yeah or just closing them and telling them to refile with better info, but that always felt icky to me.

**Comment by mattruzzi** [comment]
Electron is now using issue forms. 
https://github.com/electron/electron/issues/new
https://github.com/electron/electron/tree/main/.github/ISSUE_TEMPLATE

They are requiring that the "I have searched for existing issues and my issue is new" checkbox is checked before someone can submit an issue. I don't know if this would  couse any problems with people "lying" and checking it even if they haven't actually done it, so that they can submit the issue form.

**Comment by ronjouch** [comment]
@mattruzzi thanks for the heads up! I was leaving this up in the air without trying it, because I first wanted to see how that works for another project, and so far I haven't met any.

1. I'll take some time to see patterns and anti-patterns in recent Electron issues and document my findings here.
2. @mattruzzi @TheCleric if you have time to look at how that works in Electron, please do so too and share facts here. Thanks!

---

Also, off-topic but on the topic of issues and issues triaging. @mattruzzi I see you regularly comment and help on issues, and you're doing good. Would you like me to grant you a "Triager" GitHub role, giving you rights to label / rename / close+reopen issues? As you may have read here and there, we need more hands.

Take your time to evaluate whether you want this or not, "no thanks" is a fine answer if your current "occasional commenter" position suits you. Also, from my side, I'd rather have a few regularly active co-committers/triagers rather than 10 ghost ones (to start with, for security). So,

- Expectations: occasional triaging, following our triage guidelines (that are currently informal but that I'll formalize and we'll discuss in a PR if you accept).
- Non expectations: anything excessive that gets you burned out. Open source maintenance is long-distance walking, not a sprint.

**Comment by mattruzzi** [comment]
@ronjouch @TheCleric  I started working on converting our issues templates to issue forms in a separate repo. 
https://github.com/mattruzzi/issueformstest
