### ISSUE TITLE
App content is blurry with HiDPI/4K resolutions under Linux / Wayland

### ISSUE THREAD

**Issue by seltzered** [nativefier/nativefier#1262]
=======================================================
- [X] Looked at API, might be a way to do this with --inject but haven't had luck yet.
- [X] There's a similar issue but around windows - https://github.com/nativefier/nativefier/issues/598 . Issue named similarly.
- [X] Yes, using nativefier v45.0.0 (latest at time of writing)

**Your question**

Hi, I'm trying to use nativefier on Ubuntu 21.04 (uses wayland by default) on a HiDPI display. App content is blurry which is seemingly due to a combination of using wayland and being on a HiDPI display (3000x2000 operating at 2x scaling). So here's what running a nativefier without any options upon build or runtime looks like:

![Screenshot from 2021-07-21 13-32-53](https://user-images.githubusercontent.com/297435/126541624-83581ab8-fa16-4120-925c-8cb558fbbf75.png)

I understand there's a way to somehow do this with `--enable-features=UseOzonePlatform --ozone-platform=wayland` , as mentioned https://github.com/microsoft/vscode/issues/109176#issuecomment-729615690 . I'm probably not doing this right but actually passing these as runtime options (e.g. ` ./Trello https://trello.com --enable-features=UseOzonePlatform --ozone-platform=wayland`) yields a non-blurry result BUT the standard window chrome disappears and it's not possible to move the window around:

![Screenshot from 2021-07-21 13-38-23](https://user-images.githubusercontent.com/297435/126542887-b13a09e1-ad24-4c2f-bc24-4f4ee0752333.png)

**Steps to reproduce**

- Be on a wayland environment and have 2x scaling on (typically used on a HiDPI display).
- Try nativefying a site like trello.com - `nativefier -n Trello https://trello.com`
- Try running the nativefied site `./Trello` , observe blurry window
- Try running with options, observe less blurry window but without window chrome: ` ./Trello https://trello.com --enable-features=UseOzonePlatform --ozone-platform=wayland`

**Debug info**

Guessing unrelated, but I do get error on launching app: `libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)`

**Context**

 - Nativefier: 45.0.0
 - Node.js: 16.5.0
 - Npm: 7.19.1
 - OS: Ubuntu 21.04
 - Additional context: HiDPI tablet display + wayland

**Comment by vially** [comment]
> I'm probably not doing this right but actually passing these as runtime options (e.g. ./Trello https://trello.com --enable-features=UseOzonePlatform --ozone-platform=wayland) yields a non-blurry result BUT the standard window chrome disappears and it's not possible to move the window around:

You're doing everything right but the missing window chrome is a [known issue](https://gitlab.gnome.org/GNOME/mutter/-/issues/217) that happens when running Electron apps under GNOME.

Unfortunately, unless you're willing to change your desktop environment (e.g.: to KDE/sway/etc), there's currently no easy workaround for this issue (but it might be fixed on the Electron side in the future: https://github.com/electron/electron/pull/29618).

In any case, my impression is that these are upstream issues and I'm not sure if there's much that can be done about it in `nativefier` (but I'm not familiar enough with it so I may be wrong).

**Comment by seltzered** [comment]
For those still trying to make this work, nativefier 47 is updated to electron 18 and now sorta supports this, but you have to add the `--ozone-platform=wayland --enable-features=WaylandWindowDecorations` options mentioned in https://github.com/electron/electron/pull/29618#issuecomment-1022009201 to make it work.
