### ISSUE TITLE
[New internal login page request] id.atlassian.com

### ISSUE THREAD

**Issue by dserodio** [nativefier/nativefier#1265]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

Treat id.atlassian.com and auth.atlassian.com as login URLs

**Steps to reproduce**

Wen trying to use nativefier with Trello, using SSO with Google, I had to use the following parameters:

```
nativefier 'https://trello.com' --internal-urls 'accounts\.google\.com|id\.atlassian\.com|.*?\.trello\.com|auth\.atlassian.com' --name Trello
```

**Context**

 - Nativefier: 45.0.0
 - Node.js: 16.5.0
 - Npm: 7.19.1
 - OS: macOS Catalina (10.15.7)
 - Is it a regression? No

**Comment by ronjouch** [comment]
Yup, thanks! Done, will ship in the next release.
