### ISSUE TITLE
How to install on windows?

### ISSUE THREAD

**Issue by Msadr471** [nativefier/nativefier#1271]
**Homework**

- [ ] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I searched existing issues, open & closed. Yes, my question is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Your question**

> Then, install Nativefier globally with `npm install -g nativefier`
![image](https://user-images.githubusercontent.com/49529241/130309424-bfd4647d-c067-4f84-b201-caa92237c61e.png)

How to install on windows?

**Context**

 - Nativefier: **_I don't know_**
 - Node.js v14.17.5.
 - Npm: 6.9.0
 - OS: Windows 10 build 1809

after I run `nativefier`:
![image](https://user-images.githubusercontent.com/49529241/130309386-f38f7e41-a62d-419c-abcf-40725e7433da.png)
![image](https://user-images.githubusercontent.com/49529241/130309391-062e79b4-4133-4559-b568-bea862b8a439.png)
![image](https://user-images.githubusercontent.com/49529241/130309462-21e7d612-a41a-4222-a9d6-24f1eed959ee.png)
![image](https://user-images.githubusercontent.com/49529241/130309467-fb6fc182-7d7b-45c3-9da5-ffb7adc30b8f.png)
![image](https://user-images.githubusercontent.com/49529241/130309489-23b4af6e-11de-4924-beb5-2344df72e804.png)

**Attached **
[i.txt](https://github.com/nativefier/nativefier/files/7024812/i.txt)

**Comment by ronjouch** [comment]
Hi @Msadr471 . This looks like misuse of your Node version manager, https://github.com/nullivex/nodist . Please switch to an official Node install, or get support from Nodist.
