### ISSUE TITLE
Nativefier Doesn't Inject CSS Properly

### ISSUE THREAD

**Issue by ibratabian17** [nativefier/nativefier#1290]
The UI Look Broken & Different from original .css file
Nativefier : 
![image](https://user-images.githubusercontent.com/71920907/136053125-2b64c481-bc7d-46fb-9865-e3e932016ce0.png)
Chrome : 
![image](https://user-images.githubusercontent.com/71920907/136053270-a26110c5-29e3-418f-b4b7-b0e4b595195a.png)
I Tried Using Javascript, But it give a little change

LOG : https://pastebin.com/raw/ecvYcG8h

**Comment by TheCleric** [comment]
@ibratabian17 could you let us know how you fixed it in case others have a similar issue?
