### ISSUE TITLE
Create app without "-win32-x64" in the name.

### ISSUE THREAD

**Issue by erperion** [nativefier/nativefier#1309]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I searched existing issues, open & closed. Yes, my question is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Your question**
[I'm following readme](https://github.com/nativefier/nativefier#usage)
>To create a native desktop app for medium.com, simply nativefier "medium.com"

> Nativefier will try to determine the app name, and well as lots of other options. If desired, these options can be overwritten. For example, to override the name, nativefier --name 'My Medium App' 'medium.com'

and I'm trying to create app:
nativefier --name 'Google Calc' https://docs.google.com/spreadsheets/u/0/
or
nativefier --name 'Google Calc' 'https://docs.google.com/spreadsheets/u/0/'

but it gives me this error:
> URL "Calc'" lacks a protocol. Will try to parse it as HTTPS: "https://Calc'". Please pass "http://Calc'" if this is what you meant.
Cannot automatically retrieve the app icon: Error: getaddrinfo ENOTFOUND calc

and the app is not created. First example uses double quotes and second (with --name) uses single quotes. Is the readme section outdated or I don't understand something? 

Anyway I wrapped name in double quotes:
nativefier --name "Google Calc" https://docs.google.com/spreadsheets/u/0/
and it works but the app created is named "Google Calc-win32-x64". Is there a way to create app without "-win32-x64"? Or if I rename app after creating it will I be able to update it?

**Context**

 - Nativefier: 45.0.5
 - Node.js: 17.1.0
 - Npm: 8.1.4
 - OS: Windows10 21H2 OS build 19044.1348

**Comment by TheCleric** [comment]
The "-win32-x64" is just a folder that it is placed into. The exe should be named `Google Calc.exe`. The contents of this folder (including the executable) can be moved wherever you'd like.
