### ISSUE TITLE
[Bug] Not using userAgentFallback to inject the userAgent causes service workers to get the Electron user agent

### ISSUE THREAD

**Issue by firefinchdev** [nativefier/nativefier#1312]
This is the same issue thats been raised many times here. Eg: https://github.com/nativefier/nativefier/issues/1112
Using latest release of nativefier, the above problem exists even if user agent is overridden.
The troubleshooting steps mentioned in README didnt help either.
This is because user agent used by service worker is still the original one. (Ref: https://github.com/GoogleChrome/workbox/issues/2314)

According to the link above, it makes sense to use the original user agent for service workers.

But for the scope of nativefier, things are different. We can have an app level user agent.
Seems like Electron does have some option for this.
See https://github.com/electron/electron/issues/16196
https://github.com/electron/electron/issues/16196#issuecomment-591674111

**Comment by TheCleric** [comment]
We do use this to an extent (if you do not provide a user agent and don't specify the user agent honest flag. However a quick experiment with doing this for all (even injected user agents) seems promising. I'll see if we can get a release to do this soon.
