### ISSUE TITLE
documnet.write not work in child window

### ISSUE THREAD

**Issue by yuviprathap** [nativefier/nativefier#1313]
//Code start 
 window.screenX = 1360
 var width = 650;
 var left = 500;
 left += window.screenX;
 var printWindow = window.open('', 'printWin', 'resizable=1,scrollbars=1,fullscreen=0,height=200,width=' + width + '  , left=' + 
 left + ', toolbar=0, menubar=0,status=1');
  var writeMe = ('<body><head>' + $('head').html() + '</head><html>');
  writeMe += ("<div id=myText class='col-6'>Well come Prathap</div>");
  writeMe += ('</html></body>');
  printWindow.document.write(writeMe);
  printWindow.document.close();
  printWindow.focus();
//Code End

The above one is my code , its was working fine in chromes browser,but after I converted nativefier exe its not working throw error
documet.write undefined . Can you please help me for this issue?

**Comment by TheCleric** [comment]
Sorry to be a jerk, but please use the new issue format when filing an issue as it will help us answer your question better. Closing, but feel free to create a new issue for this, following the prescribed format.

**Comment by yuviprathap** [comment]
what a replay also closing bug ah thanks :)
