### ISSUE TITLE
`--single-instance` crashes the app on macOS Monterey.

### ISSUE THREAD

**Issue by martin-braun** [nativefier/nativefier#1314]
`--single-instance` crashes the app on macOS Monterey.

_Originally posted by @o9uzdev in https://github.com/nativefier/nativefier/issues/1295#issuecomment-954807992_

---

I have the same problem, so I want to reference this comment into a new issue, because it doesn't seem to be related with the referenced issue on BigSur. The issue introduced on Monterey.

**Comment by emicha** [comment]
I have the same issue. Using Monterey + https://github.com/nativefier/nativefier/releases/tag/v45.0.6

**Comment by JAKgit** [comment]
I can confirm this issue.

**Comment by schloram** [comment]
Same problem here with Monterey and Nativefier 45.0.8

**Comment by dsXLII** [comment]
For what it's worth, I'd been having the same problem, but it seems to have gone away with 46.0.

**Comment by schloram** [comment]
Yes. I can confirm that it is working with Nativefier 46.0.0
