### ISSUE TITLE
How to open child window always in second screen is it possible ?

### ISSUE THREAD

**Issue by yuviprathap** [nativefier/nativefier#1318]
Hai, My question is simple .
  I am created app in angularjs then converted into exe using nativefire. Now what my problem is.
I want to open all my child windows in second screen .

is it possible to do in nativefire ?

**Comment by ronjouch** [comment]
Hi @yuviprathap. This is not possible in Nativefier, and this is the OS job, not something we want / can / plan to implement. On some OSes (e.g. Linux/Wayland) it's alright impossible.

**Comment by yuviprathap** [comment]
Okay Thanks for the information
