### ISSUE TITLE
Bookmark as internal url and all open new tab as title-bar-style hidden

### ISSUE THREAD

**Issue by AjayShanker-geek** [nativefier/nativefier#1319]
**Homework**

- [X] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md , no existing option fits my needs.
- [X] I searched existing issues, open & closed. Yes, my feature request is new.
- [X] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

Hi, possible to open bookmark as an internal url by changing `"type": "link",` in the .json config. Also making all internal url open with title-bar-style hidden.

**Context**

 - Nativefier: 45.0.6
 - Node.js: v16.13.0
 - Npm: 8.1.0
 - OS: macOS 12.0.1 21A559 arm64

**Comment by ronjouch** [comment]
@AjayShanker-geek I don't understand your feature request; can you reformulate?
