### ISSUE TITLE
Release request for 45.0.7

### ISSUE THREAD

**Issue by firefinchdev** [nativefier/nativefier#1320]
Since https://github.com/nativefier/nativefier/pull/1316 is now merged, maybe we can make a minor release...

**Comment by ronjouch** [comment]
Yes, will release soon. Please don't make such issues, it's not like it's been months since the last release. Just wait or make a dev build.

**Comment by mattruzzi** [comment]
Should we bump electron to [13.6.3](https://github.com/electron/electron/releases/tag/v13.6.3)?

**Comment by ronjouch** [comment]
> @ronjouch Should we bump electron to [13.6.3](https://github.com/electron/electron/releases/tag/v13.6.3)?

@mattruzzi yup I always bump to the latest minor/patch before I release.
