### ISSUE TITLE
Inject only on default link and not the bookmarks Pages

### ISSUE THREAD

**Issue by AjayShanker-geek** [nativefier/nativefier#1323]
- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I searched existing issues, open & closed. Yes, my question is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

Possible to exclude `--inject` to the bookmark links or a specific page.

**Context**

 - Nativefier: 45.0.6
 - Node.js: v16.13.0
 - Npm: 8.1.0
 - OS: macOS 12.0.1 21A559 arm64

**Comment by ronjouch** [comment]
@AjayShanker-geek I don't understand your question; can you reformulate?

**Comment by ronjouch** [comment]
Closing as issue wasn't reproducible and didn't get feedback. Feel free to chime in, we'll re-open the discussion 🙂.
