### ISSUE TITLE
Pretected content error in Amazon prime video

### ISSUE THREAD

**Issue by AbnHL-24** [nativefier/nativefier#1329]
Hi, I have the problem that in Amazon Prime Video when I want to play some content it tells me that I have a "protected content error". I would be very grateful if you could help me with this.
![image](https://user-images.githubusercontent.com/50131827/145951464-ac421c39-1678-4b76-b433-612f9b364772.png)

**Comment by ronjouch** [comment]
Try https://github.com/nativefier/nativefier/blob/master/API.md#widevine

**Comment by AbnHL-24** [comment]
I have read the documentation, it was fixed by adding --widevine when building the app.
It would be like this:
nativefier "https://www.primevideo.com/" --widevine

**Comment by AbnHL-24** [comment]
> Try https://github.com/nativefier/nativefier/blob/master/API.md#widevine
Thank you, that solved the problem.
