### ISSUE TITLE
create from a server localhost adress

### ISSUE THREAD

**Issue by maverick40** [nativefier/nativefier#1330]
Hello, how can I create an application, with a local internet adress:
 http: //localhost:4040/

 I have an audio server on my pc and I would like to create the application.

thx

**Comment by SrIzan10** [comment]
i mean, you can, but only you can use it.
if you want more people to use it, you’ll need to host it on a server hosting company like linode or google cloud, and if you want to still self host it yourself, you can port forward.

**Comment by maverick40** [comment]
I found the solution: You have to add all the complete address, like this for example: http://localhost:4040 /web/index.php/xxxxx/xxx. 
The x correspond to the target while being connected to the site with his user account.

Thx
