### ISSUE TITLE
Widevine error

### ISSUE THREAD

**Issue by ReazerDev** [nativefier/nativefier#1341]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

When I'm trying to run an app that uses widevine on arch linux, I get the following error:
![image](https://user-images.githubusercontent.com/36013882/150001118-5be6a8a9-19b4-4c66-9f82-6bd8bb0d990c.png)

**Steps to reproduce**

It builds successfully and everything worked on Ubuntu.
The website works without a problem in my Chrome Browser.

**Expected behavior**

App should start

**Actual behavior**

App doesn't start. See error above.

**Debug info**

**Context**

 - Nativefier: (for example: 45.0.5)
 - Node.js: (for example: v17.3.1)
 - Npm: (for example: 8.3.0)
 - OS: (for example: Arch Linux 5.16.0-arch1-1)
 - Is it a regression? 
 - Additional context: (for example: "I'm on my own branch https://github.com/nativefier/nativefier/pull/1306 Finally got motivation to finish this lol")

**Comment by ronjouch** [comment]
Please rebase your branch to get 5e3c23267a57f0f61e97e9367c780e0db2c728d9, shipped in [46.0.1](https://github.com/nativefier/nativefier/releases/tag/v46.0.1).

**Comment by rxng** [comment]
how does one rebase branch in this way when using npm install? I used npm install nativefier@46.0.1 , but still getting the app.widevine-error . 

The latest version doesn't run with widevine either
