### ISSUE TITLE
title-bar-style does not work with youtube.com on macOS

### ISSUE THREAD

**Issue by jandb1980** [nativefier/nativefier#1353]
I'm building my apps with the following command:
`nativefier --name 'YouTube' --icon '/Users/.../OwnApps/Pictures/youtube.icns' 'https://www.youtube.com/' '/Users/.../OwnApps/FinalApp' --inject '/Users/.../OwnApps/site.css' --title-bar-style 'hiddenInset' --tray --bookmarks-menu '/Users/.../OwnApps/Bookmarks/youtube.json' --disable-dev-tools --fast-quit`

The Code in the site.css is the following:
`body {
-webkit-app-region: drag;
}

/* make class elements draggable */
.aside-brand-wrapper {
-webkit-app-region: drag;
padding-top: 5px;
}

div#kt_header {
-webkit-app-region: drag;
}

/* make element with ID not draggable */
div#kt_aside_menu_wrapper {
-webkit-app-region: no-drag!important;
}

div#kt_content {
-webkit-app-region: no-drag!important;
}`

Any web page I build into an app with this command works fine. I can move the window with the mouse.

Only with youtube.com it does not work. The window stays fixed in the middle of the screen and cannot be moved.

Do I need to adjust the code in site.css for youtube?

**Comment by Danos0100** [comment]
Try `#masthead-container {
  -webkit-app-region: drag;
}

#masthead-container button, #masthead-container link, #masthead-container input, #masthead-container yt-icon{
  -webkit-app-region: no-drag;
}`

**Comment by jandb1980** [comment]
Very cool, thank you that works perfect.
