### ISSUE TITLE
Permanently saving HTML in DevTools

### ISSUE THREAD

**Issue by bimadam** [nativefier/nativefier#1355]
Hi, I’m using school website and I have to write username and password everytime I launch application. I tried saving HTML code (adding ,,value = "my_username/my_password",, in Chrome, it worked, but in Nativefier it didn’t worked. Is there any possible way to do it in Nativefier? 

 - Nativefier: 46.1.0
 - Node.js: 17.4.0
 - Npm: 8.3.1
 - OS: Windows 10 Pro Build 21H2

**Comment by ronjouch** [comment]
Closing as dup of https://github.com/nativefier/nativefier/issues/310

**Comment by bimadam** [comment]
Autokey isnt supported for Windows.
