### ISSUE TITLE
how do i pack the unpacked application

### ISSUE THREAD

**Issue by atordvairn** [nativefier/nativefier#1358]
how do i pack the unpacked application in Linux build ?

when i run the command in Linux i get the unpacked folder with the executable

the executable can't run solo
how do i pack all the files into a `.deb` or `.appimage` file

**Comment by ronjouch** [comment]
Closing as duplicate of #512

**Comment by ronjouch** [comment]
> how do i pack all the files into a .deb or .appimage file
See #249

> the executable can't run solo
That's not my experience. What do you mean?
