### ISSUE TITLE
Strange characters prefixing generated files

### ISSUE THREAD

**Issue by rxng** [nativefier/nativefier#1361]
Trying to access the generated output folder results in No such file or directory, and this is because the folder is prefixed by strange characters '$'\342\200\216' , so it cannot be accessed unless I type those strange characters. Wonder why nativefier chooses to prefix all the files with these?

Please see screenshot. I am on opensuse tumbleweed kde

![image](https://user-images.githubusercontent.com/19649766/155815809-1063222b-69be-4f08-b952-6fdceea45c9b.png)

**Comment by Tedward747** [comment]
@rxng I've added a PR to fix this but unless you're building it from source it won't help you until the next release. In the mean time you have two options:

1) Use the --name argument every time you run nativefier, i.e.
`nativefier "https://music.apple.com" --name "AppleMusic"`

2) Patch the file, bit of work up front but then everything just works. Run the following:

If you don't have git installed:
`zypper in git`

Then:
```
cd /usr/local/lib/node_modules/nativefier/lib/utils
wget https://raw.githubusercontent.com/Tedward747/nativefier/1361-patch/patch
git apply patch
```

If nativefier isn't installed in that directory you can find it with
`find / -iname nativefier`

Then you should be able to head back to your normal working directory and run it without specifying --name.

Hope this helps
