### ISSUE TITLE
White screen, not showing app

### ISSUE THREAD

**Issue by sara246santos** [nativefier/nativefier#1366]
**Homework**

- [ ] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [ ] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [ ] I searched existing issues, open & closed. Yes, my bug is new.
- [ ] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

When clicking on the APP.exe, the browser opens but the screen is white and nothing shows, just a white screen.

**Steps to reproduce**

Give your ***full*** nativefier command and its logs, with the ***`--verbose` flag***, on a ***public*** site:

npm install -g nativefier

nativefier 'overleaf.com'

**Expected behavior**

Open overleaf website

**Actual behavior**

White screen

**Debug info**

- Console logs of your `nativefier` build command, with `--verbose` flag
- If the bug happens at app run time, the in-app DevTools console logs (open it with F12)
- Error messages
- Screenshots
- Anything else relevant!

**Context**

 - Nativefier: latest
 - Node.js: 16.14.0
 - Npm: 8.5.3
 - OS: Windows 10 Version 10.0.19041.1415
 - Is it a regression? If yes, what's the last working / first broken version? 
 - Additional context: (for example: "I'm behind a proxy, with configuration X and protocol Y")
![issue](https://user-images.githubusercontent.com/100968480/156841639-9acabcdf-8ac9-4521-8bb4-309e29c47283.png)

**Comment by Tedward747** [comment]
@sara246santos  try `nativefier "https://overleaf.com"`

![2022-03-06_12-31-15](https://user-images.githubusercontent.com/28074894/156939077-faaf2afc-c2af-49b8-87bc-cb146ba32a86.jpg)

**Comment by NickLM1200** [comment]
I got the same issue the first time I tried the system in a Microsoft Surface Pro 8, and when I run it on a different computer (virtual machine) it works fine. I tried all the different versions of a link, but I am still with the issue. I don't know if that happens to depend on the computer, setting, or some problem with the project.

**Comment by Tedward747** [comment]
@NickLM1200 if you want to provide the command you're using to build it I can take a look and see if I can figure out what's going on

**Comment by NickLM1200** [comment]
@Tedward747  First I tried nativefier '(any website)', and then I tried to change the client to Mozilla instead of google chrome, but it still doesn't work.

**Comment by Tedward747** [comment]
@NickLM1200 use `"` instead of `'`

`nativefier "https://google.com"`

see if that does the trick

**Comment by NickLM1200** [comment]
It does work with double quotes, Thanks @Tedward747
