### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by SRKRANTIKARI** [nativefier/nativefier#1370]
Hello dear nativerfier Dev's!
Can you please tell me how can i use nativerfier in TERMUX. i am newbie please tell

**Comment by ronjouch** [comment]
@SRKRANTIKARI hi. See [README.md](https://github.com/nativefier/nativefier/blob/master/README.md) for the basics, [API.md](https://github.com/nativefier/nativefier/blob/master/API.md) for the full help, and [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for examples.

With that, closing. Feel free to come back with a detailed question if you have problems.
