### ISSUE TITLE
A default injection method that automatically implements the scripts in CATALOG.md when a site in that file is access

### ISSUE THREAD

**Issue by JonAdrover** [nativefier/nativefier#1375]
- [ x ] I looked at nativefier --help and https://github.com/nativefier/nativefier/blob/master/API.md
- [ x ] I searched existing issues, open & closed. Yes, my question is new.
- [ x ] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Problem statement**
Nativefier should work smoother with complicated apps that are not compatible with the original build command. Existing options make it less user friendly because the apps listed in the Catalog are highly used.

**Suggested solution**
Scanning user input for common websites and implementing a default injection method instead of referring to the CATALOG for including a flag or injecting your own programming in the build process.

**Comment by ronjouch** [comment]
Yup, see #1130.
