### ISSUE TITLE
[Feature Request] Upgrade to electron v18

### ISSUE THREAD

**Issue by AgentSmith0** [nativefier/nativefier#1376]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

What about upgrading to electron v18, which comes with the latest Chromium v100: https://github.com/electron/electron/releases/tag/v18.0.0

Thank you very much for this awesome library!

**Comment by ronjouch** [comment]
@AgentSmith0 yup.

1. Feel free to pass `--electron 18.0.0` to give it a try already, maybe it'll work.
2. When I/anyone feels like changing the default, we follow [HACKING / Deps: major-upgrading Electron](https://github.com/nativefier/nativefier/blob/master/HACKING.md#deps-major-upgrading-electron).

**Comment by AgentSmith0** [comment]
Thanks, changing the electron version using the `--electron-version` parameter worked fine. I think v18 can be used as default value now.

**Comment by ronjouch** [comment]
👍. @AgentSmith0 pls report any electron18-specific issues in this thread if you encounter any (verifying that the problem doesn't happen with 16). Upgrading Electron is tricky, so we value feedback from users to warn us about stuff our own testing might miss.

**Comment by dkadioglu** [comment]
I think, I have found an issue with electron 18. I use Outlook Web App as nativefied and found the following issue:
If I build the native app with electron 18, then the inline preview of a pdf attached to an email doesn't work and produces an error (in german: Fehler beim Laden des PDF-Dokuments.). If I build the native app with electron 17.4.0, then the inline preview of a pdf attached to an email works as it should without error.

Any further info I should provide?

**Comment by ronjouch** [comment]
@dkadioglu thanks. Yes, please file a new issue and provide the information requested by the issue template.

**Comment by dkadioglu** [comment]
> @dkadioglu thanks. Yes, please file a new issue and provide the information requested by the issue template.

Done #1401
