### ISSUE TITLE
Unable to sign HBO Max with castLabs EVS on Linux

### ISSUE THREAD

**Issue by Flipp3rrr** [nativefier/nativefier#1377]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [ ] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

Following the steps for HBO Max in [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md#hbo-max) produces a `FileNotFound` error.

**Steps to reproduce**

```sh
$ nativefier "https://play.hbomax.com/" --widevine --enable-es3-apis


    Hi! Nativefier is minimally maintained these days, and needs more hands.
    If you have the time & motivation, help with bugfixes and maintenance is VERY welcome.
    Please go to https://github.com/nativefier/nativefier and help how you can. Thanks.



Processing options...

ATTENTION: Using the **unofficial** Electron from castLabs 
It implements Google's Widevine Content Decryption Module (CDM) for DRM-enabled playback. 
Simply abort & re-run without passing the widevine flag to default to 16.0.9+wvcus

Preparing Electron app...

Converting icons...

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
Packaging app for platform linux x64 using electron v16.0.9+wvcus

Finalizing build...
App built to /[...]/Nativefier/HBOMax-linux-x64, move to wherever it makes sense for you and run the contained executable file (prefixing with ./ if necessary)
Menu/desktop shortcuts are up to you, because Nativefier cannot know where you're going to move the app. Search for "linux .desktop file" for help, or see https://wiki.archlinux.org/index.php/Desktop_entries

$ python -m castlabs_evs.vmp sign-pkg HBOMax-linux-x64

FileNotFoundError: No matching executable found in: HBOMax-linux-x64

$ python -m castlabs_evs.vmp sign-pkg HBOMax-linux-x64/HBOMax

FileNotFoundError: No matching executable found in: HBOMax-linux-x64/HBOMax
```

**Expected behavior**

I expected the steps for signing in `CATALOG.md` to sign the app.

**Actual behavior**

CastLabs EVS returns a `FileNotFoundError`.

**Debug info**

![image](https://user-images.githubusercontent.com/33151653/161025633-168c17e1-94c3-4a70-a388-a8688337df47.png)

**Context**

 - Nativefier: 46.1.1
   - Installed from Arch Linux AUR
 - Node.js: v17.8.0
 - Npm: 8.5.5
 - OS: Arch Linux (rolling)

**Comment by TheCleric** [comment]
Possibly a new or previously unknown limitation in Castlabs signing where they don't appear to support Linux:

https://github.com/castlabs/electron-releases/issues/75

**Comment by Flipp3rrr** [comment]
> Possibly a new or previously unknown limitation in Castlabs signing where they don't appear to support Linux:
> 
> [castlabs/electron-releases#75](https://github.com/castlabs/electron-releases/issues/75)

Ah I see, thanks for the reply. From the wording from that issue it appears non-persistent signing is still possible, would that mean I have to sign it before every use?

**Comment by TheCleric** [comment]
> Ah I see, thanks for the reply. From the wording from that issue it appears non-persistent signing is still possible, would that mean I have to sign it before every use?

I'm not sure. You'd have to check their documentation.
