### ISSUE TITLE
Doesn't work for youtube tv

### ISSUE THREAD

**Issue by nrgapple** [nativefier/nativefier#1392]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

**Steps to reproduce**

```
nativefier --name "TV" 'https://tv.youtube.com/'
```

**Expected behavior**

youtube tv would work signed in

**Actual behavior**

![image](https://user-images.githubusercontent.com/10817537/163505989-3c6c3773-ab2b-4205-9079-029aa46105ae.png)

**Comment by Danos0100** [comment]
Google sites block login on electron apps as they not real chrome, so you must change the user agent to something else. Build with --user-agent "safari" or --user-agent "firefox". Login will probably still fail at first attempt, so click 'try again' and give it a few (up to 5) shots.

**Comment by nrgapple** [comment]
I will try that. I mainly asked this here to aid others that may try YouTube TV in the future. This post should be useful for the next person with the same issue searching google. Thanks for your response.
