### ISSUE TITLE
安装不了,希望有老师可以指点一下.

### ISSUE THREAD

**Issue by vipoky11** [nativefier/nativefier#1393]
npm install -g nativefier
Password:

changed 230 packages in 4s

38 packages are looking for funding
  run `npm fund` for details
为什么安装不了呢?希望有老师指点
mac

**Comment by ronjouch** [comment]
Hi @vipoky11, you're doing the right thing, and Nativefier is installed after what you did.

Now you must call it. For that, do a bit of searching on how to add installed node.js binaries to your macos unix $PATH variable of your shell (bash, probably). Then nativefier will work when you call `nativefier` from your terminal.
