### ISSUE TITLE
Absolute path error for MacOS Universal

### ISSUE THREAD

**Issue by Randomblock1** [nativefier/nativefier#1398]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

The new Universal binary builder fails when the output path is not absolute.

**Steps to reproduce**

Run master branch with `-a universal` and specifying a relative path.

```
nativefier -p osx -a universal google.com example
```

**Expected behavior**

It works.

**Actual behavior**

It throws an error.
`Error: Expected opts.x64AppPath to be an absolute path but it was not`
This does not happen when specifying an absolute path.

**Suggested solution**

Check if the output path is absolute. If not, use `process.cwd()` and prefix the path with it.

**Context**

 - Nativefier: master
 - Node.js: v16.13.0
 - Npm: 8.5.5
 - OS: MacOS 12.3.1

**Comment by ronjouch** [comment]
@TheCleric
