### ISSUE TITLE
Mavericks is apparently not supported after all ..?!

### ISSUE THREAD

**Issue by JackCico** [nativefier/nativefier#1404]
- [ x ] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [ x ] I searched existing issues, open & closed. Yes, my question is new.
- [ x ] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

I tried to create a macOS nativefier app for Mavericks 10.9.5. Apparently this works only with Electron version up to 3.1.13, because from v4.x I get the message that macOS 10.10 is required.  But I can't work with Electron 3.1.13 because then various Javascript executions of the stored website lead directly to error messages when starting the app.

![image](https://user-images.githubusercontent.com/103328918/165356875-32988e6e-f997-4227-ac1a-d32912236492.png)
![image](https://user-images.githubusercontent.com/103328918/165356899-2ed90f18-3c5d-4cfc-8a88-0dd812ec36ef.png)

Am I doing something wrong to use more recent Electron versions in Nativefier so that you don't get the message about the macOS 10.10 minimum requirement _or_ would it make more sense to increase the minimum requirement for Nativefier, away from the 10.9+ specification? ;))

kindest regards, Jack

**Comment by ronjouch** [comment]
> would it make more sense to increase the minimum requirement for Nativefier, away from the 10.9+ specification? ;))

@JackCico yes, thanks for the notice. I just pushed that to our README.

---

That being said, can you please copy-paste the full text of the error partially shown by your second screenshot? This looks like a bug.
