### ISSUE TITLE
How to add more than 1 internal URL?

### ISSUE THREAD

**Issue by Markellas** [nativefier/nativefier#1410]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I searched existing issues, open & closed. Yes, my question is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Your question**

How to add more than 1 internal url?

**Steps to reproduce**

This is what I was trying to do
```
nativefier google.com --name MarkellasBrowser --internal-urls "mail.ru" "github.com"
```

And after entering command, the Nativefier made an app only with 1 internal URL (In this case "mail.ru"). So it didn't contain github.com and opened it in browser.

Please, help!

**Comment by ronjouch** [comment]
Hi! See the doc ( https://github.com/nativefier/nativefier/blob/master/API.md#internal-urls ): the parameter is a regex. Pass a regex that matches your two domain. If you don't know about regexes, follow a tutorial. They're a useful thing to know.
