### ISSUE TITLE
Cant login in google calendar

### ISSUE THREAD

**Issue by Schahramsigi** [nativefier/nativefier#1414]
Hi,
I use nativefier 47.1.3 to use my calendar in google.

 nativefier -p linux -a x64 --disable-context-menu -n google-calendar https://calendar.google.com/

Everything is also going well and nativefier finishes without reporting any errors.
But when I try to login to google I get an error:
[https://postimg.cc/qt7y9qsd](url)
worked fine with previous version.
What am I doing wrong?

5.15.0-33-generic x86_64 * Ubuntu 22.04 * KDE 5.24.4

**Comment by ronjouch** [comment]
See https://github.com/nativefier/nativefier/blob/master/CATALOG.md#google-apps
