### ISSUE TITLE
could you please add to support flash

### ISSUE THREAD

**Issue by redfox100100** [nativefier/nativefier#1416]
Dear sir,

I have an old website used for teach child, the web site use flash to open,sand no one can update the website .so I can only use old computer with windows 7 to open the website.

Could you please add flash support to the app, that I can use new computer with windows 10 to open the Website.

Ihankyou very much.

**Comment by ronjouch** [comment]
My empathies, but no. See https://github.com/nativefier/nativefier/issues/1123#issuecomment-796404738 for context, rationale, and workarounds.
