### ISSUE TITLE
Amazon.com does not seem to work in the built app (Mac)

### ISSUE THREAD

**Issue by jandb1980** [nativefier/nativefier#1421]
**Homework**

- [ x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [ x] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [ x] I searched existing issues, open & closed. Yes, my bug is new.
- [ x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

The top section of Amazon's web page does not display properly in the final built app. It looks like the top section is broken.

**Steps to reproduce**

nativefier --name 'Amazon' --icon '/path/amazon.icns' 'https://smile.amazon.de/' '/path/FinalApp' --inject '/path/site.css' --title-bar-style 'hiddenInset' --tray --bookmarks-menu '/path/amazon.json' --disable-dev-tools --fast-quit --quiet --lang de-DE

**Expected behavior**

After the error-free build process, I expected the app to display the page error-free.

**Actual behavior**

The build process of the app runs flawlessly, yet the Amazon page in the app window looks broken.

**Debug info**

**Context**

 - Nativefier: (47.2.0)
 - Node.js: ( ?)
 - Npm: (8.9.0)
 - OS: (macOS 12.5 Beta (21G5027d))
 - Is it a regression? If yes, what's the last working / first broken version? Maybe version 47.0
 - Additional context: -

**Comment by jandb1980** [comment]
<img width="1371" alt="Bildschirmfoto 2022-05-31 um 22 45 21" src="https://user-images.githubusercontent.com/73630846/171281474-3bf54c0c-b7bc-4bb3-a83e-376c1fe7c52d.png">

**Comment by BastelPichi** [comment]
Why are you adding extra css? May this be the issue?

**Comment by jandb1980** [comment]
I have removed the CSS code from the build process. After that the header of the app was ok again.

After I added the CSS code unchanged but again to the build process, the header area of Amazon in the app is still ok.

No idea where the problem was now.
