### ISSUE TITLE
Connect-src error while POST Request to external URL

### ISSUE THREAD

**Issue by OctavioSI** [nativefier/nativefier#1433]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I searched existing issues, open & closed. Yes, my question is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Your question**

I am using Nativefier with Notion, so that I can use custom buttons (which I've already implemented as per PR https://github.com/nativefier/nativefier/pull/1430) and perform a number of actions.

Everything works fine with injected JS but POST requests for external pages when I click such injected button, since I am getting a connect-src error. This happens due to browser Content-Security-Policy.
```
Refused to connect to '<EXTERNALAPIURLHERE'> because it violates the following Content Security Policy directive: "connect-src 'self'
```

After some digging, it seem that I would be able to get over it by adding a meta tag such as
```
<meta http-equiv="Content-Security-Policy" content="connect-src 'self' *;">
```

However, the only way I could possibly use this in this setup would by injecting it through JavaScript in Nativefier, such as
```
let meta = document.createElement("meta");
meta.httpEquiv = "Content-Security-Policy";
meta.content = "connect-src 'self' *;";
document.getElementsByTagName('head')[0].appendChild(meta);
```

But this does not work. Since injected JS is run only after DOM is loaded, I believe that any meta tag dynamically injected like this would not be used by the browser/nativefier since it was already read and interpreted before page load.

Is there any workaround this? 

**👉 Edit:**

So after some more digging I was able to change the meta tag loaded by directly editing the resources/app/lib/main.js file. I've searched for "app.on('ready'" in the file and set it like this:
```
	const { session } = require('electron');
	session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
	    callback({ responseHeaders: Object.assign({
		"Content-Security-Policy": [ "default-src * 'unsafe-inline' 'unsafe-eval' data: ; connect-src https://* http://* wss://*;" ]
	    }, details.responseHeaders)});
	});
```
If I limit the domains for connect-src it will show lots of errors due to policy violation in my console and setting it like this fixes that. This means that I was able to successfully change the meta tag related to content-security-policy.

HOWEVER, even though everything seems ok, when I try to call the fetch function in my injected Javascript, I still get the same error:
![screenshot](https://user-images.githubusercontent.com/8326550/177888571-5554152d-5597-4c90-8d0f-b961d950eea1.png)

I wonder whether the page itself restricts the policy to already loaded pages only or something like that.

**👉 Edit 2:**
So, I've found this comments in this repo's issues: https://github.com/nativefier/nativefier/issues/207#issuecomment-733300697

This comment gave me the idea to install a chrome extension which disables CSP (I've tested the extension directly in my chrome browser and it works for the intented purposes: https://chrome.google.com/webstore/detail/always-disable-content-se/ffelghdomoehpceihalcnbmnodohkibj?hl=en-GB). 

To do that I've put the extension files in my /resources/app/lib folder and used the following code in /resources/app/lib/main.js file, inside onReady function:

```
async function onReady() {
    // extensions
    const path_1 = __importDefault(__webpack_require__(14));
    await electron_1.session.defaultSession.loadExtension(path_1.default.join(process.cwd()+"/resources/app/lib/chrome-csp-disable-master"));
...
```

It seems the extension was indeed installed in my Nativefier app, but the error is still there. *Sigh*

**Context**

 - Nativefier: 47.2.1
 - Node.js: 14.5.0
 - Npm: 6.14.5
 - OS: Linux PopOS 22.04 LTS
 - Additional context: (for example: "I'm behind a proxy, with configuration X and protocol Y")

**Comment by OctavioSI** [comment]
So, after A LOT of trial and error and a bit of reading on electron documentation, I was finally able to pull it off. \o/

In order to execute a request to an external URL bypassing the CSP rules used by Notion I had to edit the resources/app/lib/main.js file of my Nativefier app and insert the following line where the app was not ready yet:

```
...
electron_1.app.on('open-url', (event, url) => {
    log.debug('app.open-url', { event, url });
    event.preventDefault();
    if (mainWindow) {
        mainWindow.webContents.send('open-url', url);
    }
});
electron_1.protocol.registerSchemesAsPrivileged([ { scheme: 'https', privileges: { bypassCSP: true } } ]); // this is the line
```
I hope this helps someone (or even me) in the future.

**Comment by kyr0** [comment]
I also needed:

```ts

async function onReady() {
        // Warning: `mainWindow` below is the *global* unique `mainWindow`, created at init time
        mainWindow = await (0, mainWindow_1.createMainWindow)(
          appArgs,
          setDockBadge
        );

        // add this code:
        mainWindow.webContents.session.webRequest.onHeadersReceived(
          (details, callback) => {
            callback({
              responseHeaders: Object.fromEntries(
                Object.entries(details.responseHeaders).filter(
                  (header) => !/x-frame-options/i.test(header[0])
                )
              ),
            });
          }
        );

```
