### ISSUE TITLE
Bug of the Fortnite Mod Menu

### ISSUE THREAD

**Issue by liamrosenbohmde** [nativefier/nativefier#1435]
I downloaded the Fortnite mod menu and completed the verification (Opera-GX downloaded) and I didn't get the mod menu.

**Comment by ronjouch** [comment]
Please provide the info requested by our [bug report issue template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Quoting its first three lines:

```
Help us help you, please take the time to fill this information 🙂.
An incomprehensible bug report is a useless bug report.
Incomprehensible / incomplete bug reports will be closed.
```

With that, closing, but will re-open if you find the time to bring details.
