### ISSUE TITLE
HOW CAN I SET show-menu-bar Languages?

### ISSUE THREAD

**Issue by onlyscv** [nativefier/nativefier#1444]
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md).
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my question is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases).

### Your question

i am in china,
when i set show-menu-bar:true.
menubar show,but it's english.
how can i set it to chinese？

![QQ截图20220803142718](https://user-images.githubusercontent.com/33649764/182539202-647e6691-a951-4ccd-9aa7-009d4670a8cd.png)

### Steps to reproduce

```
nativefier --verbose --some-option https://mysite.com
<paste your verbose build logs, if relevant to your question>
```

### Nativefier version

49

### Node.js version

16.14.0

### npm version

8.3.1

### OS

windows

**Comment by ronjouch** [comment]
Nativefier doesn't support localization.

Note that you can hide the menu bar with `--show-menu-bar=false`
