### ISSUE TITLE
External links open twice on messenger.com

### ISSUE THREAD

**Issue by mbesemann** [nativefier/nativefier#1452]
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md).
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my bug is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases).

### Nativefier command

sudo nativefier --name "Messenger" https://messenger.com

### Steps to reproduce

1. Open Messenger
2. Click on an external link in a conversation

### Expected behavior

Only one tab should open in the browser, and no blank tabs should be created in Nativefier.

### Actual behavior

A new blank tab is opened in the Nativefier app, as well as 2 tabs in the default browser pointing to the linked URL.  Perhaps conflicting with existing Facebook JS?

### Debug info

<img width="847" alt="Screenshot 2022-08-15 at 1 23 23 PM" src="https://user-images.githubusercontent.com/42157326/184684453-5e7b5e5e-b6c9-4ec0-9a94-f8061f02148f.png">
<img width="240" alt="Screenshot 2022-08-15 at 1 23 42 PM" src="https://user-images.githubusercontent.com/42157326/184684551-12e52584-2178-4a0c-b61c-e432d6ce5921.png">

### Nativefier version

49.0.0

### Node.js version

v16.14.2

### npm version

8.17.0

### OS

macOS Ventura beta 5

**Comment by ronjouch** [comment]
Thanks! Should be fixed in eecc33c1aa6a84efb5b850682de58289028c50c5, released in v50.0.0
