### ISSUE TITLE
Add ability to specify `thickFrame` Window option.

### ISSUE THREAD

**Issue by RickyGrassmuck** [nativefier/nativefier#1453]
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md), no existing option fits my needs.
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my feature request is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases). Yes, the feature I'm requesting isn't in it.

### Problem statement

Nativefier should expose the `thickFrame` window option to facilitate using a more compact title bar.

### Motivation & context

In my use case, there is no header to coerce into being a "title bar" on the site I'm building the application for and I'd just break things trying to inject something to make one. 

I have provided a screenshot showing below showing the size difference the option makes and find having the compact version appealing enough to not even worry about hacking together a frameless solution.

![image](https://user-images.githubusercontent.com/17223437/185573880-45958ff6-1003-4ff3-9f3e-0c33c757a123.png)

I just finished up properly adding the ability to build apps with this option to nativefier and will be opening a PR should y'all find this potentially useful!

**Comment by RickyGrassmuck** [comment]
Annnnndddd I just stumbled across the `--browserwindow-options` flag. Must have read past it the first few time's I was reading through the options.

I'll leave the PR and this request up though as there are a few examples of flags modifying things that could be done through `--browserwindow-options` already and having a dedicated flag for this option may make it easier for people to find this feature.

**Comment by ronjouch** [comment]
> Annnnndddd I just stumbled across the `--browserwindow-options` flag. Must have read past it the first few time's I was reading through the options.

🙂

> I'll leave the PR and this request up though as there are a few examples of flags modifying things that could be done through `--browserwindow-options` already and having a dedicated flag for this option may make it easier for people to find this feature.

This issue will remain searchable even if closed. With that, closing and closing the PR.
