### ISSUE TITLE
Setting up Nativefier on my personal computer 

### ISSUE THREAD

**Issue by shuklavk** [nativefier/nativefier#1455]
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md).
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my question is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases).

### Your question

Hello. I wanted to play around with the nativefier code on my personal computer (Linux), and was following the steps on Hacking.md . I have done all the steps up till 

```
npm link
which nativefier
```

But I am not getting "/home/youruser/.node_modules/lib/node_modules/nativefier"

instead getting "/usr/local/bin/nativefier"

The comments say "If not, be sure your `npm_config_prefix` env var is set and in your `PATH`" but I am more on the new side of programming + electron so not fully sure what this means. 

Does this mean to put this variable in the .env file? and which PATH is it referring to? 

Thank you in advance!

### Steps to reproduce

```
which nativefier
```

### Nativefier version

49.0.0

### Node.js version

v12.22.9

### npm version

8.5.1

### OS

Linux Ubuntu 22

**Comment by BastelPichi** [comment]
To my knowledge this shouldnt be a problem. However try simply adding e.g. a hello world to the code, and run it to see if that works. 
Best regards
