### ISSUE TITLE
Create GitHub Action

### ISSUE THREAD

**Issue by marshalmiller** [nativefier/nativefier#1456]
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md), no existing option fits my needs.
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my feature request is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases). Yes, the feature I'm requesting isn't in it.

### Problem statement

This feature would allow you to add Nativefier into the pipeline cycle and produce packages for your repository. Pipelines allow you to build on Linux and Windows. So I assume this would work. Perhaps it would be limited to Linux packages. I know NPM can run on GitHub Actions. This would be a simple config file/recipe that users could add to their deployment process.

### Motivation & context

I love Natiefier, but it would greatly improve my CI/CD process if I could include it in my pipeline as a process. I think it would allow many users to add usable packages to their repository, making the app more accessible for some.

**Comment by BastelPichi** [comment]
If you mean to automatically package Websites:
As nativefier files are usually 250-300mb big, this doesn't make too much sence. However I have an repo here that gets the size down to 90mb by double zipping it. Feel free to fork and modify the config.json, should be self explaining.
[https://github.com/BastelPichi/nativefier-automatic-spotify/](https://github.com/BastelPichi/nativefier-automatic-spotify/)

The executables built work.

Else I spent two hours lol
Hope this is helpful!

**Comment by marshalmiller** [comment]
@BastelPichi so your workflow can be adapted so that when I push a new release of my Flask app, it will read the config.json file and create builds based on your action parameters?

**Comment by Randomblock1** [comment]
It would be convenient, but really it's not that hard. You just tell Actions to install and then run Nativefier. That's it.
Anyway, here's my action that automatically builds and 7zips everything on all platforms. The Linux 7z is only 56 mb. You just need to set up an npm run script, look at my `package.json`.

https://github.com/Randomblock1/messages4desktop/blob/master/.github/workflows/build.yml

**Comment by ronjouch** [comment]
Looks like you got the help you needed 🙂. With that, closing.
