### ISSUE TITLE
create a exe file instead a batch of files

### ISSUE THREAD

**Issue by arcanisgk** [nativefier/nativefier#1457]
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md), no existing option fits my needs.
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my feature request is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases). Yes, the feature I'm requesting isn't in it.

### Problem statement

is posible create one file only inteas a batch of files?

### Motivation & context

![image](https://user-images.githubusercontent.com/1207306/186753524-da08d1fa-aed3-4f61-9da1-6ae7e1227a7f.png)

**Comment by ronjouch** [comment]
Hi @arcanisgk . No this is not possible, and is out of our reach. Feel free to search/ask upstream in Electron issues.
