### ISSUE TITLE
Critical Vulnerability

### ISSUE THREAD

**Issue by Retr02332** [nativefier/nativefier#1459]
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md).
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my question is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases).

### Your question

Hi Nativefier team !!

Do you have a secure/private contact where I can send a security report?

Regards.

### Steps to reproduce

0

### Debug info

0

### Nativefier version

0

### Node.js version

0

### npm version

0

### OS

0

**Comment by ronjouch** [comment]
@Retr02332 maintainer here. Sure, pls send details to the email you'll find in any commit I pushed to the repo, e.g. https://github.com/nativefier/nativefier/commit/be2180b53f6887c48f81caf2713ae55b38191a89.patch .

**Comment by Retr02332** [comment]
@ronjouch Perfect, I just sent you the vulnerability details to your email.

**Comment by winteriscariot** [comment]
I just clicked a link in my nativefier app and it wouldn't open it and referred me to this issue. Why?

How can I disable validating URLs? I don't want this behavior and I understand the risks that I may be taking.

**Comment by winteriscariot** [comment]
note: I have "--internal-urls "(.*)"" when building the app, but it should still open the URL in an internal browser window

**Comment by winteriscariot** [comment]
The domain that was blocked was https://outlook.office365.com -- hardly a malicious site. Links to github.com open without issue.

I'd ideally not like *any* validation happening.

**Comment by ikiK-CRO** [comment]
Hi, I also have a problem that leads me here, I have a web app that has a button to generate  .ics files for Outlook and iCalendar events. Download/generate of those is blocked and I don't see anywhere in the API anything I can do to help myself. 

Note: I have download options enabled and they work on other parts of the app. 
<img width="767" alt="Screenshot 2023-04-04 at 20 29 20" src="https://user-images.githubusercontent.com/25029344/229885989-dd0afcef-ae38-41ee-94fd-b8efdffed447.png">

Please advise.

**Comment by mlscherer** [comment]
Hello! Just found a message directing me to here...

"Navigation blocked to qz:launch
URL protocol is disallowed. If you believe this URL should open, you might be right, and our
validation mignt be excessive. Please share this error & URL at https://github.com/nativefier/nativefier/issues/1459"

we use QZ Tray, which is a well-known and used print management app and I believe that Nativefier should not block this...
