### ISSUE TITLE
Unable to install nativefier, ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/nativefier/lib/cli.js'

### ISSUE THREAD

**Issue by Buster14** [nativefier/nativefier#1473]
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md).
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my bug is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases).

### Nativefier command

npm install -g nativefier

### Steps to reproduce

At first I installed using the command above, but I admit since it took like 15 minutes I CTRL+C i thought there was connections issue.
Then i try again but i got above error

### Expected behavior

nativefier installed

### Actual behavior

```
root@ViewingStation:/home/aio# npm install -g nativefier
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /usr/local/lib/node_modules/nativefier/lib/cli.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/nativefier/lib/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-22T01_46_58_460Z-debug.log
```

### Nativefier version

v50

### Node.js version

12.22.12

### npm version

7.5.2

### OS

debian 11

**Comment by Buster14** [comment]
Ok I've tried deleting the nativefier folder, but upon installing again i got this error, even with allow root it doesnt help

```
root@ViewingStation:/usr/local/lib/node_modules# rm -rf nativefier/
root@ViewingStation:/usr/local/lib/node_modules# npm install -g nativefier
npm WARN deprecated electron-osx-sign@0.5.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/nativefier/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Error: EACCES: permission denied, stat '/root/.cache/electron/5b3fdb6354d4b2210afd2202f8499027ea141b40bb9ab0374ce41f7ae3c0bee4/electron-v19.0.17-linux-x64.zip'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-22T02_35_16_868Z-debug.log
root@ViewingStation:/usr/local/lib/node_modules# ls
root@ViewingStation:/usr/local/lib/node_modules# npm install -g nativefier --unsafe-perm=true --allow-root
npm WARN deprecated electron-osx-sign@0.5.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/nativefier/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Error: EACCES: permission denied, stat '/root/.cache/electron/5b3fdb6354d4b2210afd2202f8499027ea141b40bb9ab0374ce41f7ae3c0bee4/electron-v19.0.17-linux-x64.zip'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-22T02_39_31_139Z-debug.log
```

**Comment by TheCleric** [comment]
Are you running this as root purposefully?

**Comment by Buster14** [comment]
Geez, didn't know it was that simple.
I'm not used to linux yet so i thought installing apps always need root.
Thanks it's working now.
