### ISSUE TITLE
How to open a file with nativefier application

### ISSUE THREAD

**Issue by furkankrcl** [nativefier/nativefier#1479]
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md).
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my question is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases).

### Your question

I want to open a file (for example: exp.csv, exp.jpg etc.) in the application I created with Nativefier.
How can I determine that I started the application with a file?
For example: When I start a Office.Word application, the start page of the application opens, when I say "Open with Office.Word" to an exp.doc file, it brings the exp.doc file to the Office.Word application as processed.

Similar to this example, I want to send my related file to the API I prepared in order to be able to process it.

Is it possible to do this with Nativefier?

Step 1) Right click on a csv file.
Step 2) Open file with my nativefier app.
Step 3) nativefier app uploads the file to a server.
Step 4) The server's forwarding link in the response is opened with the nativefier application.

### Nativefier version

50.0.0

### Node.js version

v16.15.1

### npm version

8.11.0

### OS

Windows 11 Pro

**Comment by emregeldegul** [comment]
Do you have any suggested solution?
