### ISSUE TITLE
可以帮忙打包一个软件吗？

### ISSUE THREAD

**Issue by hht2009** [nativefier/nativefier#1498]
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md).
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my question is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases).

### Your question

链接：https://hht.icu/
站点名：HhtNav
试了好多次都没成功
windows和Mac版，谢谢！

### Steps to reproduce

```
nativefier --verbose --some-option https://mysite.com
<paste your verbose build logs, if relevant to your question>
```

### Nativefier version

1

### Node.js version

1

### npm version

1

### OS

1

**Comment by TheCleric** [comment]
Unfortunately we can not respond to issues without a fully filled out report. As well none of our developers speaks Chinese, so English bug reports would be preferred.
