### ISSUE TITLE
Can JS execute shell commands , if it is in nativefier?

### ISSUE THREAD

**Issue by NerdsForGaming** [nativefier/nativefier#1505]
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md).
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my question is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases).

### Your question

I am currently trying to make a desktop app , but i am lazy so i made it in html , i have a JS script that executes  some shell commands , if i nativefiy that webstie , would i be able to use that JS script and execute shell commands?

### Steps to reproduce

not a nativefier error

### Nativefier version

50.0.1

### Node.js version

v10.19.0

### npm version

ignore

### OS

Zorin os 16.1

**Comment by arjankuijpers** [comment]
With C and C++ you can do everything, so one solution is to make a C++ function for what you want to achieve see: https://www.electronjs.org/de/blog/from-native-to-js

**Comment by NerdsForGaming** [comment]
Alright thanks!
