### ISSUE TITLE
Stuck on Cloudflare browser check loop

### ISSUE THREAD

**Issue by slithery0** [nativefier/nativefier#1510]
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md).
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my bug is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases).

### Nativefier command

nativefier 'https://doge.click/vc/qmZ7bj' --name doge

### Steps to reproduce

I am having trouble with cloudflare verification. I tried various useragent flags, i guess that created no difference. Have anyone managed to bypass cloudflare check?

### Expected behavior

Should just pass the check right?

### Actual behavior

Went on a loop with same verification page, constanty reloading.

### Nativefier version

50.0.1

### Node.js version

16.19.0

### npm version

8.19.3

### OS

Arch Linux x86_64

**Comment by hxvy0** [comment]
because of invaild ssl 😂
![image](https://user-images.githubusercontent.com/85783692/221240615-77f98119-f785-4784-91a5-91c24d9ab1ac.png)

**Comment by slithery0** [comment]
No, I am stuck here. It keeps reloading.
I checked other website with Cloudflare browser verification enabled, evey website i tested does the same. Cant get in at all.
![image](https://user-images.githubusercontent.com/39809189/221260321-caf90fb3-536b-4be5-b4b5-5d80d04d6200.png)

**Comment by hxvy0** [comment]
> No, I am stuck here. It keeps reloading. I checked other website with Cloudflare browser verification enabled, evey website i tested does the same. Cant get in at all. ![image](https://user-images.githubusercontent.com/39809189/221260321-caf90fb3-536b-4be5-b4b5-5d80d04d6200.png)

bro bcs of invaild ssl, site cannot load bcs of invaild ssl

**Comment by slithery0** [comment]
> > No, I am stuck here. It keeps reloading. I checked other website with Cloudflare browser verification enabled, evey website i tested does the same. Cant get in at all. ![image](https://user-images.githubusercontent.com/39809189/221260321-caf90fb3-536b-4be5-b4b5-5d80d04d6200.png)
> 
> bro bcs of invaild ssl, site cannot load bcs of invaild ssl

try nativifying [chatgpt](https://chat.openai.com/) url which have cloudflare browser check feature enabled, it wont let you pass through.
