### ISSUE TITLE
poooooooooon

### ISSUE THREAD

**Issue by Keni0lez** [nativefier/nativefier#1521]
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md).
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my bug is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases).

### Nativefier command

p

### Steps to reproduce

p

### Expected behavior

p

### Actual behavior

p

### Debug info

p

### Nativefier version

p

### Node.js version

p

### npm version

p

### OS

p

**Comment by TheCleric** [comment]
Closing as incomplete/spam.
