### ISSUE TITLE
Add support for electron-ad-blocker

### ISSUE THREAD

**Issue by PhantomNimbi** [nativefier/nativefier#1532]
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md), no existing option fits my needs.
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my feature request is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases). Yes, the feature I'm requesting isn't in it.

### Problem statement

I would like to see an optional flag for adding support for `electron-ad-blocker` into nativefier app(s).

### Motivation & context

This would be extremely useful for blocking ads in nativefier apps since a lot of websites tend to be a bit excessive with ads.

An example of a possible flag option would be `--ad-blocker-enabled`

You can find electron-ad-blocker at the following github repository: [Jense5/electron-ad-blocker][url]

[url]: https://github.com/Jense5/electron-ad-blocker

**Comment by digitalextremist** [comment]
Agreed on this issue, but seems solvable this way: https://github.com/nativefier/nativefier/issues/207

Then any extension, including those for ad blocking, can be added.

**Comment by PhantomNimbi** [comment]
> Agreed on this issue, but seems solvable this way: https://github.com/nativefier/nativefier/issues/207
> 
> Then any extension, including those for ad blocking, can be added.

Unfortunately, that won't quite work. As is stated in that post, injecting ad blocking extentions fails due to them requiring the `chrome.` browser apis which aren't available in Electron.

**Comment by TheCleric** [comment]
That library (electron-ad-blocker) hasn't been updated in 5 years and according to their open issues, doesn't look like it has worked since Electron 4.0.
