### ISSUE TITLE
Support specifying language/locale

### ISSUE THREAD

**Issue by jmalarcon** [nativefier/nativefier#175]
Hi:

Congratulations for this great app...

Some web apps automatically adapt its UI to the current user language.
With the current Nativefier app the default language is English, but if you want to use an specific language (i.e., Spanish or German) as the default it would be very useful. Maybe with a simple switch such as:

`--user-language es-ES`

for example.

Thanks and keep the good work!.

**Comment by jiahaog** [comment]
Hi there, yeap this is possible. Would you like to work on a pull request?

**Comment by jmalarcon** [comment]
Hi:

I'd love to do it, but I'm afraid I can't do it. I'm not an expert in this technology at all. Sorry :-S

I was just suggesting it as an enhancement.

Thanks.

**Comment by TheCleric** [comment]
@jmalarcon to get an idea of what you would expect out of a feature like this, what effect would you want this to have? The page you're running in Nativefier would act as if a browser under that locale would act?

**Comment by jmalarcon** [comment]
Hi @TheCleric Yes, that's exactly it. The application I'm interested in "nativify" adapts it's interface automatically to the browser preferred language and it would be very interesting being able to set it when "compiling" with nativifyer.

Thanks!

**Comment by TheCleric** [comment]
This wasn't actually possible until recently (https://github.com/electron/electron/issues/5649), but seems doable now!
