### ISSUE TITLE
Session not saved for Google Apps sites via Okta 

### ISSUE THREAD

**Issue by jweinstein** [nativefier/nativefier#259]
### Description

I have to log in to Google Apps via Okta.  Sadly, I have it doesn't maintain the session info between app starts and I have to re-login. :(
### Steps to Reproduce Issue

Using `nativefier https://calendar.google.com`
Open App
Log in to Google Apps via Okta
Exit App
Open App, have to log back in :(
### Specifications

Latest everything on Mac 10.11

**Comment by ibnbd** [comment]
I am having the same issue with my app :(

**Comment by suparng-medallia** [comment]
I have the same issue. :(

**Comment by TheCleric** [comment]
@jweinstein (or @ibnbd) I know this is an older issue, can you confirm if this is still an issue in the current version of Nativefier?

**Comment by TheCleric** [comment]
Closing as I have not heard a response back. We can reopen if anyone is still experiencing this.
