### ISSUE TITLE
Google Inbox doesn't maintain login

### ISSUE THREAD

**Issue by ericbiewener** [nativefier/nativefier#261]
### Description

I'm referring to https://inbox.google.com

The resulting app always requires me to log back in. As a workaround, Inbox has an option to automatically redirect you from Gmail to Inbox. So I can turn that setting on, then build a Gmail app in nativefier, and it successfully logs in each time and redirects me to Inbox.
### Steps to Reproduce Issue
1. `nativefier https://inbox.google.com`
2. open app and log in
3. close app, then reopen
### Specifications
- Version of Nativefier: 7.0.1
- Version of Node.js: 4.2.1
- OS: OS X 10.11.6

**Comment by abovethewater** [comment]
Same issue here - great workaround, thanks.

To get it to work I had to first set the setting not to redirect to Inbox, create the app, then set the setting once logged into the native app.

**Comment by TheCleric** [comment]
@ericbiewener can you confirm if this issue still exists in the current version of Nativefier?

**Comment by ericbiewener** [comment]
4 years later... Inbox isn't even a product anymore!
