### ISSUE TITLE
Support notifications under Windows ≤ 7 (probably through Electron ≥ 1.6.7 support through brightray)

### ISSUE THREAD

**Issue by LupusUmbrae** [nativefier/nativefier#294]
### Description
Just wondering if there is a way to modify the output to include the [notification shim](https://github.com/seriema/electron-notification-shim) so this can support notifications on Windows 7? As at the moment Electron does not appear to support Notifications on Windows <= 7, despite them working in Chrome/Firefox :(

Sadly i'm brand new to Electron and have no idea how to do the necessary steps from the notifications shim page, but i would assume that i need to add the requires to a step before creating the output to include it?

Hopefully you have some ideas or pointers on doing this.

### Steps to Reproduce Issue
Create a native webpage and try to create a notification, easiest way i found was to just manually try and create a Notification:

```javascript
new Notification("hi")
```

### Specifications
- Version of Nativefier: `v7.0.1`
- Version of Node.js (run `$ node --version`): `v4.3.0`
- OS: `Windows 7`
- Architecture `64Bit`

**Comment by ronjouch** [comment]
@LupusUmbrae thanks for the report. The [electron docs](https://github.com/electron/electron/blob/master/docs/tutorial/desktop-environment-integration.md#windows) say:

> *On Windows 7, notifications are not supported. You can however send "balloon notifications" using the [Tray API](https://github.com/electron/electron/blob/master/docs/api/tray.md#traydisplayballoonoptions-windows).*

If someone want to start working on this, maybe these balloon notifications could do the trick too.

**Comment by ronjouch** [comment]
Good news! [Electron 1.6.7 beta](https://github.com/electron/electron/releases/tag/v1.6.7) *"added support for notifications on Windows 7: https://github.com/electron/electron/pull/9168 , https://github.com/electron/electron/issues/8384"*, obviating the need for a third-party module. Worth looking at!

**Comment by TheCleric** [comment]
@LupusUmbrae it looks like this is a pretty old issue, and since then Electron's support of Windows 7 notifications have improved. Can you confirm if this is still an issue?

**Comment by TheCleric** [comment]
Closing as I have not heard a response back. We can reopen if anyone is still experiencing this.
