### ISSUE TITLE
Setting platform=darwin along with arch=ia32 fails silently, should warn

### ISSUE THREAD

**Issue by humphd** [nativefier/nativefier#301]
I'm not sure whose bug this is (upstream or here), but since I hit it in nativefier, I'll start by filing it here and you can advise me.  I wanted to package a 32-bit OS X Electron app, and set `arch='ia32'` and `platform='darwin'`.  Nativefier gets 61% into the process (i.e., in `packaging`) and then just stops, with no error, and no built output.

In the debugger I can see it silently skipping my combination here in `electron-packager`:

```js
  var combinations = []
  archs.forEach(function (arch) {
    platforms.forEach(function (platform) {
      // Electron does not have 32-bit releases for Mac OS X, so skip that combination
      if (common.isPlatformMac(platform) && arch === 'ia32') return // <--------- here
      combinations.push(common.createDownloadOpts(opts, platform, arch))
    })
  })
```

The comment above that code is really useful, and it would be nice to up-level it to the user in the form of a warning, perhaps responding to the `darwin + ia32` combo even before the app runs.  It's not obvious that it just has nothing to do, since there is no Electron support for this combo.

**Comment by ronjouch** [comment]
@humphd thanks for the report 👍, good catch! We're resuming maintenance of nativefier and we have lots to do. So if you have the time for that, a PR will be most welcome.

**Comment by TheCleric** [comment]
I'm looking through older issues, and am retesting this one (over 4 years later), and we must be doing something better, because I not see we show this when trying to do an invalid combination (such as Mac + ia32):

> Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
> WARNING: The platform/arch combination darwin/ia32 is not currently supported by Electron Packager

Is this along the lines of what you were originally looking for @humphd ?

**Comment by humphd** [comment]
@TheCleric that sounds good, yes.  If that's the case now, then this is closable.
