### ISSUE TITLE
--counter does not work with Facebook

### ISSUE THREAD

**Issue by kcampion** [nativefier/nativefier#302]
### Description
I made a native wrapper for facebook.com with the --counter option. The titles of Facebook have (X) Facebook, but nothing happened when I receive a notification. 

### Steps to Reproduce Issue
```
$ nativefier --counter --disable-dev-tools --name "Facebook" "https://www.facebook.com"
```

### Specifications
- Version of Nativefier: `v7.0.1`
- Version of Node.js: `v6.7.0`
- OS: `MacOs Sierra 10.12.1`
- Architecture `x64`

**Comment by nansthomas** [comment]
I have the same problem ! Do you fix it ?

**Comment by ronjouch** [comment]
Hey @kcampion @nansthomas, https://github.com/jiahaog/nativefier/pull/256 was recently release as part of Nativefier 7.1.0, could you try it and see if `--counter` works now? Thanks :)

**Comment by kcampion** [comment]
The problem seems to be always here @ronjouch after updating Nativefier and regenerated the app.

**Comment by TheCleric** [comment]
@kcampion I feel like an absolute jerk for asking this, but I don't have a Facebook account to verify this myself, but can you confirm if this still occurs in the latest version of Nativefier?

**Comment by TheCleric** [comment]
Closing as I have not heard a response back. We can reopen if anyone is still experiencing this.
