### ISSUE TITLE
Proactively tell about Nativefier options/version and Electron version at app build time, in order to improve discoverability

### ISSUE THREAD

**Issue by ronjouch** [nativefier/nativefier#336]
First, a lot of issues are feature requests already present in nativefier as options, but user don't know about them.

Second, a lot of issues are about using old Electron versions. A fix is of course to release frequently with recent electron versions, but it only goes so far (doesn't cover users on old versions of Nativefier), so I think we should put give some emphasis to `--electron-version`.

I propose we add a little text popping up at app build time encouraging users to have a look at them. It would look like this:

```bash
~ nativefier -e 1.6.6 --name "gmail" "https://mail.google.com/mail"
Nativefier has many optional features you might like, run nativefier --help for the full list.
In particular, use --electron-version to pick your electron/chrome version!
Check you're asking for a recent one at https://github.com/electron/electron/releases
[ ... existing output]
```

---

EDIT 2017-04-19: In addition to *mentioning* `use --electron-version to pick your electron/chrome version`, since we're making network requests anyway to get the electron version list for useragent setting, we could explicitly say `Building with Electron a.b.c, but a.b.f is available. Use --electron-version to pick your electron/chrome version!`.

Note: I guess we don't want to dynamically/automatically use the last version, that would introduce non-deterministic behavior and may make troubleshooting more painful by putting us *too much* at Electron's bleeding edge.

Thoughts?

**Comment by jiahaog** [comment]
@ronjouch I think it's a little obvious to tell the user to check `nativefier --help`, but it's definitely a good idea to print the latest electron version there! Also, it would be great if we could print something telling them that they are using a outdated version of nativefier, or other useful things that they might want to know!

**Comment by ronjouch** [comment]
> *"I think it's a little obvious to tell the user to check `nativefier --help`, but it's definitely a good idea to print the latest electron version there! Also, it would be great if we could print something telling them that they are using a outdated version of nativefier, or other useful things that they might want to know!"*

@jiahaog good point for the outdated nativefier, I'll consider it.

And regarding telling/encouraging to check `nativefier --help`, it's an idea I got after my big issue triage, which led me to think it's not so obvious for many users. Will keep it short when I work on it, and will submit output examples that we can discuss.

**Comment by themidnightfox** [comment]
@ronjouch: I would prefer defaulting to the use of the latest stable electron version (which should be the version with the least bugs and security leaks). In the case the newest version introduces bugs nativefier has the option to set a custom (older) electron version making sure the user has something to fall back to.

This is why:
I don't follow electron releases so expecting me to specify electron releases forces me to make decisions I am not fit to make (I also happen to be lazy ^^) and where nativefier (in my case) made the lesser choice by default. An app was failing me and my default behaviour (rebuilding the app with nativefier after updating nativefier) did not fix it as I did not specify an electron version.

Annother idea:
If a commandline setting is optional, I expect software to use sane defaults, so if you want users to look into the options and choose please make the setting required (in this case the -e|--electron-version option).

**Comment by TheCleric** [comment]
@ronjouch do we feel like this is still needed 4ish years later?

**Comment by ronjouch** [comment]
> @ronjouch do we feel like this is still needed 4ish years later?

@TheCleric 👍, our options section-ification & two-layers-ification will better address this.
