### ISSUE TITLE
Clicking on app-emitted notification fail to focus nativefied app

### ISSUE THREAD

**Issue by maheshprabhu2010** [nativefier/nativefier#396]
### Description

I am getting push notifications from my application and when I click on the notification, minimized application will be loaded and visible. But in Nativefiered application, when clicked on the notification, nothing happens.

### Specifications
Version of Nativefier (run $ nativefier --version): v7.4.0
Version of Node.js (run $ node --version): v6.10.3
OS: Windows 10
Architecture: 64 Bit

**Comment by apersonnamedmike** [comment]
I'm also getting this issue

**Comment by TheCleric** [comment]
I'm assuming this was fixed in #640 

If this issue is still present, we can reopen. 😄
