### ISSUE TITLE
--internal-urls examples

### ISSUE THREAD

**Issue by digiltd** [nativefier/nativefier#530]
### Description

I am unable to get `--internal-urls` to do what I think it is meant to do

I am trying to create a native version of an internal tool that we use, I want to be able to open "internal tool" related links within the packaged app (e.g. "new ticket", "home", "contact directory" will take you to the relevant pages in the app). But I want external urls to open in a browser, so if for example a ticket contains a link to a client's site or a github pr, it will open in the default browser. 

I have tried various types of formatting for the regex, but nothing seems to work

`nativefier --internal-urls "*.subdomain.theservice.com" --icon assets/icon.icns subdomain.theservice.com`

`nativefier --icon assets/icon.icns --internal-urls '/(\subdomain.theservice)/g' subdomain.theservice.com`

`nativefier --icon assets/icon.icns --internal-urls '/(\subdomain.theservice)' subdomain.theservice.com`

`nativefier --icon assets/icon.icns --internal-urls 'subdomain.theservice' subdomain.theservice.com`

`nativefier --icon assets/icon.icns --internal-urls subdomain.theservice subdomain.theservice.com`

am I missing something obvious?

**Comment by digiltd** [comment]
I wasn't missing anything, though I was using it wrong... well, my assumptions of how it worked was wrong.

`--internal-urls` only works on links that use `target="_blank"` 

There are lots of posts about internal urls (like [this one](https://github.com/jiahaog/nativefier/issues/23#issuecomment-173915175)), but nothing conclusive.

----

(will make a pr for the docs at some point, but for now here is a rundown of how (I think) it works)

Standard links open in the same Electron window

`<a href="https://bbc.co.uk">The BBC</a>`

`<a href="https://reddit.com">Reddit</a>`

Links with target set to blank will open in a new Electron window.

`<a href="https://bbc.co.uk" target="_blank">The BBC in a new window</a>`

`<a href="https://reddit.com" target="_blank">Reddit</a>`

By defining internal urls you can control which open in an Electron window and which open in your default browser.

`--internal-urls 'bbc.co.uk'`

Using the same example, BBC will open in Electron and Reddit will open in Chome (or whatever the default is)

**Comment by ronjouch** [comment]
We've since improved `--internal-urls` with automatic recognizing of common login pages, and improved the documentation to clarify what's going on with example. With that, closing.
