### ISSUE TITLE
Cant login into Native version of Medium.com

### ISSUE THREAD

**Issue by guppythegod** [nativefier/nativefier#644]
### Description

I can't seem to sign in to the native version due to the fact that it always logs me in, in my browser.

### Steps to reproduce issue

1. Create a native version of Medium.com
2. Open and click sign in
3. Sign in with gmail
4. Enter in the correct account and password

### Details

- Are you nativefying a *public* website?
yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
yes
- Full nativefier command used to build your app: nativefier --name "Medium" "https://medium.com"
- Version of Nativefier (run `nativefier --version`): 7.6.4
- Version of node.js (run `node --version`): 8.11.1
- OS: Windows 10
- Error message / stack trace (if any):
N/A

**Comment by Shane98c** [comment]
This same issue occurs for me with other apps where the sign in is handled externally to the site.  My institution's G-Suite login system is the most recent example of this issue.

**Comment by mattruzzi** [comment]
@guppythegod Does this still happen with the latest version of nativefier now that it is aware of third party login pages?

https://github.com/nativefier/nativefier/blob/master/API.md#internal-login-pages

**Comment by ronjouch** [comment]
Thx Matt. Yes I think our auto-internal-login-pages logic fixes this. With that, closing, but anyone feel free to chime in if the problem persists, and I'll reopen.
