### ISSUE TITLE
Cannot run 32bit apps created on 64bit machine with proper --arch flag

### ISSUE THREAD

**Issue by nottiesweather** [nativefier/nativefier#687]
### Description

Cannot run 32bit apps created on 64bit ubuntu machine. (64bit apps work fine).

### Steps to reproduce issue

Ubuntu 18.04 XFCE - installed npm with recommends. Process completes without error but then the executable will not run. Running from terminal shows error "error while loading shared libraries: libgtk-3.so.0" - this is installed.

### Details

- Are you nativefying a *public* website? Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes
- Full nativefier command used to build your app: `nativefier --name "Customweb" --arch "ia32" "https://www.customweb.co.za"`
- Version of Nativefier (run `nativefier --version`): `7.6.7`
- Version of node.js (run `node --version`): `8.10`
- OS: `ubuntu xfce`
- Error message / stack trace (if any):

./customweb: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory

<Error message / Stack trace here>
```

**Comment by ronjouch** [comment]
Closing as 32bit is no longer supported by Electron >=19 / Nativefier 48

**Comment by CentroEducacional-CEC** [comment]
Qual a alternatica para 32bits?

**Comment by ronjouch** [comment]
> Qual a alternativa para 32bits?

Regular Chromium (e.g. compiled by Debian / 32bit-i686) in `--kiosk` mode
