### ISSUE TITLE
Microsoft Office 365 Natifier Apps Open a Separate Window in Default Browser, Refuses to Login in Nativefie-d App.

### ISSUE THREAD

**Issue by jebeld17** [nativefier/nativefier#745]
### Description

Microsoft Office 365 Natifier Apps Open a Separate Window in Default Browser. Once I log into my account on the default browser, the Nativefie-d app still doesn't catch my login information and refuses to load.

### Steps to reproduce issue
1. Download and install latest Node.JS from www.nodejs.org
2. Download and install Nativefier
3. Attempt to create an Office365 Web App in Nativefier - for instance, http://www.onenote.com/
4. Run the Nativefie-d app by double-clicking.

### Details

- Are you nativefying a *public* website?
Yes.
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
N/A
- Full nativefier command used to build your app: `nativefier --name "OneNote" "http://www.onenote.com/"`
- Version of Nativefier (run `nativefier --version`): `v7.6.10`
- Version of node.js (run `node --version`): `v12.0.0-nightly201901218b2e861da1`
- OS: `Ubuntu 18.10 (AMD64); "#14-Ubuntu SMP PREEMPT Wed Dec 5 12:12:14 UTC 2018" + "Linux 4.18.0-13-lowlatency (x86_64)"`

**Comment by jebeld17** [comment]
I believe this may have something to do with the OAuth and the way the Nativefier wrapper handles it.

**Comment by fabioromeo** [comment]
I've managed to login with the followin command: 

> nativefier "https://office.live.com/start/Excel.aspx" --name "Excel Online" --internal-urls "d.docs.live.net|login.live.com|onedrive.live.net|onedrive.live.com"

The problem I'm having is that the app can't open the file for whatever reason. Maybe there's an URL lacking but I couldn't figure out which one yet.

**Comment by danieltomasz** [comment]
I have the same problem, the above command still login in the browser

**Comment by damitti444** [comment]
Hey! I had the same issue, trying to log into youtube music. 
What worked for me was:
- right click the "sign in" - open link in new window
- give email, pw and code etc.. - browser will open (ignore it)
- right click "sign in" again - open link in new window - ...login process continues
- choose account, close all webapp windows
- open up the webapp container again
- works (for me at least)
I hope this helped, as I cannot provide any coding

**Comment by SS10house** [comment]
Works fine for me as such:
nativefier "https://onenote.com" --internal-urls ".*\.\.*?"

I just took from the example page, and removed the URL, leaving just the "." and the other stuff.
My goal is "open EVERYTHING internally" and hey, it works.

**Comment by SS10house** [comment]
I was able to get the onenote to work with this argument:
`--internal-urls "."`
That keeps everything internal. It just doesnt work for opening documents in excell online and such. Those look like they open a new window, then it just dissapears

**Comment by adishourya** [comment]
> I was able to get the onenote to work with this argument:
> `--internal-urls "."`
> That keeps everything internal. It just doesnt work for opening documents in excell online and such. Those look like they open a new window, then it just dissapears

try  instead --internal-urls "(.*)"
worked for me 
# nativefier -p linux -a x64 -n "msoffice" https://www.office.com/ --internal-urls "(.*)"

**Comment by francispeixoto** [comment]
> > I was able to get the onenote to work with this argument:
> > `--internal-urls "."`
> > That keeps everything internal. It just doesnt work for opening documents in excell online and such. Those look like they open a new window, then it just dissapears
> 
> try instead --internal-urls "(.*)"
> worked for me
> 
> ### nativefier -p linux -a x64 -n "msoffice" https://www.office.com/ --internal-urls "(.*)"

I would add a user agent like Edge to force additional functional compatibility with tools like MS Teams

**Comment by sandeep070** [comment]
> --internal-urls "."

This worked for me - Thanks much!
I was trying to nativefier "Service Now" App.

**Comment by ronjouch** [comment]
I think this is fixed with the recent automatic recognizing of common login pages. Closing, but do shout if some use cases are still broken and we'll re-open.

**Comment by TheCleric** [comment]
It does indeed look like login.microsoftonline.com is not currently supported which seems to cause the need for the `--internal-urls` workaround.

Reopening, but will have a fix soon.

**Comment by TheCleric** [comment]
@prebm this will be fixed in the next release of Nativefier.

**Comment by Greenscreen23** [comment]
@ronjouch 
Hey, I think this is still broken with Microsofts `live.com` website.
e.g. a Nativefier app for `todo.microsoft.com` requires `--internal-urls "live.com"` to be able to login.
My Nativefier version is 46.1.1

**Comment by martin-braun** [comment]
I still have problems with it. I try to login a Microsoft List that I got shared with. Despite trying `.` and `(.*)` as internal url, it won't let me sign in using a one time code. It opens https://invitations.microsoft.com/ConsentAndRedeem?lc=1033 in my primary browser, trying the handshake. It seems to not treat this url as internal, but I tried to set it internal explicitly. It's not working.
