### ISSUE TITLE
Is it possible to send a get request from browser to nativefier app?

### ISSUE THREAD

**Issue by zottirik** [nativefier/nativefier#752]
Is it possible to send a get request from browser to nativefier app?

**Comment by jjlawren** [comment]
https://github.com/jiahaog/nativefier/issues/405 ?

**Comment by zottirik** [comment]
I couldn't find solution for my question :(
Example, I want to open app with a get parameter like this;
mynativefierapp?id=5

Is there any easy way to make this?

Thanks,

**Comment by inglesuniversal** [comment]
GOOD QUESTION

I guess if you had a userid preconfigured you could possibly accomplished that. I have used the internal storage of the browser and it works fine. You could also integrate Firebase web.

**Comment by zottirik** [comment]
I think, my issue is different.
I want to give link from a web page with a href to my app. When I click to link, my app will open. Is it possible?

**Comment by UserNeo** [comment]
That would be an app parameter, how can I read it out via JavaScript in the nativefier app?

**Comment by ronjouch** [comment]
> I want to open [my nativefier] app with a [query] parameter like `mynativefierapp?id=5`
>
> I want to link from a web page with a href to my [nativefier] app. When I click to link, my app will open. Is it possible?

@zottirik you could make your webpage have a link with a custom protocol handler like `mynativefierapp://5`, associate this protocol at your OS level to some script/executable that parses the `5`, builds an associated URL like `http://mynativefierapp/id/5`, then opens your Nativefier app at this URL, using recently-added https://github.com/nativefier/nativefier/pull/1154 .

From this point it's plumbing that is specific to your use case, I don't see anything related to Nativefier. With that, closing.
