### ISSUE TITLE
Basic HTTP auth information is lost in child windows

### ISSUE THREAD

**Issue by nickbe** [nativefier/nativefier#762]
I'm using an invoice app. When generating a PDF then the website would normally open a new tab where the PDF is being displayed. Nativefier opens a new window which is absolutely fine but at the same time I'm presented with a complete new login - which means that the new window forgot all about it's actual session and function.

The website in question is non-public.
The command used to build the executable is:

```
set AUTHNAME=--basic-auth-username "yyyyyyy"
set AUTHPASS=--basic-auth-password "xxxxxxxx" 
set OPTIONS=--show-menu-bar --insecure --conceal --internal-urls "(.*?)" --clear-cache --ignore-certificate
set APPNAME=--name "BackOffice-Wawi"
set URL="https://ccccccccccccccccccccc"
set PLATFORM=--platform "windows" --arch "x64"

nativefier %APPNAME% %OPTIONS% %PLATFORM% %AUTHNAME% %AUTHPASS% %URL%

```
Version of Nativefier is 7.6.11
Node Version is 10.15.2
OS: Windows 10 Pro

**Comment by nickbe** [comment]
Any solution to that?

**Comment by ronjouch** [comment]
@nickbe hmmm, there's a chance that @TheCleric 's https://github.com/nativefier/nativefier/commit/27748889246fa7b83eb84113e1d84abedaa2f708 fixed this issue.

1. Can you give Nativefier 43.1.3 a try?
2. If the issue is still present, a reproduction scenario on a _public_ website will be super useful.

**Comment by nickbe** [comment]
@ronjouch: YESSS .... It works  :) 
This seemed to have done the trick.

Thank you.

**Comment by ronjouch** [comment]
> @ronjouch: YESSS .... It works :)
> This seemed to have done the trick.
> 
> Thank you.

Passing the "thank you" who @TheCleric , who's responsible for the fix.
