### ISSUE TITLE
Can not nativefier Gitbook due to Google OAuth

### ISSUE THREAD

**Issue by a-marionette** [nativefier/nativefier#774]
### Description

After linking to "https://gitbook.com" in nativefier, the sign-in page does not work when using Google's oAuth sign-in feature. An error related to a missing "href" is disclosed.

### Steps to reproduce issue

1. Nativefier https://gitbook.com
2. Attempt to "Sign in" via Google Account option

- Node: v10.15.3
- OS: MacOS

**Comment by TheCleric** [comment]
@a-marionette can you confirm if this issue still exists now that we support known login urls by default in the current version?

**Comment by TheCleric** [comment]
Closing as I have not heard a response back. We can reopen if anyone is still experiencing this.
