### ISSUE TITLE
Spotify doesn't play, and barfs HARMONY_LOCAL_PLAYER_DISABLED errors

### ISSUE THREAD

**Issue by everlydesigns** [nativefier/nativefier#785]
Hey there!

I can't get Spotify to work with nativefier, I get this error in the console when trying to play something:

`Uncaught (in promise) r {code: "HARMONY_LOCAL_PLAYER_DISABLED", message: "Cannot perform command; local player is disabled.", status: -1, debug: {…}}`

Any idea why that might be happening? Here's my full command:

`nativefier --name "Spotify" "https://open.spotify.com/" --title-bar-style 'hidden' --global-shortcuts shortcuts.json --inject spotify.css --min-width 280 --min-height 280 --width 280 --height 280 --internal-urls ".*?"`

I'd like to point out I'm on the latest version of nativefier and I'm running macOS 10.13.6. I'm trying to make a cleaner version of Spotify, so that I'm not distracted by other songs & playlist while working etc.

**Comment by alexandrerochasalles** [comment]
@everlydesigns I know that the this issue was open 2 years ago, but now, are you able to use the Spotify with Nativefier??
