### ISSUE TITLE
Make file open in nativefier app

### ISSUE THREAD

**Issue by foguetes** [nativefier/nativefier#807]
I'm trying to turn skottie.skia.org into an app where when I double click a Lottie .json file, the file is immediately played in the website window. I'm using Windows 10.

In other words, I define the Nativefier created app as the default app for the json filetype and when I double click it the json file is uploaded to skottie.skia.org and displayed.

**Comment by jebeld17** [comment]
This would definitely be great, but I think it would be a lot of maintenance work to keep this feature running.

Such a feature could work like this:
1. Opening a [selected data file format] file in the Nativefied app triggers a macro to run that performs the on-screen clicks and steps necessary to import and open the file from within the browser.

**Comment by ahmedu007** [comment]
Ideally you'd want to create another app with nativefier and add all such features to that

**Comment by mxdpeep** [comment]
You do get the fact, that nativefier is creating an electron Chromium container, right?

**Comment by ronjouch** [comment]
As commenters said, this is out of scope for Nativefier.
