### ISSUE TITLE
Popups are seemingly openend in a new session

### ISSUE THREAD

**Issue by nickbe** [nativefier/nativefier#812]
Popups from web applications seem to loose their session data when openend in new windows.
I'm thrown back to the app login now.

I've tried --internal-urls .*  but this does not seem to have any effect at all.

**Comment by teaearlgraycold** [comment]
This has the effect of making OAuth difficult/impossible to use with the project.

**Comment by ronjouch** [comment]
@nickbe @danthedaniel this might have been fixed by https://github.com/nativefier/nativefier/pull/1174 . Can you give Nativefier 43.1.3 a try? With that, considering this fixed, but will re-open if you say it's not.
