### ISSUE TITLE
[macOS] Nativefier apps "Bundle Identifier" isn't specific enough

### ISSUE THREAD

**Issue by core-code** [nativefier/nativefier#866]
generated apps should be identifiable in some way. 

currently they use the Bundle Identifier

`com.electron.[websitename]
`
which makes them completely indistinguishable from real apps (well, as real as electron apps can be).

i suggest using either
`com.electron. nativefier.[websitename]
`or
`org.nativefier.[websitename]
`as the CFBundleIdentifer for the generated apps

(previouly, generated apps were at least recognisable via the copyright "Crée via OSXNativefier - Created with OSXNativefier - " but even this is not the case anymore)

**Comment by ronjouch** [comment]
@core-code what is the benefit of this? In which context is this "bundle identifier" useful?

**Comment by core-code** [comment]
1.) per Apple's rules, bundle identifiers have to be unique. instead the way they are currently generated they are sure to collide with other apps, with all the negative consequences e.g. for system provided caching and preferences.

2.) we have no way to hide Nativefier apps in our MacUpdater and the same problems will apply to other app-updaters. i am sure users are unhappy if generated pseudo-apps show up in their updaters.

**Comment by ronjouch** [comment]
@core-code thx for the feedback.

1. Okay, I understand point 1 (potential collisions)...
2. ... but I fail to understand point 2. Why would your suggestion of adding a `nativefier.` middle section change anything about "hideabity of Nativefier apps in app updaters"?. Why would `com.electron.nativefier.[websitename]` be more hideable than current `com.electron.[websitename]` ?

**Comment by core-code** [comment]
> Why would your suggestion of adding a nativefier. middle section change anything about "hideabity of Nativefier apps in app updaters"?. 

because if "nativefier" is to the Bundle Identifier somewhere, it becomes possible to ignore all nativefier apps by searching for the substring  "nativefier".

as it currently is, there is no way to know if an "app" with the bundle identifier "com.electron.WEBSITENAMEXYZ" is a real app or made with nativefier.

**Comment by core-code** [comment]
awesome, thanks!
