### ISSUE TITLE
[8.0 regression] Unable to download Electron if behind a proxy

### ISSUE THREAD

**Issue by leinardi** [nativefier/nativefier#907]
### Description

`ts` branch doesn't seem to work behind a proxy anymore.

### Steps to reproduce issue

1. try to nativefy behind a proxy

### Details

- Are you nativefying a *public* website? yes
- Full nativefier command used to build your app: `nativefier --name "Webex-Teams" --platform linux --arch x64 --electron-version 8.0.1 --tray --single-instance --counter --bounce --honest https://teams.webex.com --verbose`
- Version of Nativefier (run `nativefier --version`): `d6ab5f7c7f4b4dc5d4037f88d78efb30f8019b6b`
- Version of node.js (run `node --version`): `v12.14.1`
- OS: `Fedora 31`
- Error message / stack trace (if any):

```
$ nativefier --name "Webex-Teams" --platform linux --arch x64 --electron-version 8.0.0 --tray --single-instance --counter --bounce --honest https://teams.webex.com --verbose
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.

Performing async options post-processing.
Inferring user agent for electron 8.0.0 / linux
Grabbing electron<->chrome versions file from https://atom.io/download/atom-shell/index.json
Inferring icon for https://teams.webex.com/ on linux
Inferring icon from store for https://teams.webex.com/ on linux
Allowed icon formats when building for linux: [ '.png', '.ico' ]
Got name Webex-Teams from options. No inferring needed
Sanitized filename for Webex-Teams : Webex-Teams
Cannot automatically retrieve the app icon: Error: connect ECONNREFUSED 185.199.111.153:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '185.199.111.153',
  port: 443
}
Unable to infer chrome version for user agent, using 78.0.3904.130
Given chrome 78.0.3904.130 on linux, using user agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.130 Safari/537.36

Preparing Electron app...
Copying electron app from /home/rleinardi/temp/nativefier/app to /tmp/nativefier-9-46-33-app-63148KjEmZwTEQEqH
Writing app config to /tmp/nativefier-9-46-33-app-63148KjEmZwTEQEqH/nativefier.json
No files to inject, skipping copy.
Updating /tmp/nativefier-9-46-33-app-63148KjEmZwTEQEqH/package.json 'name' field to webex-teams-nativefier-ff9bb8

Converting icons...
Option "icon" not set, skipping icon conversion.

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 14.2.1
  electron-packager Node v12.14.1
  electron-packager Host Operating system: linux 5.4.13-201.fc31.x86_64 (x64) +0ms
  electron-packager Packager Options: {"arch":"x64","asar":false,"darwinDarkModeSupport":false,"dir":"/tmp/nativefier-9-46-33-app-63148KjEmZwTEQEqH","electronVersion":"8.0.0","name":"Webex-Teams","out":"/home/rleinardi","overwrite":true,"platform":"linux","targetUrl":"https://teams.webex.com/","tmpdir":false,"win32metadata":{"ProductName":"Webex-Teams","InternalName":"Webex-Teams","FileDescription":"Webex-Teams"}} +0ms
  electron-packager Target Platforms: linux +0ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring appVersion from version in /tmp/nativefier-9-46-33-app-63148KjEmZwTEQEqH/package.json +0ms
  electron-packager Application name: Webex-Teams +5ms
  electron-packager Target Electron version: 8.0.0 +0ms
  electron-packager Ignored path regular expressions: [
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$',
  '/tmp/electron-packager'
] +0ms
  electron-packager Downloading Electron with options {"platform":"linux","arch":"x64","version":"8.0.0","artifactName":"electron"} +0ms
Error during build: GotError [RequestError]: connect ECONNREFUSED 140.82.118.3:443
    at ClientRequest.<anonymous> (/home/rleinardi/temp/nativefier/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:313:26)
    at ClientRequest.emit (events.js:228:7)
    at ClientRequest.origin.emit (/home/rleinardi/temp/nativefier/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  name: 'RequestError',
  code: 'ECONNREFUSED',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/electron/electron/releases/download/v8.0.0/electron-v8.0.0-linux-x64.zip',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://github.com/electron/electron/releases/download/v8.0.0/electron-v8.0.0-linux-x64.zip',
  gotOptions: {
    path: '/electron/electron/releases/download/v8.0.0/electron-v8.0.0-linux-x64.zip',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'github.com',
    port: null,
    hostname: 'github.com',
    hash: null,
    search: null,
    query: null,
    pathname: '/electron/electron/releases/download/v8.0.0/electron-v8.0.0-linux-x64.zip',
    href: 'https://github.com/electron/electron/releases/download/v8.0.0/electron-v8.0.0-linux-x64.zip',
    retry: {
      retries: [Function],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: true,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    method: 'GET'
  }
}

```
The environmental variable for the proxy are correctly set and working for other tools (e.g. npm):
```
ftp_proxy=http://localhost:3128/
https_proxy=http://localhost:3128
http_proxy=http://localhost:3128
```

In the current master the icon is correctly shown:
```
$ nativefier --name "Webex-Teams" --platform linux --arch x64 --electron-version 8.0.0 --tray --single-instance --counter --bounce --honest https://teams.webex.com --verbose
  inferring [                                                  ] 0%Unable to infer chrome version for user agent, using 61.0.3163.100
Cannot automatically retrieve the app icon: Error: connect ECONNREFUSED 185.199.109.153:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '185.199.109.153',
  port: 443
}
Downloading tmp-63615-1-SHASUMS256.txt-8.0.0
[============================================>] 100.0% of 5.65 kB (5.65 kB/s)
Packaging app for platform linux x64 using electron v8.0.0

App built to /home/rleinardi/Webex-Teams-linux-x64

```

**Comment by ronjouch** [comment]
> In the current master the icon is correctly shown

@leinardi not sure I understand you. What I see is that:

1. In both cases, getting the icon fails
2. *But* apparently, `electron-packager`'s job used to work in Nativefier 7.7.1.

Put differently: when nativefying behind a proxy, you never had an icon, but used to be able to successfully build. Now you still don't have an icon, and app build fails. Correct?

**Comment by leinardi** [comment]
Yep, I think that's correct: current stable can still download electron and build the wrapper, with the icon missing, ts just fails immediately because it is unable to download electron.

**Comment by ronjouch** [comment]
> Yep, I think that's correct: current stable can still download electron and build the wrapper, with the icon missing, ts just fails immediately because it is unable to download electron.

@leinardi hm, interesting.

Could this just be "working-ish" in 7.7.1 stable because your Electron got cached as you first downloaded the demanded Electron on a proxy-less connection? Put differently, in the ts branch, does nativefier succeed if you first run the same command behind a proxy-less connection (which will cache Electron), THEN re-run it behind a proxy (which will use the cached Electron)?

Or are you sure things worked plain better on the proxy side in 7.7.1 stable? I'm asking these suspicions because I changed almost nothing around the call to electron-packager and would be hoping for the exact same behavior & bugs. I'm not sure where to look.

Thanks for the fast feedback, I don't have a proxy at hand here, your precisions will help fixing that.

**Comment by leinardi** [comment]
> Could this just be "working-ish" in 7.7.1 stable because your Electron got cached as you first downloaded the demanded Electron on a proxy-less connection
> are you sure things worked plain better on the proxy side in 7.7.1 stable

I thought of the same thing and to be sure I tried with a brand new version of electron that I had never downloaded before.

Now, just to triple check, I downloaded another version 7.1.12, that was release the 10th of February.
I can see the download progress via command line:
![image](https://user-images.githubusercontent.com/273338/74658358-60d70200-5192-11ea-8867-7066246c3b93.png)
And I can see the spike of usage in my network monitor:  ![image](https://user-images.githubusercontent.com/273338/74658388-78ae8600-5192-11ea-95bf-0998b477438b.png)

I can confirm that the current release installed via `npm install nativefier -g` works fine behind prozxy.

**Comment by ronjouch** [comment]
> I can confirm that the current release installed via `npm install nativefier -g` works fine behind prozxy.

@leinardi okay, thanks for double-checking. I'm a bit puzzled as I don't remember changing anything how electron-packager (which does the downloading) is called.

If you have time to spare and want to try helping, the call to `electron-packager` is at https://github.com/jiahaog/nativefier/blob/ts/src/build/buildMain.ts#L116 , and here are [the dev docs](https://github.com/jiahaog/nativefier/blob/ts/docs/development.md).

**Comment by ronjouch** [comment]
@leinardi got it; electron-packager now uses https://github.com/electron/get#proxies , which say:

> Downstream packages should utilize the `initializeProxy` function to add HTTP(S) proxy support. If the environment variable `ELECTRON_GET_USE_PROXY` is set, it is called automatically. A different proxy module is used, depending on the version of Node in use, and as such, there are slightly different ways to set the proxy environment variables. For Node 10 and above, [`global-agent`](https://github.com/gajus/global-agent#environment-variables) is used. Otherwise, [`global-tunnel-ng`](https://github.com/np-maintain/global-tunnel#auto-config) is used. Refer to the appropriate linked module to determine how to configure proxy support.

I'd like your help, as I don't have a proxy for tests. Can you test on both node<10 and node>=10, and tell me me how you had to set up environment variables for each? 

- When running node>=10, see https://github.com/gajus/global-agent#faq
- When running node<10, see https://github.com/np-maintain/global-tunnel#auto-config

Thanks 🙂.

**Comment by leinardi** [comment]
Hey, these days I'm not able to test, sorry :'(

**Comment by ronjouch** [comment]
> Hey, these days I'm not able to test, sorry :'(

@leinardi no problem. Will release with a note in a "Known Issues" section, someone else will jump on it. Thanks for the report anyway 🙂.
