### ISSUE TITLE
Tray icon is blank on macOS

### ISSUE THREAD

**Issue by altechzilla** [nativefier/nativefier#942]
When having an app open, it adds an invisible icon item to the OS top bar.

1. There should be a parameter to change that to an actual icon
2. There should be a parameter to remove it completely.

Example 1:
<img width="207" alt="Untitled" src="https://user-images.githubusercontent.com/8274669/78501628-e109f480-774b-11ea-850f-b563ab6c0f83.png">

Example 2: [View GIF](https://share.getcloudapp.com/geu2ng77)

**Comment by ronjouch** [comment]
@Abruptive please respect the [bug report issue template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Quoting its first three lines:

```
Help us help you, please take the time to fill this information 🙂.
An incomprehensible bug report is a useless bug report.
Incomprehensible / incomplete bug reports will be closed.
```

**Comment by Abruptive** [comment]
---
name: Bug Report / Feature
about: When having an app open, it adds an invisible icon item to the OS top bar.
labels: bug

---

**Bug description**
When having an app open, it adds an invisible icon item to the OS top bar.
- There should be a parameter to change that to an actual icon
- There should be a parameter to remove it completely.

- [X] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [X] I searched existing open & closed issues. Yes, my bug is new.
- [X] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Steps to reproduce**
Bundle any app with Nativefier.

**Expected behavior**
Shouldn't show an invisible icon.

**Actual behavior**
Shows an invisible icon.

**Debug info**
Example 1:
<img width="207" alt="Untitled" src="https://user-images.githubusercontent.com/8274669/78501628-e109f480-774b-11ea-850f-b563ab6c0f83.png">

Example 2: [View GIF](https://share.getcloudapp.com/geu2ng77)

**Context**
 - Nativefier: Latest
 - Node.js: Latest
 - Npm: Latest
 - OS: macOS

**Comment by Abruptive** [comment]
@ronjouch

**Comment by ronjouch** [comment]
@Abruptive nope, still incomplete:

> **Steps to reproduce**
> Give your ***full*** nativefier command, with the ***`--verbose` flag***, on a ***public*** site:

and

> **Debug info**
> Verbose logs (command-line and/or in app DevTools console)

and

> **Context**
> - Nativefier: (for example: 8.0.4)
> - Node.js: (for example: 13.11.0)
> - Npm: (for example: 6.14.7)

**Comment by Abruptive** [comment]
**JS**
```
var nativefier = require('nativefier').default;

var options = {
    name: 'Intercom',
    targetUrl: 'https://app.intercom.com/',
    appCopyright: 'Abruptive',
    appVersion: '1.0.0',
    counter: true,
    bounce: true,
    width: 1600,
    height: 1000,
    showMenuBar: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    enableEs3Apis: false,
    insecure: false,
    internalUrls: '.*?\.webflow.com/\.*?',
    hideWindowFrame: true,
    titleBarStyle: 'hiddenInset',
    disableDevTools: true,
    disableContextMenu: true,
    singleInstance: true,
    clearCache: false,
    tray: 'stay-in-tray',
    darwinDarkModeSupport: true,
    platform: 'darwin',
    arch: 'x64',
    version: '1.0.0',
    out: './build',
    overwrite: true,
    inject: [
        './source/css/styles.css',
        './source/css/scripts.js',
    ],
    asar: false,
    icon: './source/img/icon-intercom.png',
    fastQuit: false,
    // userAgent: 'Mozilla ...', // will infer a default for your current system
    honest: false,
    zoom: 1.0,
    // fileDownloadOptions: {
    //     saveAs: true // always show "Save As" dialog
    // },
    // processEnvs: {
    //     "GOOGLE_API_KEY": "<your-google-api-key>"
    // }
    win32metadata: {
        CompanyName: 'Intercom',
        FileDescription: 'Intercom Desktop App',
        OriginalFilename: 'Intercom',
        ProductName: 'Intercom',
        InternalName: 'Intercom'
    }
};

nativefier(options, function(error, appPath) {
    if (error) {
        console.error(error);
        return;
    }
    console.log('App has been nativefied to', appPath);
});
```

**Context:**
Nativefier: 8.0.6
Node.js: 12.11.0
Npm: 6.14.3

**Comment by ronjouch** [comment]
@Abruptive thanks. Well, already now I know you're using the programmatic interface, which is relatively untested.

So,

1. I don't have a mac and tray/trayicon works for me on Linux, so what I'm looking at, for a blind fix, is a trace in `verbose` logs of something gone wrong with icon preparation, or a potential warning. For CLI users it's the `--verbose` flag, for you please pass `verbose: true` in your options and come back with logs.
2. Also, what if you manually convert your `./source/img/icon-intercom.png` to an icns file (using the tool of your choice) and pass `icon: ./source/img/icon-intercom.icns` ?
3. Finally, 1. was to get errors at build time. Can you run your app from the terminal and report about *run* -time errors/warnings?

**Comment by ikiK-CRO** [comment]
I have same issue 

![Screen Shot 2020-04-08 at 09 10 18](https://user-images.githubusercontent.com/25029344/78755685-d92f9780-7979-11ea-8940-4321165e29b5.png)

Nativefier: 8.0.6 AND  8.0.0 tested.
Node.js: v13.12.0
Npm: 6.14.4
OS: OSX 10.11.6 (15G22010)

My verbose log:
[Running in verbose mode!.txt](https://github.com/jiahaog/nativefier/files/4448841/Running.in.verbose.mode.txt)

**Comment by aagarw33** [comment]
Hello @ronjouch I have same issue, Can you please help? Thanks.

Nativefier: 8.0.7
Node.js: 8.9.1
Npm: 5.5.1
OS: OSX 10.15.4 (19E287)

`nativefier --tray start-in-tray --single-instance  www.facebook.com  --name "Facebook" --verbose `

**Logs:**
[logs.txt](https://github.com/jiahaog/nativefier/files/4690283/logs.txt)

<img width="168" alt="Screen Shot 2020-05-27 at 11 55 20 AM" src="https://user-images.githubusercontent.com/7662849/83050056-9309c280-a011-11ea-842f-6b41ca3421ed.png">
