### ISSUE TITLE
Incorrect icon detection due to name false positives (e.g. bing.com matching ing.com)

### ISSUE THREAD

**Issue by lgarron** [nativefier/nativefier#969]
Thanks for writing this! This kind of thing used to be such a chore, and I was excited to see something so simple to use. :-D

However, I had a bit of a shock on my very first try, so I thought I'd report it.

**Bug description**

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.mdtimer.cubing.net
- [x] I searched existing open & closed issues. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases (I'm actually going straight off the repo source.)

**Steps to reproduce**

1. Run `nativefier timer.cubing.net`

(Or `nativefier bing.com`.)

**Expected behavior**
End up with an app that has the https://timer.cubing.net icon.

(Or the Bing icon)

**Actual behavior**
End up with an app that has the [ING icon](https://github.com/jiahaog/nativefier-icons/blob/gh-pages/files/ing.png)

**Debug info**
N/A

**Context**
 - Nativefier: 1d3bed5f09961e878c4c40085bd69aa2159d3a4c
 - Node.js: v13.13.0
 - Npm: v6.14.4
 - OS: macOS 10.15.4

**Comment by lgarron** [comment]
I'm filing the issue in this repo (rather than https://github.com/jiahaog/nativefier-icons) because the cause of this behaviour is:

https://github.com/jiahaog/nativefier/blob/master/src/infer/inferIcon.ts#L95

This takes the icon store heuristic and accepts it unconditionally if there is a full string match. Unfortunately, `ing.com` is so short that there is no icon heuristic name longer than `ing` that can be used (https://github.com/jiahaog/nativefier-icons#naming-convention).

However, the substring [a very common suffix](https://en.wikipedia.org/wiki/-ing) and so the ING icon will be used for many sites with verbs in their name. There is no way for an affected site to override this right now, no matter what the site response is.

I'd like to suggest one of:
- Removing the `ing` icon.
- Adding a new convention to the heuristic that allows marking an icon name as a match only for an exact domain (so that the ING icon only matches `ing.com`, or an exact domain label (so that `ing.org` or `someth.ing.com` match).
  - The latter might work for ING, but it wouldn't work for a file name like `status` (which might stand for `status.io`) without also including many status pages  (e.g. status.github.com).
- Taking the icon from the target site if there is a reasonably large icon (although the dimension threshold might have to be quite low to make a difference).

**Comment by Miladiir** [comment]
Just ran into this problem for https://web.getbring.com

Very annoying since I am also a customer of ING, so this was pretty confusing.

**Comment by TheCleric** [comment]
Since we have removed the `ing.com` icon that gave so many false positives, has anyone else had an issue with this?

**Comment by lgarron** [comment]
Look`ing` good!

<img width="509" alt="Screen Shot 2021-10-01 at 18 23 36" src="https://user-images.githubusercontent.com/248078/135699495-7bc3b024-3f8a-402e-92ac-698028e32204.png">

**Comment by dawaltconley** [comment]
Hi, I'm getting a false positive for https://player.fm, which is using the Google Play Music icon. Tried to provide a custom icon using the `--icon` path but it seems to be ignoring that; is that intended or should it be possible to override?
