### ISSUE TITLE
Microsoft Teams App | Screen Share Issue on MacOS

### ISSUE THREAD

**Issue by s-ahuja** [nativefier/nativefier#971]
**Bug description**
Unable to perform a screen share when using the nativefied Teams App.

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [x] I searched existing open & closed issues. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Steps to reproduce**
Give your ***full*** nativefier command, with the ***`--verbose` flag***, on a ***public*** site:

nativefier "https://teams.microsoft.com/_\?tenantID\=<my_org_tenant_id>" --name "Microsoft Teams Second" --internal-urls '.*' --icon icon.icns -p mac --counter --bounce 

**Expected behavior**
1. Should be able to do a screen share like i am with Chrome / (or any other browser when using teams.microsoft.com in a browser session)

**Actual behavior**
1. Clicking on Screen Sharing button opens a window - about what to share
2. Select Window/Desktop - nothing happens

**Context**
 - Nativefier: 8.0.7
 - Node.js: - v13.12.0
 - Npm: - 6.14.4
 - OS: MacOS 10.15.4

**Comment by ronjouch** [comment]
Closing as dup of https://github.com/nativefier/nativefier/issues/927 .
