### ISSUE TITLE
[OSX] Clicking on desktop notification from gmail results in empty new window.

### ISSUE THREAD

**Issue by jottr** [nativefier/nativefier#98]
I have wrapped my gmail with nativefier. 
When I receive a new email, I get a desktop notification. When clicking it, gmail generates a new window in nativefier, which has no content. In chrome, this new window displays the message content. 

```
$ nativefier --version
6.6.1

$ node --version
v5.4.1

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.2
BuildVersion:   15C50
```

**Comment by jottr** [comment]
https://github.com/jiahaog/nativefier/issues/88

**Comment by TheCleric** [comment]
@jottr in light of #88 being fixed (via #955) can you confirm if this is still an issue?

**Comment by jottr** [comment]
@TheCleric sorry, I can't.  I haven't used nativefier in over 5 years.

**Comment by TheCleric** [comment]
Thanks. Closing this, but will reopen if this appears to still be an issue for others.
