### ISSUE TITLE
[Feature Request] Change Export Folder Name as a Flag?

### ISSUE THREAD

**Issue by dragonBall561** [nativefier/nativefier#995]
**Problem statement**
I would like it if you could change the folder name that Nativefier saves a web app to. For example, I run `nativefier -n "Example" https://example.com` It would export it as in the folder `example-linux-x64`. I would like it if you could change the name of the folder in the same command that makes the web app. For example, you could make the flag -folder and run it like this:
```
nativefier -n "Example" -folder "The-Folder-Name-That-I-Want" https://example.com
```
And the package would be `whatever directory you opened the Terminal / The-Folder-Name-That-I-Want`. It is more work (for me) to change the folder's name afterward.

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md, no existing option fits my needs.
- [x] I searched existing open & closed issues. Yes, my issue is new.

**Suggested solution**
I want to be able to change the folder's name in the same command that makes the app

**Alternative solutions**
Renaming the folder afterward.

**Context**
 - Nativefier: 9.0.0
 - Node.js: 12.18.1
 - Npm: 6.14.5
 - OS: Linux Mint 19.3 Cinnamon
 - Additional context: None

**Comment by ronjouch** [comment]
> **Alternative solutions**
> Renaming the folder afterward.

Yup. You're the first one to ask for something like this and it's easily automatable with a little ` && mv foo bar`, so IMHO this isn't something that deserves a flag. Closing for now.

**Comment by YAMLcase** [comment]
I'd like this as well
